In [1]:
#This is the program for analsis

In [1]:
import pandas as pd 
import numpy as np

In [2]:
df_kk_cn = pd.read_csv('input/kishakoutei_china.csv')
df_ar_cn = pd.read_csv('input/arxiv_china.csv')
df_ar_noncn = pd.read_csv('input/arxiv_nonchina.csv')

In [4]:
pd.set_option('display.max_colwidth', None)

In [6]:
df_kk_cn.head(10)

,reference,title,title_en,keywords,date,link,paperid,ref_no,ref_author,ref_title,ref_journal,ref_type,matched_title,language,countries,doi
0,PADEN B， ČÁP M， YONG S Z， et al. A survey of motion planning and control techniques for self-driving urban vehicles［J］. IEEE Transactions on Intelligent Vehicles， 2016， 1（1）： 33-35.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,1,PADEN B， ČÁP M， YONG S Z， et al,A survey of motion planning and control techniques for self-driving urban vehicles,IEEE Transactions on Intelligent Vehicles， 2016， 1（1）： 33-35.,J,NaN,en,"['US','CZ']",NaN
1,WATZENIG D， HORN H. Automated driving： safer and more efficient future driving［M］. Springer Cham， 2016.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,2,WATZENIG D， HORN H,Automated driving： safer and more efficient future driving,Springer Cham， 2016.,M,Automated Driving Safer and More Efficient Future Driving Foreword,en,[],NaN
2,AMER N H， ZAMZURI H， HUDHA K， et al. Modelling and control strategies in path tracking control for autonomous ground vehicles： a review of state of the art and challenges［J］. Journal of Intelligent & Robotic Systems， 2017， 86： 225-254.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,3,AMER N H， ZAMZURI H， HUDHA K， et al,Modelling and control strategies in path tracking control for autonomous ground vehicles： a review of state of the art and challenges,Journal of Intelligent & Robotic Systems， 2017， 86： 225-254.,J,Modelling and Control Strategies in Path Tracking Control for Autonomous Ground Vehicles: A Review of State of the Art and Challenges,en,"['MY', 'MY', 'MY']",https://doi.org/10.1007/s10846-016-0442-0
3,DUAN J L， GUAN Y， LI S E， et al. Distributional soft actor-critic： off-policy reinforcement learning for addressing value estimation errors ［J］. IEEE Transactions on Neural Networks and Learning Systems， 2022， 33（11）： 6584-6598.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,4,DUAN J L， GUAN Y， LI S E， et al,Distributional soft actor-critic： off-policy reinforcement learning for addressing value estimation errors,IEEE Transactions on Neural Networks and Learning Systems， 2022， 33（11）： 6584-6598.,J,Distributional Soft Actor-Critic: Off-Policy Reinforcement Learning for Addressing Value Estimation Errors,en,"['CN', 'CN', 'CN', 'CN', 'CN', 'CN']",https://doi.org/10.1109/tnnls.2021.3082568
4,LIN Z Y， MA J， DUAN J L， et al. Policy iteration based approximate dynamic programming toward autonomous driving in constrained dynamic environment［J］. IEEE Transactions on Intelligent Transportation Systems， 2023， 24（5）： 5003-5013.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,5,LIN Z Y， MA J， DUAN J L， et al,Policy iteration based approximate dynamic programming toward autonomous driving in constrained dynamic environment,IEEE Transactions on Intelligent Transportation Systems， 2023， 24（5）： 5003-5013.,J,Policy Iteration Based Approximate Dynamic Programming Toward Autonomous Driving in Constrained Dynamic Environment,en,"['CN', 'HK', 'CN', 'CN', 'CN', 'CN', 'SG']",https://doi.org/10.1109/tits.2023.3237568
5,LIU M， ZHAO F， YIN J L， et al. Reinforcement- tracking： an effective trajectory tracking and navigation method for autonomous urban driving［J］. IEEE Transactions on Intelligent Transportation Systems， 2022， 23（7）： 6991-7007.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,6,LIU M， ZHAO F， YIN J L， et al,Reinforcement- tracking： an effective trajectory tracking and navigation method for autonomous urban driving,IEEE Transactions on Intelligent Transportation Systems， 2022， 23（7）： 6991-7007.,J,Reinforcement-Tracking: An Effective Trajectory Tracking and Navigation Method for Autonomous Urban Driving,en,"['CN', 'CN', 'CN', 'CN', 'CN', 'CN']",https://doi.org/10.1109/tits.2021.3066366
6,SHAN Y X， ZHENG B L， CHEN L S， et al. A reinforcement learning-based adaptive path tracking approach for autonomous driving［J］. IEEE Transactions on Vehicular Technology， 2020， 69（10）： 10581-10595.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,7,SHAN Y X， ZHENG B L， CHEN L S， et al,A reinforcement learning-based adaptive path tracking approach for autonomous driving,IEEE Transactions on Vehicular Technology， 2020， 69（10）： 10581-10595.,J,A Reinforcement Learning-Based Adaptive Path Tracking Approach for Autonomous Driving,en,"['CN', 'CN', 'CN', 'CN', 'CN']",https://doi.org/10.1109/tvt.2020.3014628
7,杜国栋， 邹渊， 张旭东， 等. 基于双估计强化学习结合前向预测控制的自动驾驶运动控制研究［J］. 汽车工程， 2024， 46（4）： 564-576.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,8,杜国栋， 邹渊， 张旭东， 等,基于双估计强化学习结合前向预测控制的自动驾驶运动控制研究,汽车工程， 2024， 46（4）： 564-576.,J,NaN,cn,"['CN', 'SW']",NaN
8,XU S B， PENG H. Design， analysis， and experiments of preview path tracking control for autonomous vehicles［J］. IEEE Transactions on Intelligent Transportation Systems， 2020， 21（1）： 48-58.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,9,XU S B， PENG H,Design， analysis， and experiments of preview path tracking control for autonomous vehicles,IEEE Transactions on Intelligent Transportation Systems， 2020， 21（1）： 48-58.,J,NaN,en,"['US', 'US']",NaN
9,XU S B， PENG H， TANG Y F. Preview path tracking control with delay compensation for autonomous vehicles［J］. IEEE Transactions on Intelligent Transportation Systems， 2021， 22（5）： 2979-2989.,基于模型预测路径积分和输出调节的层级运动控制,A Cascade Control Scheme for Path Tracking with Model Predictive Path Integral and Output Regulator,"autonomous driving,MPPI,underactuated,output regulator,",2024/10/21,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007,41,10,XU S B， PENG H， TANG Y F,Preview path tracking control with delay compensation for autonomous vehicles,IEEE Transactions on Intelligent Transportation Systems， 2021， 22（5）： 2979-2989.,J,Preview Path Tracking Control With Delay Compensation for Autonomous Vehicles,en,"['US', 'US']",https://doi.org/10.1109/tits.2020.2978417

In [8]:
df_kk_cn['title'].value_counts()

title
飞行汽车关键技术及应用研究综述                   207
面向自动驾驶的大模型对齐技术：综述                 119
基于多粒度关系推理的自动驾驶域自适应视觉目标检测算法         40
基于模型预测路径积分和输出调节的层级运动控制             38
基于实例激活图的自动驾驶实时实例分割算法               38
自动驾驶等级提高条件下驾驶人驾驶姿势变化规律分析           37
基于BEV特征融合的3D目标检测方法                 36
基于多信息融合网络的行人轨迹预测方法                 35
基于LiDAR点云特征补全的雪天无人车目标检测            34
城市道路场景下考虑多类交通参与者的多模态车辆轨迹预测方法研究     33
语义驱动的4D雷达与相机融合目标检测                 31
基于双分支实例分割网络的复杂环境车道线检测方法            30
基于级联YOLOv7的自动驾驶三维目标检测              29
基于人机博弈的驾驶权接管控制策略                   28
匝道汇入场景下基于交互场模型的驾驶员交互行为研究           26
自动驾驶环境下车道级雷视融合SLAM                 25
环境车辆轨迹拟人学习的自动驾驶仿真场景构建方法            23
引入自监督预训练的轨迹预测方法                    23
基于改进分层可拓理论的智能汽车AFS/DYC协调控制         23
面向量产自动驾驶域控制器多传感器同步方法研究             22
基于有向图的城市交叉口场景相似性评价方法               22
仿驾驶员DDPG汽车纵向自动驾驶决策方法               21
基于双目逆投影的停车位占位快速检测方法                20
基于角度交并比和自适应生命周期的三维多目标跟踪算法          20
车载雷达关键场景的数据采集与标记方法                 19
线控转向相似性路径跟踪的综合控制器设计                17
基于复合动态采样的自动驾驶矿车节能路径规划方法            15
基于结构化意图建模的自动驾驶类人性决策策略研究            14
Name: count, dtype: int64

In [13]:
papers_kk_cn = df_kk_cn['title'].unique()

In [70]:
i=0
n=0
k=0
d=0
e=0
for paper in papers_kk_cn:
    print(paper)
    df_temp = df_kk_cn[df_kk_cn['title'] == paper]
    a = len(df_temp[(df_temp['language'] == 'cn')|(df_temp['language'] == 'zh')])
    b = len(df_temp[(df_temp['language'] == 'en')&((df_temp['countries'].str.contains('CN'))|(df_temp['countries'].str.contains('HK')))])
    c = len(df_temp)
    d = d+a
    e = e+b
    f = len(df_temp[(df_temp['language'] == 'en')&(df_temp['countries'].str.contains('US'))])
    
    print(a,b,c-b-a,f)
    print(round(a/c,2),round(b/c,2),round((c-b-a)/c,2))
    if a/c > 0.3:
        print ('yes')
        i=i+1
    if b/c > 0.3:
        print ('yes')
        n=n+1
    if (a+b)>f:
        print('china')
        k=k+1
    else:
        print('US')
print(i,n,k)
print(d/28,e/28,k/28)

基于模型预测路径积分和输出调节的层级运动控制
2 10 26 16
0.05 0.26 0.68
US
面向自动驾驶的大模型对齐技术：综述
3 52 64 61
0.03 0.44 0.54
yes
US
基于多信息融合网络的行人轨迹预测方法
3 10 22 10
0.09 0.29 0.63
china
基于双目逆投影的停车位占位快速检测方法
4 5 11 3
0.2 0.25 0.55
china
环境车辆轨迹拟人学习的自动驾驶仿真场景构建方法
10 10 3 6
0.43 0.43 0.13
yes
yes
china
匝道汇入场景下基于交互场模型的驾驶员交互行为研究
3 6 17 13
0.12 0.23 0.65
US
城市道路场景下考虑多类交通参与者的多模态车辆轨迹预测方法研究
8 5 20 7
0.24 0.15 0.61
china
语义驱动的4D雷达与相机融合目标检测
4 16 11 7
0.13 0.52 0.35
yes
china
线控转向相似性路径跟踪的综合控制器设计
12 2 3 0
0.71 0.12 0.18
yes
china
基于结构化意图建模的自动驾驶类人性决策策略研究
1 10 3 1
0.07 0.71 0.21
yes
china
面向量产自动驾驶域控制器多传感器同步方法研究
11 6 5 3
0.5 0.27 0.23
yes
china
基于人机博弈的驾驶权接管控制策略
7 18 3 9
0.25 0.64 0.11
yes
china
飞行汽车关键技术及应用研究综述
48 36 123 68
0.23 0.17 0.59
china
基于LiDAR点云特征补全的雪天无人车目标检测
5 9 20 8
0.15 0.26 0.59
china
自动驾驶环境下车道级雷视融合SLAM
11 9 5 1
0.44 0.36 0.2
yes
yes
china
基于角度交并比和自适应生命周期的三维多目标跟踪算法
3 9 8 6
0.15 0.45 0.4
yes
china
基于多粒度关系推理的自动驾驶域自适应视觉目标检测算法
4 16 20 11
0.1 0.4 0.5
yes
china
引入自监督预训练的轨迹预测方法
1 6 16 9
0.04 0.26 0.7
US
车载雷达关键场景的数据采集与标记方法
2 4 13 6
0.11 0.21 0.68
US
基于改进分层可拓理论的智能汽车AFS/DYC协调控制
12 5 6 5
0.52 0.22 0.26
yes
china
基于BEV特征融合的3D目标检测方法
3 13 20 12
0.08 0.36 0.56
yes
china
基于级联YOLOv7的自动驾驶三维目标检测
6 8 15 10
0.21 0.28 0.52
china
基于实例激活图的自动驾驶实时实例分割算法
3 11 24 9
0.08 0.29 0.63
china
仿驾驶员DDPG汽车纵向自动驾驶决策方法
6 6 9 4
0.29 0.29 0.43
china
基于双分支实例分割网络的复杂环境车道线检测方法
5 12 13 6
0.17 0.4 0.43
yes
china
自动驾驶等级提高条件下驾驶人驾驶姿势变化规律分析
3 2 32 15
0.08 0.05 0.86
US
基于有向图的城市交叉口场景相似性评价方法
5 8 9 7
0.23 0.36 0.41
yes
china
基于复合动态采样的自动驾驶矿车节能路径规划方法
6 2 7 2
0.4 0.13 0.47
yes
china
6 11 22
6.821428571428571 10.928571428571429 0.7857142857142857

In [30]:
df_ar_cn.head(10)

,citing_arxiv_id,citing_title,cited_title,cited_year,cited_doi,cited_arxiv,status,matched_title,language,countries
0,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,Equivariant diffusion solution for inorganic crystal structure determination from powder X-ray diffraction data,2026.0,10.1038/s41467-026-70035-9,NaN,ok,Equivariant diffusion solution for inorganic crystal structure determination from powder X-ray diffraction data,en,"CN,IE"
1,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,Machine learning-driven crystal system prediction for perovskites using augmented XRD data,2026.0,10.1016/j.engappai.2025.113247,2602.04435,ok,Machine learning-driven crystal system prediction for perovskites using augmented XRD data,en,AE
2,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,Automated phase mapping of high-throughput X-ray diffraction data encoded with domain-specific materials science knowledge,2025.0,10.1038/s41524-025-01837-6,NaN,ok,Automated phase mapping of high-throughput X-ray diffraction data encoded with domain-specific materials science knowledge,en,"CN,US"
3,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,KAN-enhanced contrastive learning: the accelerator of crystal structure identification from XRD patterns,2025.0,10.1038/s41524-026-02015-y,2511.04055,ok,KAN-enhanced contrastive learning: the accelerator of crystal structure identification from XRD patterns,en,"AU,CN,HK"
4,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,Dara: Automated Multiple-Hypothesis Phase Identification and Refinement from Powder X‑ray Diffraction,2025.0,10.1021/acs.chemmater.5c02820,2510.19667,ok,Dara: Automated Multiple-Hypothesis Phase Identification and Refinement from Powder X-ray Diffraction,en,US
5,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,XQueryer: an intelligent crystal structure identifier for powder X-ray diffraction,2025.0,10.1093/nsr/nwaf421,NaN,ok,XQueryer: an intelligent crystal structure identifier for powder X-ray diffraction,en,"CN,HK"
6,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,Machine learning in X-ray diffraction for materials discovery and characterization,2025.0,10.1016/j.matt.2025.102272,NaN,ok,Machine learning in X-ray diffraction for materials discovery and characterization,en,US
7,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,Interpretable X-ray diffraction spectra analysis using confidence evaluated deep learning enhanced by template element replacement,2025.0,10.1038/s41524-025-01743-x,NaN,ok,Interpretable X-ray diffraction spectra analysis using confidence evaluated deep learning enhanced by template element replacement,en,CN
8,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,Computational investigation into XRD peak broadening effects with discrete dislocation dynamics in additively manufactured 316L stainless steel,2024.0,10.1016/j.jmps.2024.105970,NaN,ok,Computational investigation into XRD peak broadening effects with discrete dislocation dynamics in additively manufactured 316L stainless steel,en,"DE,US"
9,2607.2088,MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction,Crystallographic phase identifier of a convolutional self-attention neural network (CPICANN) on powder diffraction patterns,2024.0,10.1107/S2052252524005323,NaN,ok,Crystallographic phase identifier of a convolutional self-attention neural network (CPICANN) on powder diffraction patterns,en,"CN,HK"

In [32]:
papers_ar_cn = df_ar_cn['citing_title'].unique()

In [79]:
## a 中国語の数a
## b 中国の機関の数
## c 全体の数
## d e 中国の数の合計（平均用）
## f アメリカの機関の数
## g 中国かつアメリカの数
## i 中国語が1/3以上の数
## n 中国の機関が1/3以上の数
## k 中国の機関がアメリカの機関より多い論文の数
## l 同数の論文の数

In [91]:
i=0
n=0
k=0
l=0
d=0
e=0
g=0
for paper in papers_ar_cn:
    print(paper)
    df_temp = df_ar_cn[df_ar_cn['citing_title'] == paper]
    a = len(df_temp[(df_temp['language'] == 'cn')|(df_temp['language'] == 'zh')])
    b = len(df_temp[(df_temp['language'] == 'en')&((df_temp['countries'].str.contains('CN'))|(df_temp['countries'].str.contains('HK')))])
    c = len(df_temp)
    d = d+a
    e = e+b
    f = len(df_temp[(df_temp['language'] == 'en')&(df_temp['countries'].str.contains('US'))])
    g= len(df_temp[(df_temp['language'] == 'en')&((df_temp['countries'].str.contains('CN'))|(df_temp['countries'].str.contains('HK')))&(df_temp['countries'].str.contains('US'))])
    
    print(a,b,c-b-a,f,g)
    print(round(a/c,2),round(b/c,2),round((c-b-a)/c,2))
    if a/c > 0.3:
        print ('yes')
        i=i+1
    if b/c > 0.3:
        print ('yes')
        n=n+1
    if (a+b)>f:
        print('china')
        k=k+1
    elif (a+b)==f:
        print('same')
        l=l+1
    else:
        print('US')
    df_temp2 =df_temp['countries'].value_counts()
    #print(df_temp2.index[0],df_temp2.iat[0])
    #print(df_temp2.index[1],df_temp2.iat[1])
    #print(df_temp2.index[2],df_temp2.iat[2])
    #print(df_temp2.index[3],df_temp2.iat[3])

    print("------")

    
print(i,n,k,l)
print(d/25,e/25,k/25)

MatDiffract: A Material-Informed Automated Analysis Platform for X-ray Powder Diffraction
2 10 26 13 2
0.05 0.26 0.68
US
------
S-squared-VLA: Decoupling Semantic and Spatial Streams in Vision-Language-Action Models for Autonomous Driving
0 21 9 9 3
0.0 0.7 0.3
yes
china
------
Hierarchical Fault Localization for Autonomous Driving Systems with Hypothesis Validation and Intent Analysis
0 18 35 22 1
0.0 0.34 0.66
yes
US
------
A Risk-Field Enhanced Closed-Loop Digital Twin Framework for Autonomous Driving Safety Validation
0 8 14 11 4
0.0 0.36 0.64
yes
US
------
A Comprehensive Study of Implementation Bugs in Multi-modal Agents
2 32 26 21 12
0.03 0.53 0.43
yes
china
------
Learning from Mistakes: Rollout-Retrieval Lifelong Policy Learning for Autonomous Driving
0 34 26 22 8
0.0 0.57 0.43
yes
china
------
ASTAD: Asymmetric Style Transfer for Synthetic-to-Real Adaptation in Autonomous Driving
0 17 26 15 4
0.0 0.4 0.6
yes
china
------
DIMOS: Disentangling Instance-level Moving Object Segmentation
0 29 29 19 2
0.0 0.5 0.5
yes
china
------
Learning from Human Driving: A Human-in-the-Loop Online Behavior Cloning Framework for Autonomous Driving
0 9 16 8 0
0.0 0.36 0.64
yes
china
------
PLAN-S: Bridging Planning with Latent Style Dynamics for Autonomous Driving World Models
0 27 16 12 5
0.0 0.63 0.37
yes
china
------
Does Visual Information Play a Decisive Role in Vision-Language-Action Model Driving Behavior?
0 15 12 9 2
0.0 0.56 0.44
yes
china
------
IDOL: Inverse-Dynamics-Guided Future Prediction for End-to-End Autonomous Driving
0 59 23 22 11
0.0 0.72 0.28
yes
china
------
IAF-Net: Illumination-Adaptive Fusion for Low-Light Urban Road Segmentation
1 21 14 11 4
0.03 0.58 0.39
yes
china
------
nuReasoning: A Reasoning-Centric Dataset and Benchmark for Long-Tail Autonomous Driving
0 38 46 39 6
0.0 0.45 0.55
yes
US
------
Variational Inference for Evidential Deep Learning
0 5 31 15 2
0.0 0.14 0.86
US
------
RCGDet3D: Rethinking 4D Radar-Camera Fusion-based 3D Object Detection with Enhanced Radar Feature Encoding
0 19 10 6 2
0.0 0.66 0.34
yes
china
------
KG-ASG: Collision-Knowledge-Guided Closed-Loop Adversarial Scenario Generation With Primary-Support Attribution
0 26 16 14 4
0.0 0.62 0.38
yes
china
------
Cross-Sample Relational Fusion: Unifying Domain Generalization and Class-Incremental Learning
0 37 46 27 3
0.0 0.45 0.55
yes
china
------
Physically Native World Models: A Hamiltonian Perspective on Generative World Modeling
0 0 35 28 0
0.0 0.0 1.0
US
------
Do Open-Loop Metrics Predict Closed-Loop Driving? A Cross-Benchmark Correlation Study of NAVSIM and Bench2Drive
0 18 13 10 4
0.0 0.58 0.42
yes
china
------
TRIP-Evaluate: An Open Multimodal Benchmark for Evaluating Large Models in Transportation
1 18 25 21 3
0.02 0.41 0.57
yes
US
------
Transferable Physical-World Adversarial Patches Against Object Detection in Autonomous Driving
0 38 20 13 4
0.0 0.66 0.34
yes
china
------
Transferable Physical-World Adversarial Patches Against Pedestrian Detection Models
0 34 23 17 4
0.0 0.6 0.4
yes
china
------
MotionScape: A Large-Scale Real-World Highly Dynamic UAV Video Dataset for World Models
0 5 23 20 3
0.0 0.18 0.82
US
------
0 20 16 0
0.24 21.52 0.64

In [39]:
papers_ar_noncn = df_ar_noncn['citing_title'].unique()

In [81]:
i=0
n=0
k=0
l=0
d=0
e=0
g=0
for paper in papers_ar_noncn:
    print(paper)
    df_temp = df_ar_noncn[df_ar_noncn['citing_title'] == paper]
    a = len(df_temp[(df_temp['language'] == 'cn')|(df_temp['language'] == 'zh')])
    b = len(df_temp[(df_temp['language'] == 'en')&((df_temp['countries'].str.contains('CN'))|(df_temp['countries'].str.contains('HK')))])
    c = len(df_temp)
    d = d+a
    e = e+b
    f = len(df_temp[(df_temp['language'] == 'en')&(df_temp['countries'].str.contains('US'))])
    g= len(df_temp[(df_temp['language'] == 'en')&((df_temp['countries'].str.contains('CN'))|(df_temp['countries'].str.contains('HK')))&(df_temp['countries'].str.contains('US'))])
    
    print(a,b,c-b-a,f,g)
    print(round(a/c,2),round(b/c,2),round((c-b-a)/c,2))
    if a/c > 0.3:
        print ('yes')
        i=i+1
    if b/c > 0.3:
        print ('yes')
        n=n+1
    if (a+b)>f:
        print('china')
        k=k+1
    elif (a+b)==f:
        print('same')
        l=l+1
    else:
        print('US')
print(i,n,k,l)
print(d/25,e/25,k/25)

BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning
0 16 12 9 2
0.0 0.57 0.43
yes
china
AUTOPILOT VQA: Benchmarking Vision-Language Models for Incident-Centric Dashcam Understanding
0 1 11 6 0
0.0 0.08 0.92
US
Flow-ERD: Agent-type Aware Flow Matching with Entropy-Regularized Distillation for Diverse Traffic Simulation
0 10 30 27 2
0.0 0.25 0.75
US
Who Responds When the Driver Is Gone? A Framework for Human Intent Understanding
0 7 19 15 2
0.0 0.27 0.73
US
CLEAR: Closed-Loop Reinforcement Learning at Scale for End-to-End Autonomous Driving
0 37 31 29 9
0.0 0.54 0.46
yes
china
CRRL: A Causality-Based Reinforcement Learning Framework for Autonomous System Recovery
0 4 43 21 1
0.0 0.09 0.91
US
Creating Impactful Autonomous Driving Datasets: A Strategic Guide from Research Gap to Benchmark
0 15 33 17 4
0.0 0.31 0.69
yes
US
CommonRoad-Game: A Human-in-the-Loop Simulation Framework for Autonomous Driving
0 1 16 8 1
0.0 0.06 0.94
US
Reasoning-aware Speculative Decoding for Efficient Vision-Language-Action Models in Autonomous Driving
0 14 17 17 5
0.0 0.45 0.55
yes
US
SENSE-VAD: Sentient and Semantic Video Anomaly Detection for Autonomous Driving
0 18 37 27 3
0.0 0.33 0.67
yes
US
Horizon3D: Sparse Radar-Camera Fusion for Long-Range 3D Perception in Autonomous Driving
0 24 21 11 5
0.0 0.53 0.47
yes
china
HSDF-Lane: Height-Aligned Signed Distance Field with Semantic Lane Prior for 3D Lane Detection
0 39 26 15 5
0.0 0.6 0.4
yes
china
Off the Rails: Hijacking the Scoring Head in Generative End-to-End Driving Planners with Safety-Violating Adversarial Perturbations
0 22 37 38 9
0.0 0.37 0.63
yes
US
Knowledge-Driven Dimension Estimation from a Single Image -3D Asset Generation Technology for Digital Twin Construction
0 3 22 9 2
0.0 0.12 0.88
US
TrafficAlign: Aligning Large Language Models for Traffic Scenario Generation
0 11 51 37 3
0.0 0.18 0.82
US
CascadeOcc: Rethinking 3D Occupancy World Models with Cascaded VQ Representations
0 18 13 8 1
0.0 0.58 0.42
yes
china
Characterizing Driver Interactions with Autonomous Vehicles via Response Maps
0 0 24 18 0
0.0 0.0 1.0
US
Towards Safety-Aware Mutation Testing for Autonomous Driving Systems
0 7 33 15 1
0.0 0.17 0.82
US
Beyond Bayer: Task-Optimal Sensor Co-Design for Robust Autonomous-Driving Segmentation
0 5 27 19 2
0.0 0.16 0.84
US
Mind the Noise: Sensitivity of Transformer-based Interaction-Aware Trajectory Prediction Models to Noisy Data
0 7 10 5 1
0.0 0.41 0.59
yes
china
CRAX: Fast Safe Reinforcement Learning Benchmarking
0 5 39 25 2
0.0 0.11 0.89
US
ARGUSTRACK: A Multi-View Annotation System for Multi-Object Tracking
0 7 18 7 2
0.0 0.28 0.72
same
Self-Driving Negotiator: An interactive, verifiable benchmark for social negotiation and theory of mind under hidden intent
0 2 9 8 1
0.0 0.18 0.82
US
RT-VLA: Real-Time Vision-Language-Action Models via Knowledge Distillation
0 7 12 8 0
0.0 0.37 0.63
yes
US
0 11 6 1
0.0 11.2 0.24

In [66]:
df_new = df_ar_cn['cited_title'].value_counts().reset_index(name='count')

In [67]:
df_new.head(20)

,cited_title,count
0,nuScenes: A Multimodal Dataset for Autonomous Driving,8
1,CARLA: An Open Urban Driving Simulator,7
2,DiffusionDrive: Truncated Diffusion Model for End-to-End Autonomous Driving,6
3,NAVSIM: Data-Driven Non-Reactive Autonomous Vehicle Simulation and Benchmarking,6
4,VAD: Vectorized Scene Representation for Efficient Autonomous Driving,6
5,Planning-oriented Autonomous Driving,6
6,Parting with Misconceptions about Learning-based Vehicle Motion Planning,5
7,Deep Residual Learning for Image Recognition,5
8,AutoVLA: A Vision-Language-Action Model for End-to-End Autonomous Driving with Adaptive Reasoning and Reinforcement Fine-Tuning,4
9,PARA-Drive: Parallelized Architecture for Real-Time Autonomous Driving,4
10,TransFuser: Imitation With Transformer-Based Sensor Fusion for Autonomous Driving,4
11,Hydra-MDP: End-to-end Multimodal Planning with Multi-target Hydra-Distillation,4
12,SparseDrive: End-to-End Autonomous Driving via Sparse Scene Representation,4
13,VADv2: End-to-End Vectorized Autonomous Driving via Probabilistic Planning,4
14,Is Ego Status All You Need for Open-Loop End-to-End Autonomous Driving?,4
15,ReCogDrive: A Reinforced Cognitive Framework for End-to-End Autonomous Driving,3
16,DriveLM: Driving with Graph Visual Question Answering,3
17,OpenDriveVLA: Towards End-to-end Autonomous Driving with Large Vision Language Action Model,3
18,Towards learning-based planning: The nuPlan benchmark for real-world autonomous driving,3
19,End-to-End Autonomous Driving: Challenges and Frontiers,3