In [1]:
#This is the program to get information about not chinese comapnies' papers

In [3]:
import pprint

import arxiv
import pandas as pd

In [12]:
import time
import requests
import xml.etree.ElementTree as ET

In [13]:
# ArXiv APIのエンドポイント
base_url = "http://export.arxiv.org/api/query"

# 著者名
author_name = "Teja Gollapudi"

# APIリクエストのパラメータ
params = {
    "search_query": f"au:{author_name}",
    "max_results": 10,
    "start": 0,
    "sortBy": "submittedDate",
    "sortOrder": "descending"
}

# APIリクエストを送信
response = requests.get(base_url, params=params)

# XMLレスポンスをパースする
root = ET.fromstring(response.text)

# 論文情報を取得
for entry in root.findall("{http://www.w3.org/2005/Atom}entry"):
    # タイトル
    title = entry.find("{http://www.w3.org/2005/Atom}title").text

    # 著者
    authors = []
    for author in entry.findall("{http://www.w3.org/2005/Atom}author"):
        name = author.find("{http://www.w3.org/2005/Atom}name").text
        authors.append(name)

    # 公開日
    published = entry.find("{http://www.w3.org/2005/Atom}published").text

    # リンク
    link = entry.find("{http://www.w3.org/2005/Atom}id").text

    # 結果を出力
    print("Title:", title)
    print("Authors:", ", ".join(authors))
    print("Published:", published)
    print("Link:", link)
    print("---")
import requests
import xml.etree.ElementTree as ET
# ArXiv APIのエンドポイント
base_url = "http://export.arxiv.org/api/query"

# 著者名
author_name = "Teja Gollapudi"

# APIリクエストのパラメータ
params = {
    "search_query": f"au:{author_name}",
    "max_results": 10,
    "start": 0,
    "sortBy": "submittedDate",
    "sortOrder": "descending"
}

# APIリクエストを送信
response = requests.get(base_url, params=params)

# XMLレスポンスをパースする
root = ET.fromstring(response.text)

# 論文情報を取得
for entry in root.findall("{http://www.w3.org/2005/Atom}entry"):
    # タイトル
    title = entry.find("{http://www.w3.org/2005/Atom}title").text

    # 著者
    authors = []
    for author in entry.findall("{http://www.w3.org/2005/Atom}author"):
        name = author.find("{http://www.w3.org/2005/Atom}name").text
        authors.append(name)

    # 公開日
    published = entry.find("{http://www.w3.org/2005/Atom}published").text

    # リンク
    link = entry.find("{http://www.w3.org/2005/Atom}id").text

    # 結果を出力
    print("Title:", title)
    print("Authors:", ", ".join(authors))
    print("Published:", published)
    print("Link:", link)
    print("---")

Title: Photometric and Spectroscopic Studies of Type Ic Supernovae SN 2020akf and SN 2021mxx
Authors: Mulchand Kurre, K. R. Sahu, Shrutika Tiwari, Yogita Patel, N. K. Chakradhari, D. K. Sahu, Rishabh Singh Teja, G. C. Anupama, Mridweeka Singh, Anirban Dutta, Anjasha Gangopadhyay
Published: 2026-07-14T09:00:32Z
Link: http://arxiv.org/abs/2607.12525v1
---
Title: SN 2025aico: Early observations of a faint Type IIb supernova with a low-mass envelope
Authors: J. -W. Zhao, A. Pastorello, B. Kumar, Y. -Z. Cai, A. Dutta, D. K. Sahu, A. Reguitti, R. S. Teja, H. Das, T. J. Moriya, N. Pyykkinen, K. Valeckas, G. Valerin, X. -Z. Zou, C. Ashall, S. Bijavara Seshashayana, G. -W. Du, G. C. Anupama, A. L. Bouquin, S. Campana, K. Chatterjee, X. -L. Chen, X. -L. Du, N. Elias-Rosa, Y. Fang, M. Fraser, W. Hoogendam, E. Hsiao, E. Kankare, E. P. Lagioia, W. -Y. Li, X. -K. Liu, P. Lundqvist, K. Matilainen, J. Martikainen, K. Medler, N. Morrell, Y. Pan, C. Pfeffer, G. Rameshan, T. M. Reynolds, M. D. Stritzinger, V. Vuolteenaho, Z. -Y. Wang, H. -F. Xiao, J. -H. Zhang, X. -W. Liu, Y. -P. Yang
Published: 2026-07-12T09:31:35Z
Link: http://arxiv.org/abs/2607.10671v1
---
Title: Learning When to Intervene on Habitual Behaviors: A Case Study in Oral Health Care
Authors: Bhanu Teja Gullapalli, Vivek Shetty, Anna L. Trella, Asim H. Gazi, Susan A. Murphy
Published: 2026-07-10T15:28:15Z
Link: http://arxiv.org/abs/2607.09518v1
---
Title: Validating Virtual Reality for Studying Multimodal Human-Robot Interaction in Socially Aware Robot Navigation
Authors: Hariharan Arunachalam, Phani Teja Singamaneni, Rachid Alami
Published: 2026-07-10T10:23:57Z
Link: http://arxiv.org/abs/2607.09261v1
---
Title: Multi-Sender Bayesian Persuasion with Imperfect Information
Authors: Andra Siva Sai Teja, Ganesh Ghalme, Sujit Gujar
Published: 2026-07-09T16:37:07Z
Link: http://arxiv.org/abs/2607.08675v1
---
Title: Can Language Models Actually Retrieve In-Context? Drowning in Documents at Million Token Scale
Authors: Siddharth Gollapudi, Nilesh Gupta, Prasann Singhal, Sewon Min
Published: 2026-07-01T23:38:25Z
Link: http://arxiv.org/abs/2607.01538v1
---
Title: SelectAnyTree: A Promptable Instance Segmentation Model for 3D Forest LiDAR Point Clouds
Authors: Trung Thanh Nguyen, Daniel Lusk, Kilian Gerberding, Janusch Vajna-Jehle, Tuan-Anh Vu, Duc Viet Le, Tu Vo, Phi Le Nguyen, Yasutomo Kawanishi, Takahiro Komamizu, Ichiro Ide, Julian Frey, Teja Kattenborn
Published: 2026-06-25T19:15:36Z
Link: http://arxiv.org/abs/2606.27491v1
---
Title: Two years of shock interaction tracing three phases of evolution: the explosion of a Type IIn supernova, SN 2019vxm
Authors: Gitika Rameshan, Rishabh Singh Teja, D. K. Sahu, G. C. Anupama, Masayuki Yamanaka, Keiichi Maeda, Tatsuya Nakaoka, Sota Goto, Brajesh Kumar, Avinash Singh, Miho Kawabata, Koji S. Kawabata, Kenta Taguchi
Published: 2026-06-24T14:45:39Z
Link: http://arxiv.org/abs/2606.25896v1
---
Title: HelpBench: Assessing the Ability of LLMs to Provide Privacy, Safety, and Security Advice
Authors: Sarah Meiklejohn, Sunny Consolvo, Patrick Gage Kelley, Tara Matthews, Sai Teja Peddinti, Renee Shelby, Lenin Simicich, Kurt Thomas
Published: 2026-06-23T17:05:19Z
Link: http://arxiv.org/abs/2606.24819v1
---
Title: Computational references are not experiments: pre-registered validation of machine-learned sodium-cathode voltages
Authors: Krishna Teja Vepa
Published: 2026-06-19T07:51:30Z
Link: http://arxiv.org/abs/2606.23725v2
---
Title: Photometric and Spectroscopic Studies of Type Ic Supernovae SN 2020akf and SN 2021mxx
Authors: Mulchand Kurre, K. R. Sahu, Shrutika Tiwari, Yogita Patel, N. K. Chakradhari, D. K. Sahu, Rishabh Singh Teja, G. C. Anupama, Mridweeka Singh, Anirban Dutta, Anjasha Gangopadhyay
Published: 2026-07-14T09:00:32Z
Link: http://arxiv.org/abs/2607.12525v1
---
Title: SN 2025aico: Early observations of a faint Type IIb supernova with a low-mass envelope
Authors: J. -W. Zhao, A. Pastorello, B. Kumar, Y. -Z. Cai, A. Dutta, D. K. Sahu, A. Reguitti, R. S. Teja, H. Das, T. J. Moriya, N. Pyykkinen, K. Valeckas, G. Valerin, X. -Z. Zou, C. Ashall, S. Bijavara Seshashayana, G. -W. Du, G. C. Anupama, A. L. Bouquin, S. Campana, K. Chatterjee, X. -L. Chen, X. -L. Du, N. Elias-Rosa, Y. Fang, M. Fraser, W. Hoogendam, E. Hsiao, E. Kankare, E. P. Lagioia, W. -Y. Li, X. -K. Liu, P. Lundqvist, K. Matilainen, J. Martikainen, K. Medler, N. Morrell, Y. Pan, C. Pfeffer, G. Rameshan, T. M. Reynolds, M. D. Stritzinger, V. Vuolteenaho, Z. -Y. Wang, H. -F. Xiao, J. -H. Zhang, X. -W. Liu, Y. -P. Yang
Published: 2026-07-12T09:31:35Z
Link: http://arxiv.org/abs/2607.10671v1
---
Title: Learning When to Intervene on Habitual Behaviors: A Case Study in Oral Health Care
Authors: Bhanu Teja Gullapalli, Vivek Shetty, Anna L. Trella, Asim H. Gazi, Susan A. Murphy
Published: 2026-07-10T15:28:15Z
Link: http://arxiv.org/abs/2607.09518v1
---
Title: Validating Virtual Reality for Studying Multimodal Human-Robot Interaction in Socially Aware Robot Navigation
Authors: Hariharan Arunachalam, Phani Teja Singamaneni, Rachid Alami
Published: 2026-07-10T10:23:57Z
Link: http://arxiv.org/abs/2607.09261v1
---
Title: Multi-Sender Bayesian Persuasion with Imperfect Information
Authors: Andra Siva Sai Teja, Ganesh Ghalme, Sujit Gujar
Published: 2026-07-09T16:37:07Z
Link: http://arxiv.org/abs/2607.08675v1
---
Title: Can Language Models Actually Retrieve In-Context? Drowning in Documents at Million Token Scale
Authors: Siddharth Gollapudi, Nilesh Gupta, Prasann Singhal, Sewon Min
Published: 2026-07-01T23:38:25Z
Link: http://arxiv.org/abs/2607.01538v1
---
Title: SelectAnyTree: A Promptable Instance Segmentation Model for 3D Forest LiDAR Point Clouds
Authors: Trung Thanh Nguyen, Daniel Lusk, Kilian Gerberding, Janusch Vajna-Jehle, Tuan-Anh Vu, Duc Viet Le, Tu Vo, Phi Le Nguyen, Yasutomo Kawanishi, Takahiro Komamizu, Ichiro Ide, Julian Frey, Teja Kattenborn
Published: 2026-06-25T19:15:36Z
Link: http://arxiv.org/abs/2606.27491v1
---
Title: Two years of shock interaction tracing three phases of evolution: the explosion of a Type IIn supernova, SN 2019vxm
Authors: Gitika Rameshan, Rishabh Singh Teja, D. K. Sahu, G. C. Anupama, Masayuki Yamanaka, Keiichi Maeda, Tatsuya Nakaoka, Sota Goto, Brajesh Kumar, Avinash Singh, Miho Kawabata, Koji S. Kawabata, Kenta Taguchi
Published: 2026-06-24T14:45:39Z
Link: http://arxiv.org/abs/2606.25896v1
---
Title: HelpBench: Assessing the Ability of LLMs to Provide Privacy, Safety, and Security Advice
Authors: Sarah Meiklejohn, Sunny Consolvo, Patrick Gage Kelley, Tara Matthews, Sai Teja Peddinti, Renee Shelby, Lenin Simicich, Kurt Thomas
Published: 2026-06-23T17:05:19Z
Link: http://arxiv.org/abs/2606.24819v1
---
Title: Computational references are not experiments: pre-registered validation of machine-learned sodium-cathode voltages
Authors: Krishna Teja Vepa
Published: 2026-06-19T07:51:30Z
Link: http://arxiv.org/abs/2606.23725v2
---

In [16]:
response.text

'<?xml version=\'1.0\' encoding=\'UTF-8\'?>\n<feed xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/" xmlns:arxiv="http://arxiv.org/schemas/atom" xmlns="http://www.w3.org/2005/Atom">\n  <id>https://arxiv.org/api/KI/OLOBca0UxWWu1zAmv9MGUpEY</id>\n  <title>arXiv Query: search_query=au:Teja OR all:Gollapudi&amp;id_list=&amp;start=0&amp;max_results=10</title>\n  <updated>2026-07-20T03:08:19Z</updated>\n  <link href="https://arxiv.org/api/query?search_query=au:Teja+OR+all:Gollapudi&amp;start=0&amp;max_results=10&amp;id_list=" type="application/atom+xml"/>\n  <opensearch:itemsPerPage>10</opensearch:itemsPerPage>\n  <opensearch:totalResults>492</opensearch:totalResults>\n  <opensearch:startIndex>0</opensearch:startIndex>\n  <entry>\n    <id>http://arxiv.org/abs/2607.12525v1</id>\n    <title>Photometric and Spectroscopic Studies of Type Ic Supernovae SN 2020akf and SN 2021mxx</title>\n    <updated>2026-07-14T09:00:32Z</updated>\n    <link href="https://arxiv.org/abs/2607.12525v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2607.12525v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>We present a comprehensive analysis of optical photometry and medium-resolution spectroscopy for Type Ic supernovae (SNe) SN 2020akf and SN 2021mxx. Our study covers the evolution of SN 2020akf from -5 to 109 days and SN 2021mxx from -3 to 115 days relative to their B-band maximum. Their peak quasi-bolometric luminosities are estimated at logL_bol = 42.37 +- 0.02 and 42.21 +- 0.02 erg/s, respectively. The velocities of the ejecta, derived from the Fe II 5169 A line at maximum light, are approximately 15000 km/s for SN~2020akf and about 10000 km/s for SN~2021mxx, which are consistent with those observed in other Type~Ic SNe. Using the semianalytical Arnett model, we estimate that SN 2020akf has a kinetic energy of E_k = 6.33 (+0.68)(-0.62) x 10^51 erg and an ejected mass of M_ej = 4.71 (+0.50)(-0.46) M_sun, while for SN 2021mxx, we get E_k = 0.54 (+0.08)(-0.12) x 10^51 erg and M_ej = 0.90 (+0.14)(-0.18),M_sun. The mass of Ni56 synthesized in the explosion is estimated at 0.10 +- 0.02 M_sun for SN 2020akf and 0.05 +- 0.01 M_sun for SN 2021mxx. The metallicities of the host galaxies near the SN regions are ~0.81 Z_sun for SN 2020akf and ~0.76 Z_sun for SN 2021mxx, where Z_sun indicates solar metallicity. Our detailed analysis suggests that SN 2020akf falls into the category of a transitional Type Ic SN, having spectral properties between normal and broad-line Type Ic SNe, while SN 2021mxx is a normal Type Ic SN with an extremely low value of the M_ej / E_k ratio.</summary>\n    <category term="astro-ph.HE" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="astro-ph.SR" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2026-07-14T09:00:32Z</published>\n    <arxiv:comment>Accepted for publication in ApJ. 28 Pages, 21 Figures, 7 Tables</arxiv:comment>\n    <arxiv:primary_category term="astro-ph.HE"/>\n    <author>\n      <name>Mulchand Kurre</name>\n    </author>\n    <author>\n      <name>K. R. Sahu</name>\n    </author>\n    <author>\n      <name>Shrutika Tiwari</name>\n    </author>\n    <author>\n      <name>Yogita Patel</name>\n    </author>\n    <author>\n      <name>N. K. Chakradhari</name>\n    </author>\n    <author>\n      <name>D. K. Sahu</name>\n    </author>\n    <author>\n      <name>Rishabh Singh Teja</name>\n    </author>\n    <author>\n      <name>G. C. Anupama</name>\n    </author>\n    <author>\n      <name>Mridweeka Singh</name>\n    </author>\n    <author>\n      <name>Anirban Dutta</name>\n    </author>\n    <author>\n      <name>Anjasha Gangopadhyay</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2607.10671v1</id>\n    <title>SN 2025aico: Early observations of a faint Type IIb supernova with a low-mass envelope</title>\n    <updated>2026-07-12T09:31:35Z</updated>\n    <link href="https://arxiv.org/abs/2607.10671v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2607.10671v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>We aimed to investigate the physical properties and the underlying explosion mechanisms of the Type IIb SN 2025aico. Through a comprehensive analysis of early-phase optical light curves and spectroscopic data, we aim to constrain the fundamental explosion parameters and evaluate the physical state of the event. We present early multi-band optical imaging and low-resolution optical spectroscopic follow-up observations of the Type IIb SN 2025aico, spanning approximately 70 days from the explosion. We constrain the properties of SN 2025aico by utilizing a hybrid model that combines shock-cooling emission and radioactively powered diffusion, as well as by analyzing the spectroscopic evolution. We use various approaches to constrain the 56Ni mixing from early data, and also compared our spectra with models to constrain the properties of the progenitor. The explosion epoch of SN 2025aico is estimated to be MJD 61032.69, while the rise time in the r_M-band is 22.30 +/- 0.70 days. The peak pseudo-bolometric luminosity in the optical bands is L_opt = (4.07 +/- 0.10) x 10^41 erg/s. The fitting yields a moderate to relatively low 56Ni mass of M_Ni = 0.033 +0.006/-0.004 M_sun and an ejecta mass of M_ej = 2.79 +0.21/-0.18 M_sun. The photospheric velocity near the bolometric peak, measured from the Fe II lambda 5169 line, is 6450 +180/-160 km/s. The derived envelope properties suggest a compact He-star progenitor possessing an H-rich envelope of M_env approx. 0.01 M_sun and a radius of R_env approx. 6-10 R_sun. The derived physical properties of SN 2025aico indicate an origin from a moderate-mass, stripped He-star in a compact binary system, characterized by a minimal residual hydrogen envelope. The explosion itself demonstrates weak to moderate 56Ni mixing throughout the ejecta.</summary>\n    <category term="astro-ph.SR" scheme="http://arxiv.org/schemas/atom"/>\n    <category term="astro-ph.HE" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2026-07-12T09:31:35Z</published>\n    <arxiv:comment>20 pages, 14 figures, submit to Astronomy &amp; Astrophysics</arxiv:comment>\n    <arxiv:primary_category term="astro-ph.SR"/>\n    <author>\n      <name>J. -W. Zhao</name>\n    </author>\n    <author>\n      <name>A. Pastorello</name>\n    </author>\n    <author>\n      <name>B. Kumar</name>\n    </author>\n    <author>\n      <name>Y. -Z. Cai</name>\n    </author>\n    <author>\n      <name>A. Dutta</name>\n    </author>\n    <author>\n      <name>D. K. Sahu</name>\n    </author>\n    <author>\n      <name>A. Reguitti</name>\n    </author>\n    <author>\n      <name>R. S. Teja</name>\n    </author>\n    <author>\n      <name>H. Das</name>\n    </author>\n    <author>\n      <name>T. J. Moriya</name>\n    </author>\n    <author>\n      <name>N. Pyykkinen</name>\n    </author>\n    <author>\n      <name>K. Valeckas</name>\n    </author>\n    <author>\n      <name>G. Valerin</name>\n    </author>\n    <author>\n      <name>X. -Z. Zou</name>\n    </author>\n    <author>\n      <name>C. Ashall</name>\n    </author>\n    <author>\n      <name>S. Bijavara Seshashayana</name>\n    </author>\n    <author>\n      <name>G. -W. Du</name>\n    </author>\n    <author>\n      <name>G. C. Anupama</name>\n    </author>\n    <author>\n      <name>A. L. Bouquin</name>\n    </author>\n    <author>\n      <name>S. Campana</name>\n    </author>\n    <author>\n      <name>K. Chatterjee</name>\n    </author>\n    <author>\n      <name>X. -L. Chen</name>\n    </author>\n    <author>\n      <name>X. -L. Du</name>\n    </author>\n    <author>\n      <name>N. Elias-Rosa</name>\n    </author>\n    <author>\n      <name>Y. Fang</name>\n    </author>\n    <author>\n      <name>M. Fraser</name>\n    </author>\n    <author>\n      <name>W. Hoogendam</name>\n    </author>\n    <author>\n      <name>E. Hsiao</name>\n    </author>\n    <author>\n      <name>E. Kankare</name>\n    </author>\n    <author>\n      <name>E. P. Lagioia</name>\n    </author>\n    <author>\n      <name>W. -Y. Li</name>\n    </author>\n    <author>\n      <name>X. -K. Liu</name>\n    </author>\n    <author>\n      <name>P. Lundqvist</name>\n    </author>\n    <author>\n      <name>K. Matilainen</name>\n    </author>\n    <author>\n      <name>J. Martikainen</name>\n    </author>\n    <author>\n      <name>K. Medler</name>\n    </author>\n    <author>\n      <name>N. Morrell</name>\n    </author>\n    <author>\n      <name>Y. Pan</name>\n    </author>\n    <author>\n      <name>C. Pfeffer</name>\n    </author>\n    <author>\n      <name>G. Rameshan</name>\n    </author>\n    <author>\n      <name>T. M. Reynolds</name>\n    </author>\n    <author>\n      <name>M. D. Stritzinger</name>\n    </author>\n    <author>\n      <name>V. Vuolteenaho</name>\n    </author>\n    <author>\n      <name>Z. -Y. Wang</name>\n    </author>\n    <author>\n      <name>H. -F. Xiao</name>\n    </author>\n    <author>\n      <name>J. -H. Zhang</name>\n    </author>\n    <author>\n      <name>X. -W. Liu</name>\n    </author>\n    <author>\n      <name>Y. -P. Yang</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2607.09518v1</id>\n    <title>Learning When to Intervene on Habitual Behaviors: A Case Study in Oral Health Care</title>\n    <updated>2026-07-10T15:28:15Z</updated>\n    <link href="https://arxiv.org/abs/2607.09518v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2607.09518v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>A central challenge for digital health interventions aimed at improving habitual behaviors is deciding when to deliver an intervention prompt. For many daily habits, such as tooth brushing or eating, individuals tend to act around a usual time of day, but this timing is not fixed and can shift as routines evolve. When intervention timing is selected in advance and held constant throughout a study, it can gradually become misaligned with behavior, causing interventions to potentially arrive after the behavior has already occurred or too early to be effective. In this work, we address this habitual timing misalignment in digital health interventions by proposing an online decision-making framework that continuously adapts intervention timing as individual behavior patterns change. Rather than treating intervention timing as a static design choice, our framework adapts it over time and integrates it into a sequential process that determines both when and whether to deliver an intervention. Using data from a deployed oral health intervention trial as a case study, we evaluate our approach using both observed data and simulated settings to assess how well different intervention timing strategies align with the timing of brushing events. Across these evaluations, we measure performance using a coverage-based metric that captures whether an intervention is delivered sufficiently close to a subsequent brushing event. We find that adaptive intervention timing consistently improves coverage compared to fixed intervention times based on user-provided input. The proposed framework is currently deployed in an ongoing randomized controlled trial of a digital oral health intervention, with preliminary results that are consistent with and further support our prior evaluations.</summary>\n    <category term="cs.HC" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2026-07-10T15:28:15Z</published>\n    <arxiv:comment>28 pages, 2 figures</arxiv:comment>\n    <arxiv:primary_category term="cs.HC"/>\n    <author>\n      <name>Bhanu Teja Gullapalli</name>\n    </author>\n    <author>\n      <name>Vivek Shetty</name>\n    </author>\n    <author>\n      <name>Anna L. Trella</name>\n    </author>\n    <author>\n      <name>Asim H. Gazi</name>\n    </author>\n    <author>\n      <name>Susan A. Murphy</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2607.09261v1</id>\n    <title>Validating Virtual Reality for Studying Multimodal Human-Robot Interaction in Socially Aware Robot Navigation</title>\n    <updated>2026-07-10T10:23:57Z</updated>\n    <link href="https://arxiv.org/abs/2607.09261v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2607.09261v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>Virtual Reality (VR) offers a flexible and controllable platform for studying human-robot interaction. Prior work has explored VR for socially aware robot navigation. However, whether VR captures the multimodal interaction dynamics observed in real-world human-robot co-navigation remains insufficiently understood. In this work, we present a VR prototype and evaluate its suitability for studying multimodal human-robot interaction (HRI) in socially aware navigation. Specifically, we investigate whether VR preserves the multimodal interaction dynamics observed in real-world human-robot co-navigation. We conducted a within-subjects study (N = 21) in which participants interacted with a PR2 mobile manipulator robot in both a motion capture equipped arena and its virtual replica in an immersive VR environment. Two common co-navigation scenarios were examined : orthogonal crossing and pass-by interactions. Participants evaluated the robot\'s perceived social awareness and interaction comfort, while trajectory and head-orientation data were analysed to examine behavioral responses during the interaction. Our results show that participants perceive the robot\'s socially aware navigation similarly in VR and in the real world. Furthermore, VR captures human interaction behaviors in ways consistent with real-world observations. These findings suggest that VR can be a reliable and flexible platform for studying richer multimodal behaviors in social navigation and HRI.</summary>\n    <category term="cs.RO" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2026-07-10T10:23:57Z</published>\n    <arxiv:primary_category term="cs.RO"/>\n    <author>\n      <name>Hariharan Arunachalam</name>\n    </author>\n    <author>\n      <name>Phani Teja Singamaneni</name>\n    </author>\n    <author>\n      <name>Rachid Alami</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2607.08675v1</id>\n    <title>Multi-Sender Bayesian Persuasion with Imperfect Information</title>\n    <updated>2026-07-09T16:37:07Z</updated>\n    <link href="https://arxiv.org/abs/2607.08675v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2607.08675v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>We study a multi-sender Bayesian persuasion problem with one receiver and several strategic senders. The underlying ground state has multiple components, each privately observed by a different sender, while the receiver holds a common prior over the joint state space. Senders simultaneously choose signaling policies, and the receiver takes an action based on the posterior induced by the signals; each is sampled independently from the sender\'s signaling policy. We analyze the game induced by the receiver\'s straightforward policy, which selects a receiver-optimal action at every posterior. In particular, we characterize the senders\' best responses under the straightforward policy and identify conditions on the prior that induce a fully informative equilibrium; i.e., truthfully reporting the ground truth is an equilibrium strategy for every sender. These conditions capture cases in which senders\' incentives are sufficiently aligned to enable full revelation without additional commitment from the receiver. The important contribution of this paper is to analyze games induced by a more general (possibly randomized) class of action policies that the receiver commits to before senders choose their signaling strategies. We show that this commitment power fundamentally changes the problem. In particular, we show that for any prior over the joint state space, the receiver can construct action policies that maximize her payoff while ensuring a fully informative equilibrium.</summary>\n    <category term="cs.GT" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2026-07-09T16:37:07Z</published>\n    <arxiv:primary_category term="cs.GT"/>\n    <author>\n      <name>Andra Siva Sai Teja</name>\n    </author>\n    <author>\n      <name>Ganesh Ghalme</name>\n    </author>\n    <author>\n      <name>Sujit Gujar</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2607.01538v1</id>\n    <title>Can Language Models Actually Retrieve In-Context? Drowning in Documents at Million Token Scale</title>\n    <updated>2026-07-01T23:38:25Z</updated>\n    <link href="https://arxiv.org/abs/2607.01538v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2607.01538v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>Language models (LMs) raise an intriguing alternative to vector-based retrieval: conditioning on an in-context corpus and directly generating a relevant answer. However, prior work has largely focused on proprietary systems or the smaller-scale reranking task, leaving corpus-scale in-context retrieval largely unexplored. In this work, we present the first systematic study of in-context retrieval on two scales practical retrievers demand: million-token corpora and length-generalization far beyond training-time sizes. We first introduce BlockSearch, a 0.6B LM retriever whose architectural and training modifications improve over prior LM baselines and length-generalize up to 10 times beyond its training regime. Nevertheless, retrieval still collapses under more extreme extrapolation. We trace this failure to an attention dilution effect: as the corpus grows, irrelevant documents dominate the softmax denominator, reducing the normalized mass on the gold document even when its pre-softmax score stays high. Motivated by this analysis, we introduce length-aware adjustments to the attention softmax and document-level sparse attention. With these modifications, at the million-token scale, our model matches dense retrieval on widely studied benchmarks (e.g, MS MARCO and NQ), while outperforming the concurrent model MSA despite being 7 times smaller. Furthermore, it significantly outperforms dense retrieval on tasks requiring entirely different notions of similarity, such as LIMIT, achieving a 3 times higher score. Together, our results position in-context retrieval a promising alternative to classical retrieval while emphasizing attention control under extreme context growth as a new challenge.</summary>\n    <category term="cs.CL" scheme="http://arxiv.org/schemas/atom"/>\n    <published>2026-07-01T23:38:25Z</published>\n    <arxiv:primary_category term="cs.CL"/>\n    <author>\n      <name>Siddharth Gollapudi</name>\n    </author>\n    <author>\n      <name>Nilesh Gupta</name>\n    </author>\n    <author>\n      <name>Prasann Singhal</name>\n    </author>\n    <author>\n      <name>Sewon Min</name>\n    </author>\n  </entry>\n  <entry>\n    <id>http://arxiv.org/abs/2606.27491v1</id>\n    <title>SelectAnyTree: A Promptable Instance Segmentation Model for 3D Forest LiDAR Point Clouds</title>\n    <updated>2026-06-25T19:15:36Z</updated>\n    <link href="https://arxiv.org/abs/2606.27491v1" rel="alternate" type="text/html"/>\n    <link href="https://arxiv.org/pdf/2606.27491v1" rel="related" type="application/pdf" title="pdf"/>\n    <summary>Automated instance segmentation of forest LiDAR point clouds is increasingly critical as forest monitoring moves toward scalable, detailed, 3D measurement. Yet, progress is constrained by label scarcity for tree instances; a single hectare can hold millions of points and hundreds of overlapping, complex crowns, making manual annotation from scratch with raw data laborious and error-prone. Annotations are often corrected from automatic pre-segme

In [18]:
client = arxiv.Client()
keyword = "autonomous driving"
search = arxiv.Search(
    query='abs:keyword',        # abs: でアブストラクトのみを対象にする
    max_results=100,                                # 取得件数を100件に固定
    sort_by=arxiv.SortCriterion.SubmittedDate,      # 投稿日でソート
    sort_order=arxiv.SortOrder.Descending,          # 降順 = 新しい順
)

results = list(client.results(search))              # ジェネレータをリスト化して確定
for r in results:
    print(r.published.date(), r.title)

2026-07-21 CR-Refiner: An Object-Centric Optimal Transport Reranker for Edit-Conditioned 3D Scene Retrieval
2026-07-21 DobicVLM: Aligning Chest X-Ray Report Generation with Clinically-Grounded Programmatic Rewards via Group Relative Policy Optimization
2026-07-21 RF-Agent: A Practical Framework for Building Language Agents for RFIC Design
2026-07-20 The natural embedding of the Ree-Tits Octagon
2026-07-20 Pailitao-MMSearch: Building Native E-Commerce Multimodal Search Foundation
2026-07-20 SALT: Salience-Aware Lexical Trie for Long-Context Compression
2026-07-19 Multi-Level Privacy-Preserving Dementia Detection from Speech via Targeted Adversarial Obfuscation and Representation Learning
2026-07-18 Beyond Fixed Depths and Widths: Optimizing Textual Decoding Tries in LLM-based Generative Recommendation
2026-07-17 A Situational Speech Synthesizer for Yoruba: System Design, Phonological Rule Architecture, and Orthographic Extensions for Contour
2026-07-17 When Not to Automate: A Formal Protocol for Human Preservation in AI-Optimized Organizations
2026-07-17 Neuro-Symbolic AI for LEED compliance: Document-Centric Benchmarking, Deterministic Numeric Checking, and When Multimodal Hurts
2026-07-16 When Words Are Safe But Actions Kill: Probing Physical Danger Beyond Text Safety in Hidden-State Risk Space
2026-07-16 Towards realistic large random models of labeled transition systems and their 0-1 laws
2026-07-16 AI vs Human Expert Reasoning: Assessing Agreements in Building Typology Predictions based on Street View Imagery
2026-07-15 MamaBench: Benchmarking LLM Robustness in Maternal and Child Health Diagnosis through Counterfactual Clinical Perturbation
2026-07-15 LIGO-PINN: Learned Initialization via Gated Optimization to Alleviate Convergence Failures in Physics Informed Neural Networks
2026-07-15 Persona Migration and Expectation Recalibration in Generative AI Adoption: A Longitudinal Study at a State Department of Transportation
2026-07-15 Measuring What the Crawler Sees: Discovery Curves, Core Persistence, and Shell Dynamics in Longitudinal Web Crawls
2026-07-13 LaGuadia: Language-Guided Adaptive Distillation from Pathology Foundation Models
2026-07-12 Quantifying the Sources of Instability in LLM-Based Stance Analysis of Public Discourse
2026-07-11 GRASP: GRanularity-Aware Search Policy for Agentic RAG
2026-07-10 FlashTrie: A GPU-Accelerated Constrained Beam Search for Generative Retrieval
2026-07-10 Multimodal Reward Hacking in Reinforcement Learning
2026-07-10 Letting the Data Speak: Extracting Keywords from Crowdsourced Collections with AI
2026-07-10 Beyond Topicality: A Conceptual Analysis of Societal Relevance and Its Application to Search Results and AI Responses
2026-07-10 Evaluating Semantic and Quality-Aware Retrieval for Source Code Repositories
2026-07-09 Applying JEPA-Style Predictive Learning to JA4-Derived Network Fingerprints
2026-07-09 Modeling Stakeholders and Lifecycle Requirements of Marine Hydrokinetic Energy Systems
2026-07-07 Domain-Driven Design in Practice: A Large-Scale Empirical Characterisation of the Open-Source Ecosystem
2026-07-07 Finding H. pylori in the Fine Print: Evidence-Linked Multi-Agent Case Finding from Gastric Biopsy Reports
2026-07-07 InfluMatch: Frontier-Quality KOL Search at 4B-Model Cost
2026-07-06 PatchOptic for Shared-State LLM Workflows with Projected Views and Verified Structured Updates
2026-07-06 Your Agent's Memories Are Not Its Own: Forged Reasoning Attacks on LLM Agent Memory and Defenses
2026-07-05 The New Shape of Search: How Conversational AI Recomposes Information Seeking
2026-07-04 Enhancement of E-commerce Sponsored Search Relevancy with LLM
2026-07-04 Next-Gen Sponsored Search: Crafting the Perfect Query with Inventory-Aware RAG (InvAwr-RAG) Based GenAI
2026-07-04 Content Hidden Behind Execution: Analyzing Public Scratch Projects at Runtime
2026-07-03 Autonomous UAV Route Planning for Coverage Maximization in Environmental Monitoring: A Systematic Literature Review
2026-07-03 Lacuna Inc. at SemEval-2026 Task 4: Structurally Gated State-Space Models for Disentangling Narrative Similarity
2026-07-03 Improving Access to Historical Archives with Real-time RAG-based Systems
2026-07-02 Pmeta-TLA: Backdoor Attacks for Speech Classification Models via Meta-Learning with Timbre Leakage Attack
2026-07-01 Agent4cs: A Multi-agent System for Code Summarization in Large Hierarchical Codebases
2026-07-01 GPUAlert: A Zero-Instrumentation Process-Boundary Monitor for Diagnosing GPU Training-Job Failures
2026-07-01 Multi-Turn Agentic Scientific Literature Search via Workflow Induction
2026-07-01 Open Science in Astrophysics: Citation Benefits of Open Code, Open Data, and Open Access
2026-06-30 Building a Multimodal Dataset of Academic Paper for Keyword Extraction
2026-06-29 PromptGNN-sim: Deep Fusion and Alignment of GNN and LLMs for Text-Attributed Graph Learning
2026-06-28 Manufactured Confidence: How Memory Consolidation Turns Hearsay into Confident Facts
2026-06-26 Context-Aware Explanations for Spatialized Document Layouts
2026-06-26 An LLM-Powered Semantic Alignment Framework for Journal Recommendation
2026-06-25 Floor Raiser or Ceiling Limiter? Differential Storytelling Outcomes with a Child-Centric GenAI System Across Individual Differences
2026-06-25 How Much Static Structure Do Code Agents Need? A Study of Deterministic Anchoring
2026-06-25 Context-Aware Synthesis of Optimization Pipelines for Warehouse Optimization
2026-06-25 A Shared IPTC Topic Space for Cross-Source Topic Modelling
2026-06-24 When Certainty Is an Artifact: Keyword Lexicon Blindness and the (Mis)Measurement of Rhetorical Stance
2026-06-24 Weave of Formal Thought
2026-06-24 Tracing Target Answers in Poisoned Retrieval Corpora via Token Influence Attribution
2026-06-24 MedGuards: Multi-Agent System for Reliable Medical Error Detection and Correction
2026-06-24 On the error bounds of the Gauss-type quadrature formulae associated with spaces of parabolic and cubic spline functions with double equidistant knots
2026-06-23 Grading the Grader: Lessons from Evaluating an Agentic Data Analysis System
2026-06-23 Inside Crypter-as-a-Service: An Ecosystem Analysis of the exploit.in Underground Forum Research Talks
2026-06-23 Dialogue to Discovery: Attribute-Aware Preference Elicitation for Conversational Product Search Assistants
2026-06-22 Domain-Driven Design in Practice: A Mining Study of Maintenance and Evolution in Open-Source Repositories
2026-06-22 LightSTAR: Efficient Visual Document Retrieval via Lightweight Selection with Vision-Adaptive Refinement
2026-06-22 Analysis of quantum-related courses and textbooks for potential integration of quantum sensing
2026-06-22 Detecting Malicious Agent Skills in the Wild using Attention
2026-06-20 Holonomies and Boundary Symmetries in the Discrete Warped Chern-Simons Gravity
2026-06-20 Toward Open-Set Speaker Attribute Prediction with Keyword-Appended LLM Embeddings
2026-06-19 TACO: Task-Aware Column Description Generation Using LLMs
2026-06-19 Beyond Classification Accuracy: An Exploration-Range Evaluation of Adaptive Crawling for Fake Shopping Sites
2026-06-19 A Validation-Gated Mechanistic Account of Suicidality Detection in LLMs
2026-06-18 Personalized Keyword Spotting for User-Defined Keywords Leveraging Text-Independent Speaker Verification
2026-06-18 Repository-Level Solidity Code Generation with Large Language Models: From Prompting to Fine-Tuning
2026-06-18 Clusters are All You Need: Pre-Training the Tsetlin Machine with Semantic Clusters from Language Models for Interpretability
2026-06-17 XmoPipe: A Pipeline for Large-Scale In-the-Wild Human Motion Dataset Construction
2026-06-16 Embedded Machine Learning for Microcontroller-Class Edge Devices: Data, Feature, Evaluation, and Deployment Pipelines
2026-06-16 HistoRAG: Embedding Historical Methodology in Retrieval-Augmented Generation Through Critical Technical Practice
2026-06-16 Learning task-specific subspaces via interventional post-training of speech foundation models
2026-06-16 TopVenues: A Reproducible Corpus and Tooling Substrate for Cybersecurity Literature Reviews
2026-06-16 Predictive Analytics in E-Commerce for CustomerBehavior Forecasting using hybrid Ret-DNN withXGBoost Model
2026-06-16 Understanding LLMs in Title-Abstract Screening: From Disagreements to Recommendations
2026-06-15 Canonical regularization of the stationary Coulomb problem and an Aufbau-like spectral ordering
2026-06-15 From Parasocial Scripts to Dyadic Persistence in Autonomous AI-Agent Communities
2026-06-15 Connecting Speech to Words through Images
2026-06-15 Rapid Poison: Practical Poisoning Attacks Against the Rapid Response Framework
2026-06-15 Invisible Manipulation Channels in AI-Assisted Financial Advisory: Implications for Market Integrity and Regulatory Design
2026-06-15 Stabilizing Short Duration Speaker Verification through Neural Re-scoring with Hybrid Enrollment
2026-06-14 Intelligent Multimodal Retrieval and Reasoning for Geospatial Knowledge Discovery on the I-GUIDE Platform
2026-06-12 A Computational Audit of Demographic Association Encoding in ClinicalBERT Language Predictions
2026-06-11 The Tone of Awareness: Topic, Sentiment, and Toxicity Maps During Mental Health Month on TikTok
2026-06-11 OneRetrieval: Unifying Multi-Branch E-commerce Retrieval with an Editable Generative Model
2026-06-11 Brick: Spatial Capability Routing for the Mixture-of-Models (MoM) Paradigm
2026-06-10 The Brain That Goes Quiet: Serving a Large Model's Knowledge at 131 Tokens per Second on an 8 GB Laptop by Removing the Large Model from the Runtime Path
2026-06-10 Attention by Synchronization in Coupled Oscillator Networks
2026-06-10 A Lightweight Multi-Agent Framework for Automated Concrete Barrier Design
2026-06-09 Auditing Inference-Time Defense Evaluation for Multimodal Large Language Models
2026-06-09 Towards Deep Contextual Reasoning from Broad Descriptions for ASR with Speech-LLM via Metadata-Driven Reasoning Chains
2026-06-09 Massive Open-Vocabulary Keyword Spotting
2026-06-09 KFC-KWS: Keyframe Fusion with CTC for User-Defined Keyword Spotting
2026-06-08 BENI Global 10: A Multilingual Economic Narrative Corpus for the Global South

In [22]:
def lookup_openalex(title, retries=3):
    safe_title = title.replace(",", " ").replace(":", " ")  # filter分割の防止
    params = {"filter": f"title.search:{safe_title}", "per_page": 1}
    for attempt in range(retries):
        try:
            r = requests.get("https://api.openalex.org/works",
                             params=params, timeout=30)
        except requests.exceptions.RequestException:
            time.sleep(2 ** attempt); continue
        if r.status_code == 429:            # 秒間レートのみ再送で対処
            time.sleep(2 ** attempt); continue
        if r.status_code != 200:
            return None
        results = r.json().get("results", [])
        if not results:
            return None
        w = results[0]
        return {
            "matched_title": w.get("title"),
            "language": w.get("language"),
            "countries": [i["country_code"]
                          for a in w.get("authorships", [])
                          for i in a.get("institutions", [])
                          if i.get("country_code")],
            "doi": w.get("doi"),
        }
    return "RATE_LIMITED"

rows = []
for r in results:
    rows.append({"arxiv_title": r.title, "openalex": lookup_openalex(r.title)})
    time.sleep(0.15)

In [26]:
rows = []

In [27]:
i=1
for r in results:
    res = lookup_openalex(r.title)
    row = {"arxiv_title": r.title}          # arxiv側の情報

    if isinstance(res, dict):               # 正常取得（辞書）のときだけ展開
        row.update(res)                     # language, countries, doi, matched_title を平坦化
    else:
        row["openalex_status"] = res        # None や "RATE_LIMITED" は状態として記録

    rows.append(row)
    print(i)
    time.sleep(1)
    i=i+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [29]:
df = pd.DataFrame(rows)
df.head(20)

,arxiv_title,openalex_status,matched_title,language,countries,doi
0,CR-Refiner: An Object-Centric Optimal Transpor...,NaN,NaN,NaN,NaN,NaN
1,DobicVLM: Aligning Chest X-Ray Report Generati...,NaN,NaN,NaN,NaN,NaN
2,RF-Agent: A Practical Framework for Building L...,NaN,NaN,NaN,NaN,NaN
3,The natural embedding of the Ree-Tits Octagon,NaN,NaN,NaN,NaN,NaN
4,Pailitao-MMSearch: Building Native E-Commerce ...,NaN,Pailitao-MMSearch: Building Native E-Commerce ...,NaN,[],https://doi.org/10.48550/arxiv.2607.17499
5,SALT: Salience-Aware Lexical Trie for Long-Con...,NaN,SALT: Salience-Aware Lexical Trie for Long-Con...,NaN,[],https://doi.org/10.48550/arxiv.2607.17486
6,Multi-Level Privacy-Preserving Dementia Detect...,NaN,Multi-Level Privacy-Preserving Dementia Detect...,NaN,[],https://doi.org/10.48550/arxiv.2607.17098
7,Beyond Fixed Depths and Widths: Optimizing Tex...,NaN,Beyond Fixed Depths and Widths: Optimizing Tex...,NaN,[],https://doi.org/10.48550/arxiv.2607.16633
8,A Situational Speech Synthesizer for Yoruba: S...,NaN,NaN,NaN,NaN,NaN
9,When Not to Automate: A Formal Protocol for Hu...,NaN,When Not to Automate: A Formal Protocol for Hu...,NaN,[],https://doi.org/10.48550/arxiv.2607.15944
10,Neuro-Symbolic AI for LEED compliance: Documen...,NaN,Neuro-Symbolic AI for LEED compliance: Documen...,NaN,"[US, US]",https://doi.org/10.48550/arxiv.2607.15647
11,When Words Are Safe But Actions Kill: Probing ...,NaN,When Words Are Safe But Actions Kill: Probing ...,NaN,[],https://doi.org/10.48550/arxiv.2607.15218
12,Towards realistic large random models of label...,NaN,Towards realistic large random models of label...,NaN,[],https://doi.org/10.48550/arxiv.2607.15029
13,AI vs Human Expert Reasoning: Assessing Agreem...,NaN,AI vs Human Expert Reasoning: Assessing Agreem...,NaN,[],https://doi.org/10.48550/arxiv.2607.14756
14,MamaBench: Benchmarking LLM Robustness in Mate...,NaN,MamaBench: Benchmarking LLM Robustness in Mate...,NaN,[],NaN
15,LIGO-PINN: Learned Initialization via Gated Op...,NaN,LIGO-PINN: Learned Initialization via Gated Op...,NaN,[],NaN
16,Persona Migration and Expectation Recalibratio...,NaN,Persona Migration and Expectation Recalibratio...,NaN,[],NaN
17,Measuring What the Crawler Sees: Discovery Cur...,NaN,Measuring What the Crawler Sees: Discovery Cur...,NaN,"[US, US]",NaN
18,LaGuadia: Language-Guided Adaptive Distillatio...,NaN,LaGuadia: Language-Guided Adaptive Distillatio...,NaN,[],https://doi.org/10.48550/arxiv.2607.11257
19,Quantifying the Sources of Instability in LLM-...,NaN,Quantifying the Sources of Instability in LLM-...,NaN,[],NaN

In [31]:
import json, requests

title = results[0].title
print(repr(title))                      # カンマ・コロンの有無を確認

r = requests.get("https://api.openalex.org/works",
                 params={"filter": f"title.search:{title}", "per_page": 1})
print(r.status_code)
print(r.text[:500])

'CR-Refiner: An Object-Centric Optimal Transport Reranker for Edit-Conditioned 3D Scene Retrieval'
429
{"error":"Rate limit exceeded","message":"Insufficient budget. This request costs $0.001 but you only have $0 remaining. Resets at midnight UTC. Need more? Add funds at https://openalex.org/pricing","retryAfter":71985,"costUsd":0.001,"dailyRemainingUsd":0,"prepaidRemainingUsd":0,"creditsRequired":10,"creditsRemaining":0,"onetimeCreditsRemaining":0}

In [4]:
from dotenv import load_dotenv
import os

In [16]:
load_dotenv()
OPENALEX_KEY = os.environ["OPENALEX_KEY"]

In [42]:
import requests

r = requests.get("https://api.openalex.org/works", params={
    "filter": "from_publication_date:2026-04-01,type:preprint",
    "group_by": "authorships.institutions.country_code",
    "per_page": 200,                 # 国数が多いので上限まで取る
    "api_key": OPENALEX_KEY,
}, timeout=30)
r.raise_for_status()

groups = r.json()["group_by"]
total = sum(g["count"] for g in groups)
for g in groups[:15]:
    print(f'{g["key"]:>10} {g["key_display_name"]:<20} {g["count"]:>8} ({g["count"]/total:.1%})')

https://openalex.org/countries/US United States           45609 (25.8%)
https://openalex.org/countries/CN China                   16015 (9.0%)
https://openalex.org/countries/GB United Kingdom          13303 (7.5%)
https://openalex.org/countries/DE Germany                  7479 (4.2%)
https://openalex.org/countries/IN India                    7104 (4.0%)
https://openalex.org/countries/FR France                   5300 (3.0%)
https://openalex.org/countries/JP Japan                    5237 (3.0%)
https://openalex.org/countries/CA Canada                   4486 (2.5%)
https://openalex.org/countries/CH Switzerland              3824 (2.2%)
https://openalex.org/countries/IT Italy                    3348 (1.9%)
https://openalex.org/countries/ES Spain                    3299 (1.9%)
https://openalex.org/countries/BR Brazil                   3265 (1.8%)
https://openalex.org/countries/AU Australia                3191 (1.8%)
https://openalex.org/countries/NL Netherlands              2762 (1.6%)
https://openalex.org/countries/KR South Korea              2260 (1.3%)

In [6]:
import requests
keyword = "autonomous driving"

KEYWORD = keyword     # ここだけ差し替える
SINCE   = "2026-04-01"
NON_CN  = "us|gb|de|in|fr|jp|ca|ch|it|es|br|au|nl|kr|se|il|sg|dk|be|at|pl|fi|no"
ARXIV_SRC = "S4306400194"                            # /sources?search=arxiv で確認したID

r = requests.get("https://api.openalex.org/works", params={
    "filter": ",".join([
        f"abstract.search:{KEYWORD}",
        f"primary_location.source.id:{ARXIV_SRC}",
        "institutions.country_code:!cn",
        f"institutions.country_code:{NON_CN}",
        f"from_publication_date:{SINCE}",
    ]),
    "sort": "publication_date:desc",
    "per_page": 25,
    "api_key": OPENALEX_KEY,
}, timeout=30)
r.raise_for_status()

In [46]:
rows = []
for w in r.json()["results"]:
    countries = sorted({c for a in w["authorships"] for c in a.get("countries", [])})
    rows.append({
        "openalex_id": w["id"],
        "title": w["title"],
        "doi": w.get("doi"),
        "publication_date": w.get("publication_date"),
        "language": w.get("language"),
        "countries": countries,
        "institutions": sorted({i["display_name"] for a in w["authorships"]
                                for i in a.get("institutions", [])}),
    })

In [7]:
works = r.json()["results"]
n_ref = [len(w.get("referenced_works", [])) for w in works]
print(sum(x > 0 for x in n_ref), "/", len(works), "件が参照あり、合計", sum(n_ref), "本")

0 / 25 件が参照あり、合計 0 本

In [9]:
import time, requests

def s2_get(path, params, retries=6):
    for a in range(retries):
        r = requests.get(f"https://api.semanticscholar.org/graph/v1/{path}",
                         params=params, timeout=30)
        if r.status_code == 429:
            wait = 5 * (a + 1)          # 共有プールは混みやすいので長めに待つ
            print(f"429, {wait}s待機")
            time.sleep(wait)
            continue
        return r
    return None

r = s2_get("paper/arXiv:2607.10565", {"fields": "title,referenceCount"})
print(r.status_code, r.text[:300])

429, 5s待機
200 {"paperId": "d1e03ed42fff32b34beb8d49aa92dedb6c71ece4", "title": "BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning", "referenceCount": 28}

In [10]:
import re, time, requests
import pandas as pd

ref_cache = {}          # arXiv ID → 参照リスト。再実行時の再取得を防ぐ

def arxiv_id(w):
    m = re.search(r"arxiv\.(\d{4}\.\d{4,5})", w.get("doi") or "", re.I)
    if m:
        return m.group(1)
    url = (w.get("primary_location") or {}).get("landing_page_url") or ""
    m = re.search(r"arxiv\.org/abs/([^v\s?]+)", url, re.I)
    return m.group(1) if m else None

def fetch_refs(aid):
    if aid in ref_cache:
        return ref_cache[aid]
    r = s2_get(f"paper/arXiv:{aid}/references",
               {"fields": "title,year,externalIds", "limit": 500})
    if r is None:
        return None                      # リトライを使い切った
    if r.status_code == 404:
        ref_cache[aid] = []              # 未収録も記録して再取得しない
        return []
    r.raise_for_status()
    ref_cache[aid] = r.json().get("data", [])
    return ref_cache[aid]

rows = []
for i, w in enumerate(works, 1):
    aid = arxiv_id(w)
    refs = fetch_refs(aid) if aid else None
    print(f"{i}/{len(works)} {aid} refs={len(refs) if refs is not None else 'FAIL'}")

    if not refs:
        rows.append({"citing_arxiv_id": aid, "citing_title": w["title"],
                     "status": "no_refs"})
        continue
    for ref in refs:
        cp = ref.get("citedPaper") or {}
        rows.append({
            "citing_arxiv_id": aid,
            "citing_title": w["title"],
            "cited_title": cp.get("title"),
            "cited_year": cp.get("year"),
            "cited_doi": (cp.get("externalIds") or {}).get("DOI"),
            "cited_arxiv": (cp.get("externalIds") or {}).get("ArXiv"),
            "status": "ok",
        })
    time.sleep(2)                        # 429を減らすための予防的な間隔

df = pd.DataFrame(rows)

1/25 2607.10565 refs=28
429, 5s待機
429, 10s待機
429, 15s待機
2/25 2607.08745 refs=12
429, 5s待機
3/25 2607.06957 refs=40
429, 5s待機
4/25 2607.04670 refs=26
429, 5s待機
429, 10s待機
429, 15s待機
429, 20s待機
429, 25s待機
429, 30s待機
5/25 2607.04953 refs=FAIL
6/25 2607.02841 refs=68
429, 5s待機
7/25 2607.03177 refs=47
429, 5s待機
429, 10s待機
8/25 2607.00710 refs=48
429, 5s待機
9/25 2607.01382 refs=17
10/25 2606.31160 refs=31
11/25 2606.31875 refs=55
429, 5s待機
12/25 2606.31096 refs=45
13/25 2606.31172 refs=65
14/25 2606.30807 refs=61
15/25 2606.30896 refs=25
16/25 2606.29097 refs=69
17/25 2606.27644 refs=31
18/25 2606.27656 refs=24
19/25 2606.26456 refs=42
20/25 2606.24096 refs=32
21/25 2606.21344 refs=17
22/25 2606.20376 refs=47
23/25 2606.20687 refs=26
24/25 2606.15139 refs=11
429, 5s待機
25/25 2606.14010 refs=19

In [19]:
pd.set_option('display.max_colwidth', None)

In [20]:
df.head(10)

,citing_arxiv_id,citing_title,cited_title,cited_year,cited_doi,cited_arxiv,status
0,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,World4Drive: End-to-End Autonomous Driving via Intention-Aware Physical Latent World Model,2025.0,10.1109/ICCV51701.2025.02659,2507.00603,ok
1,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,Bridging Past and Future: End-to-End Autonomous Driving with Historical Prediction and Planning,2025.0,10.1109/CVPR52734.2025.00643,2503.14182,ok
2,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,Don’t Shake the Wheel: Momentum-Aware Planning in End-to-End Autonomous Driving,2025.0,10.1109/CVPR52734.2025.02089,2503.03125,ok
3,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,Bench2Drive: Towards Multi-Ability Benchmarking of Closed-Loop End-To-End Autonomous Driving,2024.0,10.48550/arXiv.2406.03877,2406.03877,ok
4,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,End-to-End Autonomous Driving through V2X Cooperation,2024.0,10.48550/arXiv.2404.00717,2404.00717,ok
5,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,On the Road to Portability: Compressing End-to-End Motion Planner for Autonomous Driving,2024.0,10.1109/CVPR52733.2024.01430,2403.01238,ok
6,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,LMDrive: Closed-Loop End-to-End Driving with Large Language Models,2023.0,10.1109/CVPR52733.2024.01432,2312.07488,ok
7,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,Is Ego Status All You Need for Open-Loop End-to-End Autonomous Driving?,2023.0,10.1109/CVPR52733.2024.01408,2312.03031,ok
8,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,Motion Planning for Autonomous Driving: The State of the Art and Future Perspectives,2023.0,10.1109/TIV.2023.3274536,2303.09824,ok
9,2607.10565,BucketKD: A Safety-Aware Bucket-Based Knowledge Distillation Framework for End-to-End Motion Planning,Cross-Modality Knowledge Distillation Network for Monocular 3D Object Detection,2022.0,10.1007/978-3-031-20080-9_6,2211.07171,ok

In [14]:
COLS = ["matched_title", "language", "countries"]

In [17]:
def lookup_openalex(title, api_key=OPENALEX_KEY):
    r = requests.get("https://api.openalex.org/works",
                     params={"filter": f"title.search:{title}",
                             "per_page": 1,
                             "api_key": api_key},      # mailtoの代わりにキーを渡す
                     timeout=30)
    if r.status_code == 429:
        return "RATE_LIMITED"
    if r.status_code != 200:
        return None
    results = r.json().get("results", [])
    if not results:
        return None
    w = results[0]
    return {
        "matched_title": w.get("title"),
        "language": w.get("language"),
        "countries": [i["country_code"] for a in w.get("authorships", [])
                      for i in a.get("institutions", []) if i.get("country_code")],
        "doi": w.get("doi"),
    }

In [21]:
lookup_openalex("World4Drive: End-to-End Autonomous Driving via Intention-Aware Physical Latent World Model", api_key=OPENALEX_KEY)

{'matched_title': 'World4Drive: End-to-End Autonomous Driving via Intention-Aware Physical Latent World Model',
 'language': 'en',
 'countries': ['SG',
  'CN',
  'CN',
  'CN',
  'CN',
  'SG',
  'CN',
  'CN',
  'CN',
  'CN',
  'CN'],
 'doi': 'https://doi.org/10.1109/iccv51701.2025.02659'}

In [18]:
df['citing_title'].unique

<bound method Series.unique of 0      BucketKD: A Safety-Aware Bucket-Based Knowledg...
1      BucketKD: A Safety-Aware Bucket-Based Knowledg...
2      BucketKD: A Safety-Aware Bucket-Based Knowledg...
3      BucketKD: A Safety-Aware Bucket-Based Knowledg...
4      BucketKD: A Safety-Aware Bucket-Based Knowledg...
                             ...
882    RT-VLA: Real-Time Vision-Language-Action Model...
883    RT-VLA: Real-Time Vision-Language-Action Model...
884    RT-VLA: Real-Time Vision-Language-Action Model...
885    RT-VLA: Real-Time Vision-Language-Action Model...
886    RT-VLA: Real-Time Vision-Language-Action Model...
Name: citing_title, Length: 887, dtype: str>

In [ ]:
i=1
for work in works:
    df_temp = df[df['cited_title'].str.contains(work, regex=False, na=False)].copy()
    if df_temp.empty:
        continue
        
    result=lookup_openalex(work, api_key=OPENALEX_KEY)

    matched_title = result['matched_title']
    language = result['language']
    countries = result['countries']
    
    df_temp[COLS] = pd.DataFrame(matched_title, language, countries)

    df_temp.to_csv(f'{i}.csv', index=False)         # 論文ごとにCSV出力
    print(i)
    i += 1

In [22]:
cited = df[df.status == "ok"]
print("行数", len(cited))
print("DOIあり", cited.cited_doi.notna().sum())
print("ユニークDOI", cited.cited_doi.nunique())
print("必要コール数", -(-cited.cited_doi.nunique() // 100))

行数 886
DOIあり 680
ユニークDOI 619
必要コール数 7

In [23]:

cited = df[df.status == "ok"].copy()

def norm_doi(d):
    if not d:
        return None
    return str(d).lower().replace("https://doi.org/", "").strip()

# 1. 被引用論文のメタデータを一括取得（ループの外で1回だけ）
dois = sorted({norm_doi(d) for d in cited.cited_doi.dropna()})
print("ユニークDOI", len(dois), "→ 必要コール数", -(-len(dois) // 100))

meta = {}
for i in range(0, len(dois), 100):
    batch = dois[i:i + 100]
    r = requests.get("https://api.openalex.org/works", params={
        "filter": "doi:" + "|".join(f"https://doi.org/{d}" for d in batch),
        "per_page": 100,
        "api_key": OPENALEX_KEY,
    }, timeout=60)
    if r.status_code != 200:                  # 異常時は中断して枠を守る
        print(r.status_code, r.text[:300])
        break
    for w in r.json()["results"]:
        meta[norm_doi(w.get("doi"))] = {
            "matched_title": w.get("title"),
            "language": w.get("language"),
            "countries": ",".join(sorted({c for a in w.get("authorships", [])
                                            for c in a.get("countries", [])})),
        }
    time.sleep(0.3)

# 2. 全行に付与する
key = cited.cited_doi.map(norm_doi)
for col in ["matched_title", "language", "countries"]:
    cited[col] = key.map(lambda k: (meta.get(k) or {}).get(col))

# 3. 引用元ごとに1ファイル書き出す
for i, (aid, g) in enumerate(cited.groupby("citing_arxiv_id"), 1):
    g.to_csv(f"{aid}.csv", index=False, encoding="utf-8-sig")
    print(i, aid, len(g), "行 / 国判明", (g.countries.fillna("") != "").sum())

ユニークDOI 619 → 必要コール数 7
1 2606.14010 19 行 / 国判明 4
2 2606.15139 11 行 / 国判明 4
3 2606.20376 47 行 / 国判明 10
4 2606.20687 26 行 / 国判明 20
5 2606.21344 17 行 / 国判明 13
6 2606.24096 32 行 / 国判明 27
7 2606.26456 42 行 / 国判明 34
8 2606.27644 31 行 / 国判明 21
9 2606.27656 24 行 / 国判明 18
10 2606.29097 69 行 / 国判明 31
11 2606.30807 61 行 / 国判明 21
12 2606.30896 25 行 / 国判明 13
13 2606.31096 45 行 / 国判明 29
14 2606.31160 31 行 / 国判明 3
15 2606.31172 65 行 / 国判明 46
16 2606.31875 55 行 / 国判明 33
17 2607.00710 48 行 / 国判明 18
18 2607.01382 17 行 / 国判明 9
19 2607.02841 68 行 / 国判明 22
20 2607.03177 47 行 / 国判明 27
21 2607.04670 26 行 / 国判明 13
22 2607.06957 40 行 / 国判明 18
23 2607.08745 12 行 / 国判明 11
24 2607.10565 28 行 / 国判明 19

In [24]:
cited.to_csv("cited_all.csv", index=False, encoding="utf-8-sig")
print(len(cited))

886