In [1]:
#This is also program to get reference information from CSAE

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
from lxml import etree

In [3]:
import time

In [4]:
from urllib.parse import urljoin

In [6]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 
}

In [10]:
url="https://www.qichegongcheng.com/CN/article/showOldVolumn.do"
resp = requests.get(url, headers=headers)
xpath = '//a[@class="J_WenZhang"]'
tree = etree.HTML(resp.text)
elements = tree.xpath(xpath)
elements
urls = []
for elm in elements:
    link = elm.get('href')
    urls.append(link)

In [11]:
urls

['../volumn/volumn_105.shtml',
 '../volumn/volumn_104.shtml',
 '../volumn/volumn_103.shtml',
 '../volumn/volumn_102.shtml',
 '../volumn/volumn_105.shtml',
 '../volumn/volumn_104.shtml',
 '../volumn/volumn_104.shtml',
 '../volumn/volumn_103.shtml',
 '../volumn/volumn_103.shtml',
 '../volumn/volumn_102.shtml',
 '../volumn/volumn_102.shtml',
 '../volumn/volumn_101.shtml',
 '../volumn/volumn_101.shtml',
 '../volumn/volumn_100.shtml',
 '../volumn/volumn_99.shtml',
 '../volumn/volumn_99.shtml',
 '../volumn/volumn_98.shtml',
 '../volumn/volumn_98.shtml',
 '../volumn/volumn_97.shtml',
 '../volumn/volumn_97.shtml',
 '../volumn/volumn_96.shtml',
 '../volumn/volumn_96.shtml',
 '../volumn/volumn_95.shtml',
 '../volumn/volumn_95.shtml',
 '../volumn/volumn_94.shtml',
 '../volumn/volumn_93.shtml',
 '../volumn/volumn_93.shtml',
 '../volumn/volumn_92.shtml',
 '../volumn/volumn_92.shtml',
 '../volumn/volumn_91.shtml',
 '../volumn/volumn_91.shtml',
 '../volumn/volumn_90.shtml',
 '../volumn/volumn_90.shtml',
 '../volumn/volumn_89.shtml',
 '../volumn/volumn_89.shtml',
 '../volumn/volumn_88.shtml',
 '../volumn/volumn_87.shtml',
 '../volumn/volumn_87.shtml',
 '../volumn/volumn_86.shtml',
 '../volumn/volumn_86.shtml',
 '../volumn/volumn_85.shtml',
 '../volumn/volumn_85.shtml',
 '../volumn/volumn_84.shtml',
 '../volumn/volumn_84.shtml',
 '../volumn/volumn_83.shtml',
 '../volumn/volumn_83.shtml',
 '../volumn/volumn_82.shtml',
 '../volumn/volumn_81.shtml',
 '../volumn/volumn_81.shtml',
 '../volumn/volumn_80.shtml',
 '../volumn/volumn_80.shtml',
 '../volumn/volumn_79.shtml',
 '../volumn/volumn_79.shtml',
 '../volumn/volumn_78.shtml',
 '../volumn/volumn_78.shtml',
 '../volumn/volumn_77.shtml',
 '../volumn/volumn_77.shtml',
 '../volumn/volumn_76.shtml',
 '../volumn/volumn_75.shtml',
 '../volumn/volumn_75.shtml',
 '../volumn/volumn_74.shtml',
 '../volumn/volumn_74.shtml',
 '../volumn/volumn_73.shtml',
 '../volumn/volumn_73.shtml',
 '../volumn/volumn_72.shtml',
 '../volumn/volumn_72.shtml',
 '../volumn/volumn_71.shtml',
 '../volumn/volumn_71.shtml',
 '../volumn/volumn_70.shtml',
 '../volumn/volumn_69.shtml',
 '../volumn/volumn_69.shtml',
 '../volumn/volumn_68.shtml',
 '../volumn/volumn_68.shtml',
 '../volumn/volumn_67.shtml',
 '../volumn/volumn_67.shtml',
 '../volumn/volumn_66.shtml',
 '../volumn/volumn_66.shtml',
 '../volumn/volumn_65.shtml',
 '../volumn/volumn_65.shtml',
 '../volumn/volumn_64.shtml',
 '../volumn/volumn_63.shtml',
 '../volumn/volumn_63.shtml',
 '../volumn/volumn_62.shtml',
 '../volumn/volumn_62.shtml',
 '../volumn/volumn_61.shtml',
 '../volumn/volumn_61.shtml',
 '../volumn/volumn_60.shtml',
 '../volumn/volumn_60.shtml',
 '../volumn/volumn_59.shtml',
 '../volumn/volumn_59.shtml',
 '../volumn/volumn_58.shtml',
 '../volumn/volumn_57.shtml',
 '../volumn/volumn_57.shtml',
 '../volumn/volumn_56.shtml',
 '../volumn/volumn_56.shtml',
 '../volumn/volumn_55.shtml',
 '../volumn/volumn_55.shtml',
 '../volumn/volumn_54.shtml',
 '../volumn/volumn_54.shtml',
 '../volumn/volumn_53.shtml',
 '../volumn/volumn_53.shtml',
 '../volumn/volumn_52.shtml',
 '../volumn/volumn_51.shtml',
 '../volumn/volumn_51.shtml',
 '../volumn/volumn_50.shtml',
 '../volumn/volumn_50.shtml',
 '../volumn/volumn_49.shtml',
 '../volumn/volumn_49.shtml',
 '../volumn/volumn_48.shtml',
 '../volumn/volumn_48.shtml',
 '../volumn/volumn_47.shtml',
 '../volumn/volumn_47.shtml',
 '../volumn/volumn_46.shtml',
 '../volumn/volumn_45.shtml',
 '../volumn/volumn_45.shtml',
 '../volumn/volumn_44.shtml',
 '../volumn/volumn_44.shtml',
 '../volumn/volumn_43.shtml',
 '../volumn/volumn_43.shtml',
 '../volumn/volumn_42.shtml',
 '../volumn/volumn_42.shtml',
 '../volumn/volumn_41.shtml',
 '../volumn/volumn_41.shtml',
 '../volumn/volumn_40.shtml',
 '../volumn/volumn_39.shtml',
 '../volumn/volumn_39.shtml',
 '../volumn/volumn_38.shtml',
 '../volumn/volumn_38.shtml',
 '../volumn/volumn_37.shtml',
 '../volumn/volumn_37.shtml',
 '../volumn/volumn_36.shtml',
 '../volumn/volumn_36.shtml',
 '../volumn/volumn_35.shtml',
 '../volumn/volumn_35.shtml',
 '../volumn/volumn_34.shtml',
 '../volumn/volumn_33.shtml',
 '../volumn/volumn_33.shtml',
 '../volumn/volumn_32.shtml',
 '../volumn/volumn_32.shtml',
 '../volumn/volumn_31.shtml',
 '../volumn/volumn_31.shtml',
 '../volumn/volumn_30.shtml',
 '../volumn/volumn_30.shtml',
 '../volumn/volumn_29.shtml',
 '../volumn/volumn_29.shtml',
 '../volumn/volumn_28.shtml',
 '../volumn/volumn_27.shtml',
 '../volumn/volumn_27.shtml',
 '../volumn/volumn_26.shtml',
 '../volumn/volumn_26.shtml',
 '../volumn/volumn_25.shtml',
 '../volumn/volumn_25.shtml',
 '../volumn/volumn_24.shtml',
 '../volumn/volumn_24.shtml',
 '../volumn/volumn_23.shtml',
 '../volumn/volumn_23.shtml',
 '../volumn/volumn_22.shtml',
 '../volumn/volumn_21.shtml',
 '../volumn/volumn_21.shtml',
 '../volumn/volumn_20.shtml',
 '../volumn/volumn_20.shtml',
 '../volumn/volumn_16.shtml',
 '../volumn/volumn_16.shtml',
 '../volumn/volumn_15.shtml',
 '../volumn/volumn_15.shtml',
 '../volumn/volumn_14.shtml',
 '../volumn/volumn_14.shtml',
 '../volumn/volumn_13.shtml',
 '../volumn/volumn_12.shtml',
 '../volumn/volumn_12.shtml',
 '../volumn/volumn_10.shtml',
 '../volumn/volumn_10.shtml',
 '../volumn/volumn_9.shtml',
 '../volumn/volumn_9.shtml',
 '../volumn/volumn_11.shtml',
 '../volumn/volumn_11.shtml',
 '../volumn/volumn_8.shtml',
 '../volumn/volumn_8.shtml',
 '../volumn/volumn_7.shtml',
 '../volumn/volumn_6.shtml',
 '../volumn/volumn_6.shtml',
 '../volumn/volumn_19.shtml',
 '../volumn/volumn_18.shtml',
 '../volumn/volumn_18.shtml',
 '../volumn/volumn_17.shtml',
 '../volumn/volumn_17.shtml',
 '../volumn/volumn_5.shtml',
 '../volumn/volumn_5.shtml',
 '../volumn/volumn_3.shtml',
 '../volumn/volumn_3.shtml',
 '../volumn/volumn_4.shtml',
 '../volumn/volumn_1.shtml',
 '../volumn/volumn_2.shtml',
 '../volumn/volumn_2.shtml']

In [14]:
source_page_url = "https://www.qichegongcheng.com/CN/article/showOldVolumn.do"

In [13]:
len(urls)

194

In [30]:
data_total=[]
for url in unique_urls:
    url = urljoin(source_page_url, url) 
    resp = requests.get(url, headers=headers)
    tree = etree.HTML(resp.text)
    xpath = '//a[@class="txt_biaoti"]'
    elements = tree.xpath(xpath)
    data_everybook=[]
    time.sleep(0.3)
    for elm in elements:        
        print("-----")
        link = elm.get('href')
        title = elm.text
        print(link)
        row = {'link' : link, 'title': title}
        data_total.append(row)

-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.020
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.ep.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.003
-----

In [31]:
data_total

[{'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001',
  'title': '一种改进的加速度阻尼半主动控制策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.002',
  'title': '润滑油灰分对直喷汽油车GPF性能影响的试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.003',
  'title': '基于WLTC和NEDC循环的轻型车氨排放特性研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004',
  'title': '测量模块对柴油机缸体上水孔流量测量的影响研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005',
  'title': '高压共轨系统不同温度下喷油参数修正计算'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006',
  'title': '高速无人驾驶车辆的操控稳定性研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007',
  'title': '无人驾驶机器人机械腿模糊监督控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.008',
  'title': '汽车传动系激励转矩波动估计与扭振性能调校'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.009',
  'title': '汽车底部复杂流场的主动和被动控制减阻方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.010',
  'title': '含概率区间混合不确定性的汽车正面碰撞可靠性优化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.011',
  'title': '离合器最优控制权系数变化对车辆性能的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.012',
  'title': '非线性影响下悬置系统模态分析及解耦度计算方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.013',
  'title': '汽车急加速进气噪声的试验测试与分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014',
  'title': '车用锂离子电池低温特性与加热方法研究进展'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.015',
  'title': '三元锂离子动力电池过充行为特性实验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.016',
  'title': '不同温度下锂电池剩余电量估算的仿真研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.017',
  'title': 'GFRP/铝合金和铝合金/铝合金粘接接头失效对比研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.001',
  'title': '强降雨场景下自适应巡航控制系统的安全控制策略'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.002',
  'title': '无人车全轮蟹行转向稳定性鲁棒控制与试验验证'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.003',
  'title': '跟驰场景中网联混合电动货车速度规划和能量管理协同控制的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.004',
  'title': '不同渗透率下非信控交叉路口混合预约多车协同控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.005',
  'title': '面向混合自动驾驶车流的协同自适应巡航控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.006',
  'title': '基于改进BP神经网络的智能车纵向控制方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007',
  'title': '基于三维锥形栅格的激光点云语义分割方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.008',
  'title': '新型分布式驱动液氢燃料电池重型商用车设计、分析与验证'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.009',
  'title': '均布模组式动力电池包热失控典型模式分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.010',
  'title': '基于大数据的电动汽车用户行为对电池老化影响分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.011',
  'title': '基于PSO的新型双电机多模式驱动系统转矩分配策略优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.012',
  'title': '电机转子铁芯剥离模型建立与径向磁密分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.013',
  'title': '电动客车AMT换挡执行机构状态估计及参数辨识'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.014',
  'title': '基于认知-控制框架的侧风工况下驾驶员横向控制模型研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.015',
  'title': 'HSM标准模型的风噪声源及其特性分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.016',
  'title': '基于道路循环工况的燃料电池空压机瞬态性能试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.017',
  'title': 'CDPF主动再生对SCR性能影响的试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.001',
  'title': '基于特性的商用车整体式车桥及耦合悬架动力学模型研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.002',
  'title': '四轮轮毂驱动车辆横向稳定性的底盘协同控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.003',
  'title': '基于扰动观测器的主动悬架切换控制算法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.004',
  'title': '面向转向制动工况的制动力动态分配策略'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.005',
  'title': '轮毂电机驱动电动汽车4WS和DYC协调控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.006',
  'title': '基于自主漂移的自动驾驶车辆极限工况轨迹规划与控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007',
  'title': '基于模型预测路径积分和输出调节的层级运动控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.008',
  'title': '基于学习型模型预测控制的智能车辆路径跟踪控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.009',
  'title': '多源干扰下的智能车模型预测纵向运动抗干扰控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.010',
  'title': '考虑侧风稳定性的汽车轨迹跟踪自适应时域模型预测控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.011',
  'title': '基于点云反射特性的前方道路附着系数估计方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.012',
  'title': '人机共驾型车道保持鲁棒控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.013',
  'title': '基于图卷积交互网络的车辆轨迹预测方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.014',
  'title': '基于工况识别的纯电动汽车2DCT换挡策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.015',
  'title': '动力电池包局部复式模组热均匀性分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.016',
  'title': '基于多维度多尺度特征的锂离子电池RUL估计方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.017',
  'title': '面向汽车安全的中国体征50'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.018',
  'title': 'AEB工况下驾驶员姿态对损伤风险的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.019',
  'title': '四凸极液冷电磁缓速器数值模拟与实验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.001',
  'title': '无人驾驶汽车局部路径规划算法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.002',
  'title': '机器人驾驶车辆的横向自适应反演切换控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.003',
  'title': '无人驾驶汽车编队雾天主动拯救系统'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.004',
  'title': 'V2X通信中基于椭圆曲线加密算法的身份认证研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.005',
  'title': '智能网联汽车计算平台虚拟化技术研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.006',
  'title': '基于三维激光点云的目标识别与跟踪研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.007',
  'title': '基于背景光照去除和连通区域的车位检测'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.008',
  'title': '驾驶员避撞转向行为的改进K-means聚类与识别'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.009',
  'title': '校准量热法测量锂电池比热容和生热率'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.010',
  'title': '不同滥用条件下车用锂电池安全性实验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.011',
  'title': '基于遗传算法的机液传动系统参数匹配研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.012',
  'title': '基于磁场重构法的轴向磁通轮毂电机建模研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.013',
  'title': '自供能磁流变阻尼器电参数影响特性及隔振性能'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.014',
  'title': '燃油近嘴区初始射流破碎及影响因素试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.015',
  'title': '基于4种典型神经网络识别路面不平度的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.016',
  'title': '基于特征评价的发动机寿命预测方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.017',
  'title': '某型SUV空空中冷器内部流动换热研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.018',
  'title': '汽车后视镜气动噪声优化研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.019',
  'title': '关联用户的汽车试验场耐久性评价路况循环确定方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.020',
  'title': '基于FAHP-FQFD方法的汽车产品性能量化评价的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.001',
  'title': '基于滑模自抗扰的电制动系统动态负载模拟'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.002',
  'title': '柴油机两级涡轮阀可调增压系统变海拔控制策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.003',
  'title': '柴油机典型工况的电控喷油器多次喷射分配'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.004',
  'title': '喷嘴内燃油空化及影响因素的实验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.005',
  'title': '车用质子交换膜燃料电池空气供应系统自适应解耦控制方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.006',
  'title': '基于有限元法及遗传算法的推力杆球铰多目标优化方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.007',
  'title': '基于非线性模型预测控制的车辆纵向队列协调控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.008',
  'title': '极限工况下主动前轮转向汽车稳定性控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.009',
  'title': '电动轮汽车车速与道路坡度估计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.010',
  'title': '考虑预碰撞时间的自动紧急制动系统分层控制策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.011',
  'title': '商用车气压ABS性能综合测试系统设计与试验'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.012',
  'title': '考虑稳健性的汽车结构耐撞性优化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.013',
  'title': '儿童安全座椅中填充吸能泡沫对头部的保护效果分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.014',
  'title': '基于流场和温度场的轿车乘员舱热舒适性分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.015',
  'title': '汽车驱动桥NVH性能分析与优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.016',
  'title': '网联车辆并线预测与巡航控制的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.017',
  'title': '碳纤维增强复合材料电池箱轻量化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.018',
  'title': '扭转梁悬架碳纤维复合材料横梁结构优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.019',
  'title': '智能车经济性起步车速规划研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.001',
  'title': '面向CAFC 法规的汽车企业轻量化策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.002',
  'title': '增程式电动客车能量管理策略优化的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.003',
  'title': '复合功率分流混合动力汽车能量管理策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.004',
  'title': '轻型柴油机起动过程瞬态喷油量控制策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.005',
  'title': '底部结构对轿车侧风气动特性的影响分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.006',
  'title': '基于分级加权模型的车身色彩感性评价方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.007',
  'title': '一种分析事故再现仿真结果不确定性的多响应面均匀设计法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.008',
  'title': '汽车防撞雷达中频信号处理系统的优化方案'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.009',
  'title': '集成式电子液压制动系统液压力变结构控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.010',
  'title': '电-液制动系统高速开关电磁阀的建模与动态特性仿真'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.011',
  'title': '混合动力客车自适应巡航控制研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.012',
  'title': '非匀质车辆队列的分布式控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.013',
  'title': '基于LQR 变传动比控制的4WIS 电动车转向控制仿真研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.014',
  'title': '基于动力学模型的三轴汽车仿真系统研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.015',
  'title': '载货车轮胎近场噪声方向性的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.016',
  'title': '一种适用于发动机振动信号的时频分析方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.017',
  'title': '多风扇冷却模块节能控制的试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.018',
  'title': '缸盖高热密度区纳米流雾化冲击冷却的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.019',
  'title': '汽车车身异种金属板件磁脉冲焊接工艺研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.001',
  'title': '基于强化学习的自动驾驶决策研究综述'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.002',
  'title': '基于检测的高效自动驾驶实例分割方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.003',
  'title': '基于分层式控制的混合动力汽车生态驾驶研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.004',
  'title': '基于最优方法的碰后辅助驾驶控制策略'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.005',
  'title': '双重下采样增强的点云改进配准算法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.006',
  'title': '混动履带式无人平台轨迹跟踪控制研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.007',
  'title': '基于轨迹预测的智能汽车行驶风险评估方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.008',
  'title': '考虑配电网负荷的电动汽车分布式充电控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.009',
  'title': '基于遗传算法的车用轴向磁通电机温度模型优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.010',
  'title': '汽车永磁同步电机切换函数式混合控制策略'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.011',
  'title': '考虑环境温度影响的超级电容SOC加权融合估计方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.012',
  'title': '基于相空间三维动态稳定域的重型车辆稳定性控制策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.ep.003',
  'title': '基于扭转刚度的电池包与车身集成设计研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.014',
  'title': '气门重叠角对GDI发动机性能和微粒排放的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.015',
  'title': '基于耐久老化车辆的实际道路行驶NO '},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.016',
  'title': '柴油机缸内两相流卷吸效应对燃烧模式的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.017',
  'title': '某SUV后视镜降噪设计与风洞试验验证'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.018',
  'title': '混动车型平衡轴齿轮敲击噪声优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.019',
  'title': '基于关联规则挖掘的车辆故障码分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.001',
  'title': '面向碳中和的新能源汽车与车网互动技术展望'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.002',
  'title': '锂离子电池机械滥用失效机理及仿真模型研究进展'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.003',
  'title': '新型动力电池热管理系统设计及性能研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.004',
  'title': '不同充电倍率下锂离子电池组冷却系统结构设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.005',
  'title': '基于电化学热耦合模型的锂离子电池快充控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.006',
  'title': '基于FFRLS-EKF联合算法的锂离子电池荷电状态估计方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.007',
  'title': '融合工况识别的增程式电动汽车模糊能量管理策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.008',
  'title': '计及出租车充电行为的微电网能量管理研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.009',
  'title': '面向冬奥示范的新一代燃料电池系统技术突破'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.010',
  'title': '面向耐久性提升的车用燃料电池系统电控技术研究进展'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.011',
  'title': '基于WO'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.012',
  'title': '碱性水电解制氢系统建模综述及展望'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.013',
  'title': '电动汽车驱动系统直流母线稳定性分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.014',
  'title': '新能源汽车高压线束在机械外载下失效试验及仿真研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.015',
  'title': '纯电动汽车低压电气系统效率研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.016',
  'title': '智能网联电动汽车经济性巡航速度规划'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.017',
  'title': '电动汽车动力电池研究展望：智能电池、智能管理与智慧能源'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.018',
  'title': 'SiC功率模块封装技术及展望'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.001',
  'title': '面向自动驾驶的大模型对齐技术：综述'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.002',
  'title': '面向智能驾驶测试的可变跟驰特性交通车建模方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.003',
  'title': '面向自动驾驶测试的交互场景策略建模与仿真'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.004',
  'title': '基于多信息融合网络的行人轨迹预测方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.005',
  'title': '基于设计运行条件的实际道路测试场景复杂度计算模型'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.006',
  'title': '交叉口车辆行为感知在线半监督混合方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.007',
  'title': '基于动态风险评估的车辆辅助驾驶行为决策'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.008',
  'title': '地下矿道无人车可行驶区域检测算法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.009',
  'title': '融合语义信息与物体级几何特征的实时动态激光SLAM算法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.010',
  'title': '基于证据深度学习的CAN网络入侵检测框架'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.011',
  'title': '考虑不同时域的商用车预见性巡航控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.012',
  'title': '基于Transformer的纯电动汽车充电时间预测'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.013',
  'title': '磷酸铁锂电池碳纳米管膜加热结构设计及验证'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.014',
  'title': '基于多工况模式的复合型悬架平顺性研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.015',
  'title': '基于NSGA-II的纯电动汽车悬置系统隔振率优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.016',
  'title': '基于KANN-DBSCAN带宽优化的核密度估计载荷谱外推'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.017',
  'title': '3D打印梯度随机蜂窝夹芯结构耐撞性研究与多目标优化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.018',
  'title': '浮动式配流盘柱塞泵马达系统动力学建模及特性研究'},

In [32]:
len(data_total)

1925

In [28]:
def remove_duplicates(lst):
    return list(set(lst))

In [29]:
unique_urls=remove_duplicates(urls)

In [40]:
dataset=[]
def clean(el):
    return " ".join("".join(el.itertext()).split())

def pick_en(vals):
    if len(vals) > 1:
        return vals[1]          
    return vals[0] if vals else None 

for paper in data_total:
    url=paper['link']
    print(url)
    resp = requests.get(url, headers=headers)
    if resp.status_code != 200:          
        print("errorcode200:", resp.status_code, url)
        continue
    
    tree = etree.HTML(resp.text)
    xpath_ref='//div[@id="collapseThree"]//table//tr'
    elements_ref=tree.xpath(xpath_ref)
    xpath_title = '//meta[@name="citation_title"]/@content'
    elements_title = tree.xpath(xpath_title)
    xpath_keywords = '//meta[@name="DC.Keywords"]/@content'
    elements_kewords = tree.xpath(xpath_keywords)

    

    for elm in elements_ref:
        
        row = {
            'reference':clean(elm),
            'title':pick_en(elements_title),
            'keywords': pick_en(elements_kewords),
            'link':url
            }
    
        dataset.append(row)
    time.sleep(0.4)

https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.020
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.ep.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.ep.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.006

In [20]:
url=data_total[0]['link']
resp = requests.get(url, headers=headers)
tree = etree.HTML(resp.text)
xpath_ref='//div[@id="collapseThree"]//table//tr'
elements_ref=tree.xpath(xpath_ref)
elements_ref

[<Element tr at 0x10d1a9200>,
 <Element tr at 0x10d1aa680>,
 <Element tr at 0x10d33d7c0>,
 <Element tr at 0x10dedda00>,
 <Element tr at 0x10dedd9c0>,
 <Element tr at 0x10dede680>,
 <Element tr at 0x10dedce80>,
 <Element tr at 0x10dedf3c0>,
 <Element tr at 0x10deded40>,
 <Element tr at 0x10dedcb40>,
 <Element tr at 0x10dedd400>,
 <Element tr at 0x10dedce00>,
 <Element tr at 0x10dedd2c0>,
 <Element tr at 0x10dede940>,
 <Element tr at 0x10dede700>,
 <Element tr at 0x10dedd580>,
 <Element tr at 0x10dedd700>,
 <Element tr at 0x10dedc080>,
 <Element tr at 0x10dedf340>,
 <Element tr at 0x10dede540>,
 <Element tr at 0x10dedd040>,
 <Element tr at 0x10dedf5c0>,
 <Element tr at 0x10deddbc0>,
 <Element tr at 0x10dedecc0>,
 <Element tr at 0x10dede400>,
 <Element tr at 0x10dede5c0>,
 <Element tr at 0x10dede640>,
 <Element tr at 0x10dede280>]

In [24]:
print(" ".join("".join(elements_ref[0].itertext()).split()))

[1] 吴昊天， 牟康伟， 王江东. 多维恶劣场景下基于有限状态机的决策控制方法研究［J］. 质量与认证， 2021（11）： 51-54.

In [26]:
print(tree.xpath(xpath_ref))

[<Element tr at 0x10d1a9200>, <Element tr at 0x10d1aa680>, <Element tr at 0x10d33d7c0>, <Element tr at 0x10dedda00>, <Element tr at 0x10dedd9c0>, <Element tr at 0x10dede680>, <Element tr at 0x10dedce80>, <Element tr at 0x10dedf3c0>, <Element tr at 0x10deded40>, <Element tr at 0x10dedcb40>, <Element tr at 0x10dedd400>, <Element tr at 0x10dedce00>, <Element tr at 0x10dedd2c0>, <Element tr at 0x10dede940>, <Element tr at 0x10dede700>, <Element tr at 0x10dedd580>, <Element tr at 0x10dedd700>, <Element tr at 0x10dedc080>, <Element tr at 0x10dedf340>, <Element tr at 0x10dede540>, <Element tr at 0x10dedd040>, <Element tr at 0x10dedf5c0>, <Element tr at 0x10deddbc0>, <Element tr at 0x10dedecc0>, <Element tr at 0x10dede400>, <Element tr at 0x10dede5c0>, <Element tr at 0x10dede640>, <Element tr at 0x10dede280>]

In [35]:
import pandas as pd

In [42]:
len(dataset)

39057

In [41]:
dataset

[{'reference': '[1] SAVARESI S M, POUSSOT-VASSAL C, SPELTA C,et al. Semi-active suspension control design for vehicles[M]. Oxford: Elsevier,2010.[2] GUGLIELMINO E, SIRETEANU T, STAMMERA C W, et al. Semi-active suspension control:improved vehicle ride and road friendliness[M]. London: Springer,2008.[3] YOKOYAMA M, HEDRICK J K, TOYAMA S. A model follow sliding mode control for semi-active suspension systems[C]. Proceedings of the American Control Conference, Arlington, VA June25-27,2001:2652 -2657.[4] DIXIT R, BUCKNER G. Sliding mode observation and control for semiactive vehicle suspensions[J]. Vehicle System Dynamics,2005,43(2):83-105.[5] CHEN B, SHIU Y, HSIEH F. Sliding-mode control for semi-active suspension with actuator dynamics[J]. Vehicle System Dynamics,2011,49(1-2):277-290.[6] FALLAH M S, BHAT R, XIE W F. H∞ robust control of semi-active Macpherson suspension system: new applied design[J]. Vehicle System Dynamics,2010,48(3):339-360.[7] DU H, ZHANG N, NAGHDY F. Robust control of vehicle electrorheologi-cal suspensnion subject to measurement noises[J]. Vehicle System Dyna-mics,2011,49(1-2):257-275.[8] TSENG H E, HEDRICK J K. Semi-active control laws-optimal and sub-optimal[J]. Vehicle System Dynamics,1994,23(1):545-569.[9] VANDERAA M A H, MUIJDERMAN J H E A, VELDPAUS F E. Constrained optimal control of semi-active suspension systems with pre-view[J]. Vehicle System Dynamics,1997,28(4-5):307-323.[10] BREZAS P, SMITH M C, HOULT W. A clipped-optimal algorithm for semi-active vehicle suspensions: theory and experimental evaluation[J]. Automatica,2015,53(3):188-194.[11] KARNOPP D C,CROSBY M J, HARWOOD R A. Vibration control using semi-active force generators[J]. ASME Journal of Engineering for Industry,1974,96(2):619-626.[12] SAMMIER D, SENAME O, DUGARD L. Skyhook and H∞ control of semi-active suspensions some practical aspects[J]. Vehicle System Dyn-amics,2003,39(4):279-308.[13] SAVARESI S M, SILANI E, BITTANTI S. Acceleration driven damper(ADD): an optimal control algorithm for comfort-oriented semiactive suspensions[J]. Journal of Dynamic Systems, Measurement, and Control,2005,127(6):218-229.[14] MORSELLI R,ZANASI R. Control of port hamiltonian systems by dissipative devices and its application to improve the semi-active suspension behavior[J]. Mechatronics,2008,18(7):364-369.[15] SAVARESI S M, SPELTA C. Mixed sky-hook and ADD:approaching the filtering limits of a semi-active suspension[J]. Journal of Dynamic Systems Measurement, and Control,2007,129(7):382-392.[16] LIU Y, ZUO L. Mixed skyhook and power-driven-damper: a new low-jerk semi-active suspension control based on power flow analysis[J]. Journal of Dynamic Systems, Measurement and Control,2016,138(8):081009-1-081009-10.[17] SPELTA C, CUTINI M, BERTINOTTI S A, et al. A new concept of semi-active suspension with controllable damper and spring[C]. Proceeding of the European Control Conference, Budapest, Hungary, August23-26,2009.[18] SPELTA C, PREVIDI F, SAVARESI S M,et al. Performance analysis of semi-active suspensions with control of variable damping and stiffness[J]. Vehicle System Dynamics,2011,49(1):237-256.[19] SANDE T P J, BESSELINK I J M, NIJMEIJER H. Rule-based control of a semi-active suspension for minimal sprung mass acceleration: design and measurement[J]. Vehicle System Dynamics,2016,54(1):281-300.[20] 郭孔辉,王杨.一种用于车辆悬架系统的智能加速度阻尼半主动控制方法:CN106515348A[P].2017-03-22.',
  'title': 'A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension',
  'keywords': 'semi-active suspension,skyhook control,ADD control,whole frequency range,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001'},
 {'reference': '[1] EEA (Energy and Environmental Analysis, Inc.) 2007. Update for advanced technologies to improve fuel economy of light duty vehicles[R]. Prepared for US Department of Energy. Arlington, Virginia, August.[2] National Research Council. Committee on the assessment of technologies for improving light-duty vehicle fuel economy 2010[R]. Assessment of Technologies for Improving Light Duty Vehicle Fuel Economy. ISBN:0-309-15608-4.[3] 中国机动车环境管理年报(2017年度)[R].北京:中华人民共和国生态环境部,2018.[4] MIKULIC I, KOELMAN H, MAJKOWSKI S, et al. A study about particle filter application on a state-of-the-art homogeneous turbocharged 2L DI gasoline engine[R]. Aachener Kolloquium,2010.[5] ZHAN R, EAKLE S, WEBER P. Simultaneous reduction of PM, HC, CO and NOx emissions from a GDI engine[C]. SAE Paper 2010-01-0365.[6] CUSTER N, PAKKO J, BOERENSEN C, et al. Lubricant-derived ash impact on gasoline particulate filter performance[C]. SAE Paper 2016-01-0942.[7] SAPPOK A, WANG Y, KAMP C, et al. Theoretical and experimental analysis of ash accumulation and mobility in ceramic exhaust particulate filters and potential for improved ash management[C]. SAE Paper 2014-01-1517.[8] SHAO H, LAM W, REMIAS J, et al. Effect of lubricating oil properties on the performance of gasoline particulate filter (GPF)[C]. SAE Paper 2016-01-2287.[9] LAMBERT C, BUMBAROSKA M, DOBSON D, et al. Analysis of high mileage gasoline exhaust particle filters[C]. SAE Paper 2016-01-0941.',
  'title': 'An Experimental Study on the Impact of Lubricant Ash onGasoline Particle Filter Performance of GDI Vehicle',
  'keywords': 'gasoline direct injection vehicle,gasoline particulate filter (GPF),accelerated ash accumulation,worldwide harmonized light vehicles test cycle (WLTC),durability,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.002'},
 {'reference': '[1] DURBIN T, WILSON R, NORBECK J, et al. Estimates of the emission rates of ammonia from light-duty vehicles using standard chassis dynamometer test cycles[J]. Atmospheric Environment,2002,36(9):1475-1482.[2] LIVINGSTON C, RIEGER P, WINER A. Ammonia emissions from a representative in-use fleet of light and medium-duty vehicles in the California South Coast Air Basin[J]. Atmospheric Environment,2009(43):3326-3333.[3] 董艳强,陈长虹,黄成,等.长江三角洲地区人为源氨排放清单及分布特征[J].环境科学学报,2009(8):1611-1617.[4] MENG W J, et al. Improvement of a global high-resolution ammonia emission inventory for combustion and industrial sources with new data from the residential and transportation sectors[J]. Environmental Science and Technology,2017,51(5):2821-2829.[5] HEEB N V, FORSS A M, BRUHLMANN S, et al. Three-way catalyst-induced formation of ammonia-velocity- and acceleration-dependent emission factors[J]. Atmospheric Environment,2006(40):5986-5997.[6] WANG C X, ZHENG T T, LU J, et al. Three-way catalytic reactions on Rh-based catalyst: effect of Rh/ceria interfaces[J]. Applied Catalysis A: General,2017(6):30-39.[7] HEEB N V, SAXER C J, FORSS A M, et al. Trends of NO-, NO2-, and NH3- emissions from gasoline-fueled Euro-3-to Euro-4-passenger cars[J]. Atmospheric Environment,2008(42):2543-2554.[8] HEEB N V, SAXER C J, FORSS A, et al. Correlation of hydrogen, ammonia and nitrogen monoxide (nitric oxide) emissions of gasoline-fueled Euro-3 passenger cars at transient driving[J]. Atmospheric Environment,2006(40):3750-3763.',
  'title': 'A Research on Ammonia Emission Characteristics of Light-dutyVehicles Based on WLTC and NEDC Cycles',
  'keywords': 'ammonia emission characteristics,WLTC cycle,NEDC cycle,three-way catalytic converter,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.003'},
 {'reference': '[1] 屈盛官,夏伟,王颖,等.高强化柴油机气缸套周围冷却水流动的数值模拟和试验研究[J].内燃机工程,2004(4):32-35.[2] 郭良平,张卫正,王长园,等.柴油机气缸盖传热规律研究[J].北京理工大学学报,2011,31(3):277-282.[3] 白敏丽,吕继组,丁铁新,等.六缸柴油机冷却系统流动与传热的数值模拟研究[J].内燃机学报,2004(6):525-531.[4] 王兆文,黄荣华,成晓北,等.车用柴油机气缸盖热负荷的改善[J].华中科技大学学报:自然科学版,2008(8):99-102.[5] 王兆文,黄荣华,成晓北,等.重型车用柴油机气缸盖内流动与传热研究[J].汽车工程,2008,30(4):312-316.[6] 王兆文,赵强,陈雄,等.基于正交设计方法的气缸盖上水孔流量测量技术[J].农业机械学报,2014,45(4):42-48,21.[7] 刘福水,闵祥芬,樊丰,等.柴油机冷却水套的优化设计方法[J].汽车工程,2014,36(6):728-733.[8] 陈思南,薛冬新,周禛,等.某16缸中速柴油机冷却水系统分析与优化[J].内燃机工程,2015,36(4):133-139.[9] 陈铄,苏中地,林景殿.气体涡轮流量计流道压力损失的数值模拟[J].中国计量学院学报,2015,26(2):134-139.[10] CHEN X Q, YU X L, LU Y J, et al. Study of different cooling structures on the thermal status of an internal combustion engine[J]. Applied Thermal Engineering,2017,116:419-432.',
  'title': 'A Study on the Influence of Measurement Module on the Measurement ofFlow Through Upper Water Holes on Cylinder Block in a Diesel Engine',
  'keywords': 'upper water hole on cylinder block,flow measurement,turbine flowmeter,measurement module,test,simulation,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004'},
 {'reference': '[1] TOMISHIMA H, MATSUMOTO T, OKI M. The advanced diesel common rail system for achieving a good balance between ecology and economy[C]. SAE Paper 2008-28-0017.[2] 苏海峰,张幽彤,梁建伟.高压共轨多次喷射的温度特性[J].北京理工大学学报,2013,33(10):1027-1031.[3] 聂枝根,申立中.高压共轨柴油机燃油状态系统的研究[J].现代车用动力,2010(1):15-18.[4] SALVADOR F J, GLMERO J, CARRERS M, et al. Fuel temperature influence on the performance of a last generation common-rail diesel ballistic injector. PartⅡ[J]. Energy Conversion & Management,2016,114(4):375-394.[5] GUPTA V K, ZHANG Zhen, SUN Zongxuan. Modeling and control of a novel pressure regulation mechanism for common rail fuel injection systems[J]. Applied Mathematical Modeling,2011,35:3473-3483.[6] 韩晓梅,林学东,李德刚.轻型柴油机起动过程瞬态喷油量控制策略研究[J].汽车工程,2017,39(1):23-27.[7] 黄丫,林学东,段春丽,等.高压共轨柴油机起动控制策略与参数优化研究[J].汽车工程,2018,40(5):501-507.[8] 杨世铭,陶文铨.传热学[M].北京:高等教育出版社,2006.8.[9] 张建明,张卫刚,王亚伟.柴油高压物理特性研究[J].高压物理学报,2005,19(1):41-44.[10] CHEN Gong. Study of temperature effects on fuel injection, combustion, and emission of direct-injection diesel engine[J]. Journal of Engineering for Gas Turbines and Power,2009,113(2):1-8.[11] YANG Xiaohong, LI Wenyang. A novel theoretical approach to the temperature-viscosity for fluidic fuel[J]. Fuel,2015,153(8):85-89.',
  'title': 'Calculation Correction of Fuel Injection Parameters at Different FuelTemperatures of High Pressure Common Rail System',
  'keywords': 'power machinery and engineering,fuel injection quantity,high pressure common rail,temperature,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005'},
 {'reference': '[1] 陈慧岩,熊光明,龚建伟,等.无人驾驶汽车概论[M].北京:北京理工大学出版社,2014.[2] 陈慧岩,陈舒平,龚建伟.智能汽车横向控制方法研究综述[J].兵工学报,2017,38(6):1203-1214.[3] 陈慧岩,张玉.军用地面无人机动平台技术发展综述[J].兵工学报,2014,35(10):1696-1706.[4] 金辉,李世杰.基于极限车速的车辆稳定性控制研究[J].汽车工程,2018,40(1):48-56.[5] LIU K, GONG J, KURT A, et al. A model predictive-based approach for longitudinal control in autonomous driving with lateral interruptions[C]. IEEE International Conference on Intelligent Vehicles Symposium (IV),2017:359-364.[6] 龚建伟,姜岩,徐威.无人驾驶车辆模型预测控制[M].北京:北京理工大学出版社,2014.[7] BROWN M, ERLIEN S M, FUNKE J, et al. Collision avoidance and stabilization for autonomous vehicles in emergency scenarios[J]. IEEE Transactions on Control Systems Technology,2017,25(4):1204-1216.[8] 李静,王子涵,王宣锋.基于相平面法的制动方向稳定性分析[J].汽车工程,2014,36(8):974-979.[9] LIU K, GONG J, CHEN S, et al. Model predictive stabilization control of high-speed autonomous ground vehicles considering the effect of road topography[J]. Applied Sciences,2018,8(5):822-837.[10] PACEJKA H B. Tyre and vehicle dynamics[M]. Netherlands: Butterworth-Heinemann,2006.[11] 李玲,马力,牟宇,等.模型车轮胎侧偏刚度的参数辨识方法[J].汽车工程,2016,38(12):1508-1514,1466.[12] MATTINGLEY J, BOYD S. CVXGEN: a code generator for embedded convex optimization[J]. Optimization and Engineering,2012,13(1):1-27.[13] 余志生.汽车理论[M].北京:机械工业出版社,2007.',
  'title': 'A Research on Handling Stability of High-speed Unmanned Vehicles',
  'keywords': 'high-speed unmanned vehicles,vehicle dynamics,handling stability,model predictive control,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006'},
 {'reference': '[1] WONG N, CHAMBERS C, STOL K, et al. Development of a robotic driver for autonomous vehicle following[J]. International Journal of Intelligent Systems Technologies and Applications,2010,8(1-4):276-287.[2] HIRATA N, MIZUTANI N, MATSUI H, et al. Fuel consumption in a driving test cycle by robotic driver considering system dynamics[C]. IEEE International Conference on Robotics and Automation (ICRA), Seattle, Washington, USA,2015:3374-3379.[3] CHEN G, ZHANG W G. Hierarchical coordinated control method for unmanned robot applied to automotive test[J]. IEEE Transactions on Industrial Electronics,2016,63(2):1039-1051.[4] CHEN G, ZHANG W G. Digital prototyping design of electromagnetic unmanned robot applied to automotive test[J]. Robotics and Computer-Integrated Manufacturing,2015,32:54-64.[5] 牛喆,牛志刚.汽车驾驶机器人换挡机械手运动仿真分析[J].中国农机化学报,2013,34(4):197-200.[6] 黄开胜,张尧,卓晴.一种汽车自动驾驶机器人:201410174404.2[P].2014-04-28.[7] 石柱,张文俊,胡可凡,等.自动驾驶机器人:201110247651.7[P].2011-08-25.[8] 陈弘,李伟,乔胜华.用于汽车试验的驾驶机器人:201110264909.4[P].2011-9-7.[9] 卢伟,陈浩,王玲,等.拖拉机驾驶机器人换挡机械手运动分析[J].农业机械学报,2016,47(1):37-44.[10] 陈刚,张为公.基于模糊自适应PID的汽车驾驶机器人的车速控制[J].汽车工程,2012,34(6):511-516.[11] 佘致廷,袁俊波,李英,等.基于模糊PI控制策略的电动汽车无离合器两挡变速控制[J].汽车工程,2012,34(11):976-980.[12] 陈刚,张为公.汽车驾驶机器人车速跟踪神经网络控制方法[J].中国机械工程,2012,23(2):240-243.[13] 袁安富,伏俊杰.驾驶机器人油门机械腿模糊自整定PID控制方法[J].自动化与仪表,2013,28(3):5-9.[14] 刘坤明,徐国艳,余贵珍.驾驶机器人机械腿动力学建模与仿真分析[J].北京航空航天大学学报,2016,42(8):1709-1714.[15] 毕翔,韩江洪,刘征宇.模糊离散事件系统的自适应监督控制[J].仪器仪表学报,2013,4(10):2170-2176.[16] 郭瑜.半监督迭代模糊聚类模型及其在中长期水文预报中的应用[J].东南大学学报:自然科学版,2013,43:59-62.[17] 国家环境保护总局.轻型汽车污染物排放限值及测量方法(中国Ⅲ、Ⅳ阶段):GB 18352.3—2005[S].北京:中国标准出版社,2005.[18] 詹兴泉.车用催化转化器评价技术及耐久试验方法间相关性研究[D].武汉:武汉理工大学,2002.',
  'title': 'Fuzzy Supervisory Control of Mechanical Legs of Unmanned Robots',
  'keywords': 'unmanned robot,dynamic model,fuzzy supervisory control,stability,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007'},
 {'reference': '[1] 吴光强,栾文博.汽车传动系相关NVH问题的动力学研究论述[J].机械工程学报,2013,49(24):108-116.[2] 高炳钊,洪金龙,陈虹.汽车传动系统平顺性驾驶品质控制[J].控制理论与应用,2017,34(7):849-866.[3] COUDERC P, CALLENAERE J. Vehicle driveline dynamic behaviour: experimentation and simulation[J]. Journal of Sound & Vibration,1998,218(1):133-157.[4] FARSHIDIANFAR A, EBRAHIMI M, BARTLETT H. Hybrid modelling and simulation of the torsional vibration of vehicle driveline systems[J]. Proceedings of the Institution of Mechanical Engineers, Part D: Journal of Automobile Engineering,2003,215(2):217-229.[5] FARSHIDIANFAR A, EBRAHIMI M, BARTLETT H, et al. Driveline shuffle in rear wheel vehicles[J]. International Journal of Heavy Vehicle Systems,2002,9(1):76-91.[6] BARTRAM M, MAVROS G, BIGGS S. A study on the effect of road friction on driveline vibrations[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2010,224(4):321-340.[7] FARSHIDIANFAR A, EBRAHIMI M, RAH-NEJAT H, et al. Optimization of the high-frequency torsional vibration of vehicle driveline systems using genetic algorithms[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2002,216(3):249-262.[8] GKINIS T, RAHMANI R, RAHNEJAT H. Effect of clutch lining frictional characteristics on take-up judder[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2017,31(3):493-503.[9] 徐红亮,龚宪生,廉超,等.新型汽车扭振减振器扭振特性试验研究[J].振动与冲击,2013,32(6):29-32.[10] 李亚南,郝志勇,郑旭,等.基于解决发动机加速异响问题的TVD分析优化[J].振动与冲击,2018,37(6):86-91.[11] YANG X S. Firefly algorithms for multimodal optimization[J]. Mathematics,2012,5792:169-178.[12] YANG X S, HE X. Firefly algorithm: recent advances and applications[J]. International Journal of Swarm Intelligence,2013,1(1):36-50.[13] FISTER I, JR I F, YANG X S, et al. A comprehensive review of firefly algorithms[J]. Swarm & Evolutionary Computation,2013,13:34-46.[14] GARCIAGONZALO E, FERNANDEZLUNA J, MARTINEZ J A. A brief historical review of particle swarm optimization (PSO)[J]. Journal of Bioinformatics & Intelligent Control,2012,1(1):3-16.[15] KENNEDY J. Particle swarm optimization[C]. Proc. of 1995 IEEE Int. Conf. Neural Networks,Perth, Australia, Nov.27-1995.[16] EBERHART R C, SHI Y. Particle swarm optimization: developments, applications and resources[C]. Congress on Evolutionary Computation. IEEE,2001.',
  'title': 'Estimation of Excitation Torque Fluctuation and Torsional VibrationPerformance Adjustment of Automobile Transmission System',
  'keywords': 'transmission system,parameter estimation,torque fluctuation,torsional vibration test,order analysis,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.008'},
 {'reference': '[1] 杨易,徐永康,沈夏威,等.基于气动升力的汽车底部流场改进[J].中南大学学报:自然科学版,2013,44(10):4063-4068.[2] YAN X, QIAO X, ZHAO Z M, et al. Comparative study on external flow simulation of passenger car with complex underbody and flat underbody[J]. Applied Mechanics and Materials,2013,380-384:69-72.[3] 肖能,王小碧,王伟民,等.前扰流板对机舱进气量和车辆气动阻力的影响研究[J].汽车工程,2014,36(10):1254-1257.[4] HWANG B G, LEE S, LEE E J, et al. Reduction of drag in heavy vehicles with two different types of advanced side skirts[J]. Journal of Wind Engineering & Industrial Aerodynamics,2016,155:36-46.[5] WANG H, ZHOU Y, ZOU C, et al. Aerodynamic drag reduction of an Ahmed body based on deflectors[J]. Journal of Wind Engineering & Industrial Aerodynamics,2016,148:34-44.[6] 张勇,潘正宇,谷正气,等.基于鲨鱼鳍的汽车车身仿生气动减阻研究[J].汽车工程,2017,39(9):1018-1024+1029.[7] 汪怡平,王涛,黎帅.基于自由变形技术的汽车气动减阻优化[J].机械工程学报,2017,53(9):135-143.[8] MCNALLY J, FERNANDEZ E, ROBERTSON G, et al. Drag reduction on a flat-back ground vehicle with active flow control[J]. Journal of Wind Engineering & Industrial Aerodynamics,2015,145:292-303.[9] 丁鹏,葛如海,李智,等.汽车自适应可调尾翼系统的研发[J].汽车工程,2017,39(08):895-899.[10] 王冰心,杨志刚,朱晖,等.定常喷/吸流动主动控制方法减阻研究[J].同济大学学报:自然科学版,2017,45(9):1383-1389.[11] 文琪,谷正气,黄泰明,等.基于尾气排放控制尾涡的新型减阻方法研究[J].空气动力学学报,2018,36(1):47-51.[12] 崔文诗,杨志刚,王国俊.合成射流激励频率对车辆气动阻力的影响[J].同济大学学报:自然科学版,2017,45(8):1167-1173.[13] 袁志群,谷正气,杨明智,等.底部结构对轿车侧风气动特性的影响分析[J].汽车工程,2017,39(1):28-34.[14] YUAN Z, GU Z, WANG Y, et al. Numerical investigation for the influence of the car underbody on aerodynamic force and flow structure evolution in crosswind[J]. Advances in Mechanical Engineering,2018,10(10):1-14.[15] 刘立宁,石硕,郗学峰,等.隔离带对侧风条件下超车过程车辆气动力的影响[J].汽车工程,2018,40(4):437-442.[16] 龚旭,谷正气,李振磊,等.侧风状态下轿车气动特性数值模拟方法的研究[J].汽车工程,2010,32(01):13-16.[17] 杨建国.基于离散气动系数的轿车瞬态侧风稳定性研究[J].中国机械工程,2016,27(4):549-554.[18] WANG Y. Numerical and experimental investigations on the aerodynamic characteristic of three typical passenger vehicles[J]. Journal of Applied Fluid Mechanics,2014,7(4):6859-6671.[19] 杨易,聂云,徐永康,等.车尾造型对凹坑型非光滑车身气动减阻的影响[J].汽车工程,2015,37(3):300-306.',
  'title': 'A Study on Car Drag Reduction by Active and PassiveControl of Complex Underbody Flow Field',
  'keywords': 'aerodynamic drag,spoiler,side-skirts,underbody suction control slot,wake jet control slot,dynamic control method,',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.009'},

In [72]:
df = pd.DataFrame(dataset)

In [73]:
df.shape

(39057, 4)

In [74]:
df['reference'].value_counts().reset_index()

,reference,count
0,,167
1,LI K Q， CHANG X Y， LI J W， et al. Cloud control system for intelligent and connected vehicles and its application［J］. Automotive Engineering， 2020， 42（12）： 1595-1605.,6
2,ZHOU W Q， QI X， CHEN L， et al. Vehicle state estimation based on the combination of unscented Kalman filtering and genetic algorithm［J］. Automotive Engineering， 2019， 41（2）： 198-205.,4
3,HU J， ZHANG Z H， CHEN R N， et al. Spatio-temporal joint planning method of intelligent vehicles based on improved hybrid A*［J］. Automotive Engineering， 2023， 45（7）： 1123-1133.,4
4,China Society of Automotive Engineers. Technology roadmap for energy saving and new energy vehicles 2.0［M］. Beijing： China Machine Press， 2020.,4
...,...,...
38643,SUN Zhipeng，CHEN Liduo，Bu Xiangjun. Study on performance evolution of power battery after crushing mechanical damage［J］. Power Source Tech.，2020，44（7）：964-966.,1
38644,11 李会峰，庞静，卢世刚. 锂离子电池滥用条件下的安全性研究［J］. 电源技术，2013，37（12）：2235-2238.,1
38645,LI Huifeng，PANG Jing，LU Shigang.Study on safety performance of Li-ion power batteries under deviant use ［J］. Power Source Tech.，2013，37（12）：2235-2238.,1
38646,12 郑芸菲. 锂离子电池在滥用条件下的安全性研究［J］. 船电技术， 2021，41（2）：44-47.,1
38647,ZHENG Yunfei. Study on safety of lithium-ion battery under overuse conditions［J］. Marine Electric & Electronic Technology， 2021，41（2）： 44-47.,1

In [75]:
df.head(10)

,reference,title,keywords,link
0,"[1] SAVARESI S M, POUSSOT-VASSAL C, SPELTA C,et al. Semi-active suspension control design for vehicles[M]. Oxford: Elsevier,2010.[2] GUGLIELMINO E, SIRETEANU T, STAMMERA C W, et al. Semi-active suspension control:improved vehicle ride and road friendliness[M]. London: Springer,2008.[3] YOKOYAMA M, HEDRICK J K, TOYAMA S. A model follow sliding mode control for semi-active suspension systems[C]. Proceedings of the American Control Conference, Arlington, VA June25-27,2001:2652 -2657.[4] DIXIT R, BUCKNER G. Sliding mode observation and control for semiactive vehicle suspensions[J]. Vehicle System Dynamics,2005,43(2):83-105.[5] CHEN B, SHIU Y, HSIEH F. Sliding-mode control for semi-active suspension with actuator dynamics[J]. Vehicle System Dynamics,2011,49(1-2):277-290.[6] FALLAH M S, BHAT R, XIE W F. H∞ robust control of semi-active Macpherson suspension system: new applied design[J]. Vehicle System Dynamics,2010,48(3):339-360.[7] DU H, ZHANG N, NAGHDY F. Robust control of vehicle electrorheologi-cal suspensnion subject to measurement noises[J]. Vehicle System Dyna-mics,2011,49(1-2):257-275.[8] TSENG H E, HEDRICK J K. Semi-active control laws-optimal and sub-optimal[J]. Vehicle System Dynamics,1994,23(1):545-569.[9] VANDERAA M A H, MUIJDERMAN J H E A, VELDPAUS F E. Constrained optimal control of semi-active suspension systems with pre-view[J]. Vehicle System Dynamics,1997,28(4-5):307-323.[10] BREZAS P, SMITH M C, HOULT W. A clipped-optimal algorithm for semi-active vehicle suspensions: theory and experimental evaluation[J]. Automatica,2015,53(3):188-194.[11] KARNOPP D C,CROSBY M J, HARWOOD R A. Vibration control using semi-active force generators[J]. ASME Journal of Engineering for Industry,1974,96(2):619-626.[12] SAMMIER D, SENAME O, DUGARD L. Skyhook and H∞ control of semi-active suspensions some practical aspects[J]. Vehicle System Dyn-amics,2003,39(4):279-308.[13] SAVARESI S M, SILANI E, BITTANTI S. Acceleration driven damper(ADD): an optimal control algorithm for comfort-oriented semiactive suspensions[J]. Journal of Dynamic Systems, Measurement, and Control,2005,127(6):218-229.[14] MORSELLI R,ZANASI R. Control of port hamiltonian systems by dissipative devices and its application to improve the semi-active suspension behavior[J]. Mechatronics,2008,18(7):364-369.[15] SAVARESI S M, SPELTA C. Mixed sky-hook and ADD:approaching the filtering limits of a semi-active suspension[J]. Journal of Dynamic Systems Measurement, and Control,2007,129(7):382-392.[16] LIU Y, ZUO L. Mixed skyhook and power-driven-damper: a new low-jerk semi-active suspension control based on power flow analysis[J]. Journal of Dynamic Systems, Measurement and Control,2016,138(8):081009-1-081009-10.[17] SPELTA C, CUTINI M, BERTINOTTI S A, et al. A new concept of semi-active suspension with controllable damper and spring[C]. Proceeding of the European Control Conference, Budapest, Hungary, August23-26,2009.[18] SPELTA C, PREVIDI F, SAVARESI S M,et al. Performance analysis of semi-active suspensions with control of variable damping and stiffness[J]. Vehicle System Dynamics,2011,49(1):237-256.[19] SANDE T P J, BESSELINK I J M, NIJMEIJER H. Rule-based control of a semi-active suspension for minimal sprung mass acceleration: design and measurement[J]. Vehicle System Dynamics,2016,54(1):281-300.[20] 郭孔辉,王杨.一种用于车辆悬架系统的智能加速度阻尼半主动控制方法:CN106515348A[P].2017-03-22.",A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001
1,"[1] EEA (Energy and Environmental Analysis, Inc.) 2007. Update for advanced technologies to improve fuel economy of light duty vehicles[R]. Prepared for US Department of Energy. Arlington, Virginia, August.[2] National Research Council. Committee on the assessment of technologies for improving light-duty vehicle fuel economy 2010[R]. Assessment of Technologies for Improving Light Duty Vehicle Fuel Economy. ISBN:0-309-15608-4.[3] 中国机动车环境管理年报(2017年度)[R].北京:中华人民共和国生态环境部,2018.[4] MIKULIC I, KOELMAN H, MAJKOWSKI S, et al. A study about particle filter application on a state-of-the-art homogeneous turbocharged 2L DI gasoline engine[R]. Aachener Kolloquium,2010.[5] ZHAN R, EAKLE S, WEBER P. Simultaneous reduction of PM, HC, CO and NOx emissions from a GDI engine[C]. SAE Paper 2010-01-0365.[6] CUSTER N, PAKKO J, BOERENSEN C, et al. Lubricant-derived ash impact on gasoline particulate filter performance[C]. SAE Paper 2016-01-0942.[7] SAPPOK A, WANG Y, KAMP C, et al. Theoretical and experimental analysis of ash accumulation and mobility in ceramic exhaust particulate filters and potential for improved ash management[C]. SAE Paper 2014-01-1517.[8] SHAO H, LAM W, REMIAS J, et al. Effect of lubricating oil properties on the performance of gasoline particulate filter (GPF)[C]. SAE Paper 2016-01-2287.[9] LAMBERT C, BUMBAROSKA M, DOBSON D, et al. Analysis of high mileage gasoline exhaust particle filters[C]. SAE Paper 2016-01-0941.",An Experimental Study on the Impact of Lubricant Ash onGasoline Particle Filter Performance of GDI Vehicle,"gasoline direct injection vehicle,gasoline particulate filter (GPF),accelerated ash accumulation,worldwide harmonized light vehicles test cycle (WLTC),durability,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.002
2,"[1] DURBIN T, WILSON R, NORBECK J, et al. Estimates of the emission rates of ammonia from light-duty vehicles using standard chassis dynamometer test cycles[J]. Atmospheric Environment,2002,36(9):1475-1482.[2] LIVINGSTON C, RIEGER P, WINER A. Ammonia emissions from a representative in-use fleet of light and medium-duty vehicles in the California South Coast Air Basin[J]. Atmospheric Environment,2009(43):3326-3333.[3] 董艳强,陈长虹,黄成,等.长江三角洲地区人为源氨排放清单及分布特征[J].环境科学学报,2009(8):1611-1617.[4] MENG W J, et al. Improvement of a global high-resolution ammonia emission inventory for combustion and industrial sources with new data from the residential and transportation sectors[J]. Environmental Science and Technology,2017,51(5):2821-2829.[5] HEEB N V, FORSS A M, BRUHLMANN S, et al. Three-way catalyst-induced formation of ammonia-velocity- and acceleration-dependent emission factors[J]. Atmospheric Environment,2006(40):5986-5997.[6] WANG C X, ZHENG T T, LU J, et al. Three-way catalytic reactions on Rh-based catalyst: effect of Rh/ceria interfaces[J]. Applied Catalysis A: General,2017(6):30-39.[7] HEEB N V, SAXER C J, FORSS A M, et al. Trends of NO-, NO2-, and NH3- emissions from gasoline-fueled Euro-3-to Euro-4-passenger cars[J]. Atmospheric Environment,2008(42):2543-2554.[8] HEEB N V, SAXER C J, FORSS A, et al. Correlation of hydrogen, ammonia and nitrogen monoxide (nitric oxide) emissions of gasoline-fueled Euro-3 passenger cars at transient driving[J]. Atmospheric Environment,2006(40):3750-3763.",A Research on Ammonia Emission Characteristics of Light-dutyVehicles Based on WLTC and NEDC Cycles,"ammonia emission characteristics,WLTC cycle,NEDC cycle,three-way catalytic converter,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.003
3,"[1] 屈盛官,夏伟,王颖,等.高强化柴油机气缸套周围冷却水流动的数值模拟和试验研究[J].内燃机工程,2004(4):32-35.[2] 郭良平,张卫正,王长园,等.柴油机气缸盖传热规律研究[J].北京理工大学学报,2011,31(3):277-282.[3] 白敏丽,吕继组,丁铁新,等.六缸柴油机冷却系统流动与传热的数值模拟研究[J].内燃机学报,2004(6):525-531.[4] 王兆文,黄荣华,成晓北,等.车用柴油机气缸盖热负荷的改善[J].华中科技大学学报:自然科学版,2008(8):99-102.[5] 王兆文,黄荣华,成晓北,等.重型车用柴油机气缸盖内流动与传热研究[J].汽车工程,2008,30(4):312-316.[6] 王兆文,赵强,陈雄,等.基于正交设计方法的气缸盖上水孔流量测量技术[J].农业机械学报,2014,45(4):42-48,21.[7] 刘福水,闵祥芬,樊丰,等.柴油机冷却水套的优化设计方法[J].汽车工程,2014,36(6):728-733.[8] 陈思南,薛冬新,周禛,等.某16缸中速柴油机冷却水系统分析与优化[J].内燃机工程,2015,36(4):133-139.[9] 陈铄,苏中地,林景殿.气体涡轮流量计流道压力损失的数值模拟[J].中国计量学院学报,2015,26(2):134-139.[10] CHEN X Q, YU X L, LU Y J, et al. Study of different cooling structures on the thermal status of an internal combustion engine[J]. Applied Thermal Engineering,2017,116:419-432.",A Study on the Influence of Measurement Module on the Measurement ofFlow Through Upper Water Holes on Cylinder Block in a Diesel Engine,"upper water hole on cylinder block,flow measurement,turbine flowmeter,measurement module,test,simulation,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004
4,"[1] TOMISHIMA H, MATSUMOTO T, OKI M. The advanced diesel common rail system for achieving a good balance between ecology and economy[C]. SAE Paper 2008-28-0017.[2] 苏海峰,张幽彤,梁建伟.高压共轨多次喷射的温度特性[J].北京理工大学学报,2013,33(10):1027-1031.[3] 聂枝根,申立中.高压共轨柴油机燃油状态系统的研究[J].现代车用动力,2010(1):15-18.[4] SALVADOR F J, GLMERO J, CARRERS M, et al. Fuel temperature influence on the performance of a last generation common-rail diesel ballistic injector. PartⅡ[J]. Energy Conversion & Management,2016,114(4):375-394.[5] GUPTA V K, ZHANG Zhen, SUN Zongxuan. Modeling and control of a novel pressure regulation mechanism for common rail fuel injection systems[J]. Applied Mathematical Modeling,2011,35:3473-3483.[6] 韩晓梅,林学东,李德刚.轻型柴油机起动过程瞬态喷油量控制策略研究[J].汽车工程,2017,39(1):23-27.[7] 黄丫,林学东,段春丽,等.高压共轨柴油机起动控制策略与参数优化研究[J].汽车工程,2018,40(5):501-507.[8] 杨世铭,陶文铨.传热学[M].北京:高等教育出版社,2006.8.[9] 张建明,张卫刚,王亚伟.柴油高压物理特性研究[J].高压物理学报,2005,19(1):41-44.[10] CHEN Gong. Study of temperature effects on fuel injection, combustion, and emission of direct-injection diesel engine[J]. Journal of Engineering for Gas Turbines and Power,2009,113(2):1-8.[11] YANG Xiaohong, LI Wenyang. A novel theoretical approach to the temperature-viscosity for fluidic fuel[J]. Fuel,2015,153(8):85-89.",Calculation Correction of Fuel Injection Parameters at Different FuelTemperatures of High Pressure Common Rail System,"power machinery and engineering,fuel injection quantity,high pressure common rail,temperature,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005
5,"[1] 陈慧岩,熊光明,龚建伟,等.无人驾驶汽车概论[M].北京:北京理工大学出版社,2014.[2] 陈慧岩,陈舒平,龚建伟.智能汽车横向控制方法研究综述[J].兵工学报,2017,38(6):1203-1214.[3] 陈慧岩,张玉.军用地面无人机动平台技术发展综述[J].兵工学报,2014,35(10):1696-1706.[4] 金辉,李世杰.基于极限车速的车辆稳定性控制研究[J].汽车工程,2018,40(1):48-56.[5] LIU K, GONG J, KURT A, et al. A model predictive-based approach for longitudinal control in autonomous driving with lateral interruptions[C]. IEEE International Conference on Intelligent Vehicles Symposium (IV),2017:359-364.[6] 龚建伟,姜岩,徐威.无人驾驶车辆模型预测控制[M].北京:北京理工大学出版社,2014.[7] BROWN M, ERLIEN S M, FUNKE J, et al. Collision avoidance and stabilization for autonomous vehicles in emergency scenarios[J]. IEEE Transactions on Control Systems Technology,2017,25(4):1204-1216.[8] 李静,王子涵,王宣锋.基于相平面法的制动方向稳定性分析[J].汽车工程,2014,36(8):974-979.[9] LIU K, GONG J, CHEN S, et al. Model predictive stabilization control of high-speed autonomous ground vehicles considering the effect of road topography[J]. Applied Sciences,2018,8(5):822-837.[10] PACEJKA H B. Tyre and vehicle dynamics[M]. Netherlands: Butterworth-Heinemann,2006.[11] 李玲,马力,牟宇,等.模型车轮胎侧偏刚度的参数辨识方法[J].汽车工程,2016,38(12):1508-1514,1466.[12] MATTINGLEY J, BOYD S. CVXGEN: a code generator for embedded convex optimization[J]. Optimization and Engineering,2012,13(1):1-27.[13] 余志生.汽车理论[M].北京:机械工业出版社,2007.",A Research on Handling Stability of High-speed Unmanned Vehicles,"high-speed unmanned vehicles,vehicle dynamics,handling stability,model predictive control,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006
6,"[1] WONG N, CHAMBERS C, STOL K, et al. Development of a robotic driver for autonomous vehicle following[J]. International Journal of Intelligent Systems Technologies and Applications,2010,8(1-4):276-287.[2] HIRATA N, MIZUTANI N, MATSUI H, et al. Fuel consumption in a driving test cycle by robotic driver considering system dynamics[C]. IEEE International Conference on Robotics and Automation (ICRA), Seattle, Washington, USA,2015:3374-3379.[3] CHEN G, ZHANG W G. Hierarchical coordinated control method for unmanned robot applied to automotive test[J]. IEEE Transactions on Industrial Electronics,2016,63(2):1039-1051.[4] CHEN G, ZHANG W G. Digital prototyping design of electromagnetic unmanned robot applied to automotive test[J]. Robotics and Computer-Integrated Manufacturing,2015,32:54-64.[5] 牛喆,牛志刚.汽车驾驶机器人换挡机械手运动仿真分析[J].中国农机化学报,2013,34(4):197-200.[6] 黄开胜,张尧,卓晴.一种汽车自动驾驶机器人:201410174404.2[P].2014-04-28.[7] 石柱,张文俊,胡可凡,等.自动驾驶机器人:201110247651.7[P].2011-08-25.[8] 陈弘,李伟,乔胜华.用于汽车试验的驾驶机器人:201110264909.4[P].2011-9-7.[9] 卢伟,陈浩,王玲,等.拖拉机驾驶机器人换挡机械手运动分析[J].农业机械学报,2016,47(1):37-44.[10] 陈刚,张为公.基于模糊自适应PID的汽车驾驶机器人的车速控制[J].汽车工程,2012,34(6):511-516.[11] 佘致廷,袁俊波,李英,等.基于模糊PI控制策略的电动汽车无离合器两挡变速控制[J].汽车工程,2012,34(11):976-980.[12] 陈刚,张为公.汽车驾驶机器人车速跟踪神经网络控制方法[J].中国机械工程,2012,23(2):240-243.[13] 袁安富,伏俊杰.驾驶机器人油门机械腿模糊自整定PID控制方法[J].自动化与仪表,2013,28(3):5-9.[14] 刘坤明,徐国艳,余贵珍.驾驶机器人机械腿动力学建模与仿真分析[J].北京航空航天大学学报,2016,42(8):1709-1714.[15] 毕翔,韩江洪,刘征宇.模糊离散事件系统的自适应监督控制[J].仪器仪表学报,2013,4(10):2170-2176.[16] 郭瑜.半监督迭代模糊聚类模型及其在中长期水文预报中的应用[J].东南大学学报:自然科学版,2013,43:59-62.[17] 国家环境保护总局.轻型汽车污染物排放限值及测量方法(中国Ⅲ、Ⅳ阶段):GB 18352.3—2005[S].北京:中国标准出版社,2005.[18] 詹兴泉.车用催化转化器评价技术及耐久试验方法间相关性研究[D].武汉:武汉理工大学,2002.",Fuzzy Supervisory Control of Mechanical Legs of Unmanned Robots,"unmanned robot,dynamic model,fuzzy supervisory control,stability,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007
7,"[1] 吴光强,栾文博.汽车传动系相关NVH问题的动力学研究论述[J].机械工程学报,2013,49(24):108-116.[2] 高炳钊,洪金龙,陈虹.汽车传动系统平顺性驾驶品质控制[J].控制理论与应用,2017,34(7):849-866.[3] COUDERC P, CALLENAERE J. Vehicle driveline dynamic behaviour: experimentation and simulation[J]. Journal of Sound & Vibration,1998,218(1):133-157.[4] FARSHIDIANFAR A, EBRAHIMI M, BARTLETT H. Hybrid modelling and simulation of the torsional vibration of vehicle driveline systems[J]. Proceedings of the Institution of Mechanical Engineers, Part D: Journal of Automobile Engineering,2003,215(2):217-229.[5] FARSHIDIANFAR A, EBRAHIMI M, BARTLETT H, et al. Driveline shuffle in rear wheel vehicles[J]. International Journal of Heavy Vehicle Systems,2002,9(1):76-91.[6] BARTRAM M, MAVROS G, BIGGS S. A study on the effect of road friction on driveline vibrations[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2010,224(4):321-340.[7] FARSHIDIANFAR A, EBRAHIMI M, RAH-NEJAT H, et al. Optimization of the high-frequency torsional vibration of vehicle driveline systems using genetic algorithms[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2002,216(3):249-262.[8] GKINIS T, RAHMANI R, RAHNEJAT H. Effect of clutch lining frictional characteristics on take-up judder[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2017,31(3):493-503.[9] 徐红亮,龚宪生,廉超,等.新型汽车扭振减振器扭振特性试验研究[J].振动与冲击,2013,32(6):29-32.[10] 李亚南,郝志勇,郑旭,等.基于解决发动机加速异响问题的TVD分析优化[J].振动与冲击,2018,37(6):86-91.[11] YANG X S. Firefly algorithms for multimodal optimization[J]. Mathematics,2012,5792:169-178.[12] YANG X S, HE X. Firefly algorithm: recent advances and applications[J]. International Journal of Swarm Intelligence,2013,1(1):36-50.[13] FISTER I, JR I F, YANG X S, et al. A comprehensive review of firefly algorithms[J]. Swarm & Evolutionary Computation,2013,13:34-46.[14] GARCIAGONZALO E, FERNANDEZLUNA J, MARTINEZ J A. A brief historical review of particle swarm optimization (PSO)[J]. Journal of Bioinformatics & Intelligent Control,2012,1(1):3-16.[15] KENNEDY J. Particle swarm optimization[C]. Proc. of 1995 IEEE Int. Conf. Neural Networks,Perth, Australia, Nov.27-1995.[16] EBERHART R C, SHI Y. Particle swarm optimization: developments, applications and resources[C]. Congress on Evolutionary Computation. IEEE,2001.",Estimation of Excitation Torque Fluctuation and Torsional VibrationPerformance Adjustment of Automobile Transmission System,"transmission system,parameter estimation,torque fluctuation,torsional vibration test,order analysis,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.008
8,"[1] 杨易,徐永康,沈夏威,等.基于气动升力的汽车底部流场改进[J].中南大学学报:自然科学版,2013,44(10):4063-4068.[2] YAN X, QIAO X, ZHAO Z M, et al. Comparative study on external flow simulation of passenger car with complex underbody and flat underbody[J]. Applied Mechanics and Materials,2013,380-384:69-72.[3] 肖能,王小碧,王伟民,等.前扰流板对机舱进气量和车辆气动阻力的影响研究[J].汽车工程,2014,36(10):1254-1257.[4] HWANG B G, LEE S, LEE E J, et al. Reduction of drag in heavy vehicles with two different types of advanced side skirts[J]. Journal of Wind Engineering & Industrial Aerodynamics,2016,155:36-46.[5] WANG H, ZHOU Y, ZOU C, et al. Aerodynamic drag reduction of an Ahmed body based on deflectors[J]. Journal of Wind Engineering & Industrial Aerodynamics,2016,148:34-44.[6] 张勇,潘正宇,谷正气,等.基于鲨鱼鳍的汽车车身仿生气动减阻研究[J].汽车工程,2017,39(9):1018-1024+1029.[7] 汪怡平,王涛,黎帅.基于自由变形技术的汽车气动减阻优化[J].机械工程学报,2017,53(9):135-143.[8] MCNALLY J, FERNANDEZ E, ROBERTSON G, et al. Drag reduction on a flat-back ground vehicle with active flow control[J]. Journal of Wind Engineering & Industrial Aerodynamics,2015,145:292-303.[9] 丁鹏,葛如海,李智,等.汽车自适应可调尾翼系统的研发[J].汽车工程,2017,39(08):895-899.[10] 王冰心,杨志刚,朱晖,等.定常喷/吸流动主动控制方法减阻研究[J].同济大学学报:自然科学版,2017,45(9):1383-1389.[11] 文琪,谷正气,黄泰明,等.基于尾气排放控制尾涡的新型减阻方法研究[J].空气动力学学报,2018,36(1):47-51.[12] 崔文诗,杨志刚,王国俊.合成射流激励频率对车辆气动阻力的影响[J].同济大学学报:自然科学版,2017,45(8):1167-1173.[13] 袁志群,谷正气,杨明智,等.底部结构对轿车侧风气动特性的影响分析[J].汽车工程,2017,39(1):28-34.[14] YUAN Z, GU Z, WANG Y, et al. Numerical investigation for the influence of the car underbody on aerodynamic force and flow structure evolution in crosswind[J]. Advances in Mechanical Engineering,2018,10(10):1-14.[15] 刘立宁,石硕,郗学峰,等.隔离带对侧风条件下超车过程车辆气动力的影响[J].汽车工程,2018,40(4):437-442.[16] 龚旭,谷正气,李振磊,等.侧风状态下轿车气动特性数值模拟方法的研究[J].汽车工程,2010,32(01):13-16.[17] 杨建国.基于离散气动系数的轿车瞬态侧风稳定性研究[J].中国机械工程,2016,27(4):549-554.[18] WANG Y. Numerical and experimental investigations on the aerodynamic characteristic of three typical passenger vehicles[J]. Journal of Applied Fluid Mechanics,2014,7(4):6859-6671.[19] 杨易,聂云,徐永康,等.车尾造型对凹坑型非光滑车身气动减阻的影响[J].汽车工程,2015,37(3):300-306.",A Study on Car Drag Reduction by Active and PassiveControl of Complex Underbody Flow Field,"aerodynamic drag,spoiler,side-skirts,underbody suction control slot,wake jet control slot,dynamic control method,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.009

In [54]:
pd.set_option("display.max_colwidth", None)
df[df["reference"] == ""]

,reference,title,keywords,link
1148,,,,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.001
1149,,,,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.002
1150,,,,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.003
1151,,,,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.004
1152,,,,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.005
...,...,...,...,...
34722,,,,https://www.qichegongcheng.com/CN/abstract/abstract17.shtml
34723,,,,https://www.qichegongcheng.com/CN/abstract/abstract18.shtml
34724,,,,https://www.qichegongcheng.com/CN/abstract/abstract19.shtml
34725,,,,https://www.qichegongcheng.com/CN/abstract/abstract20.shtml
34726,,,,https://www.qichegongcheng.com/CN/abstract/abstract21.shtml

In [55]:
df.to_csv('reference.csv',index=False)

In [57]:
import re

In [76]:
LEAD = re.compile(
    r'^(?:'
    r'[\[［(（](\d{1,4})[\]］)）]'      # 括弧付き: 区切り不要
    r'|'
    r'(\d{1,3})[.．、\s]'              # 裸の数字: 区切り必須（誤検出防止）
    r')\s*(.*)$', re.S)

def to_pairs(text):
    if not isinstance(text, str) or not text.strip():
        return []
    if len(re.findall(r'\[\d+\]\s', text)) > 1:
        parts = re.split(r'(?=\[\d+\]\s)', text)
    else:
        parts = [text]
    out = []
    for p in parts:
        p = p.strip()
        if not p:
            continue
        m = LEAD.match(p)
        if m:
            no = m.group(1) or m.group(2)   # どちらの形式でマッチしたか
            out.append((no, m.group(3).strip()))
        else:
            out.append((None, p))
    return out

df['_p'] = df['reference'].apply(to_pairs)
df = df.explode('_p', ignore_index=True)
df[['ref_no', 'reference']] = pd.DataFrame(df['_p'].tolist(), index=df.index)
df = df.drop(columns='_p')

# 番号なし＝翻訳を除去
df_dropped = df[df['ref_no'].isna()]            # 確認用に残す
df = df[df['ref_no'].notna()].reset_index(drop=True)
df['ref_no'] = df['ref_no'].astype(int)

In [77]:
len(df_dropped)

9048

In [78]:
import re
s = df_dropped['reference'].fillna("")

empty = s.str.strip() == ""
bare  = s.str.match(r'^\s*\d{1,3}[.．、\s]')     # 裸の数字で始まる＝救済すべき
rest  = ~empty & ~bare

print("空行:", empty.sum())
print("裸の数字:", bare.sum())          # 救済対象
print("翻訳など:", rest.sum())
print(df_dropped.loc[bare, 'reference'].head(5).tolist())

空行: 167
裸の数字: 0
翻訳など: 8881
[]

In [79]:
df.to_csv('reference_repaired.csv',index=False)

In [80]:
df.shape

(37879, 5)

In [81]:
df['reference'].value_counts().reset_index()

,reference,count
0,HE K， ZHANG X， REN S， et al. Deep residual learning for image recognition［C］. Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition， 2016： 770-778.,10
1,VASWANI A， SHAZEER N， PARMAR N， et al. Attention is all you need［J］. Advances in Neural Information Processing Systems， 2017， 30.,8
2,李克强， 常雪阳， 李家文， 等. 智能网联汽车云控系统及其实现［J］. 汽车工程， 2020， 42（12）： 1595-1605.,7
3,TREIBER M， HENNECKE A， HELBING D. Congested traffic states in empirical observations and microscopic simulations［J］. Physical Review E， 2000， 62（2）： 1805.,6
4,"余志生.汽车理论[M].北京:机械工业出版社,2009.",6
...,...,...
36590,廖小东，谢皎，王瑁．锰酸锂高温失效机理研究［J］．电源技术，2015，39（9）：1849-1851．,1
36591,毛国龙，刘建文，赵鹏．磷酸铁锂电池储存性能研究［J］.电源技术，2016，40（5）：971-972．,1
36592,孙智鹏，陈立铎，卜祥军. 动力电池挤压机械损伤后性能演化研究［J］.电源技术，2020，44（7）：964-966.,1
36593,李会峰，庞静，卢世刚. 锂离子电池滥用条件下的安全性研究［J］. 电源技术，2013，37（12）：2235-2238.,1
36594,郑芸菲. 锂离子电池在滥用条件下的安全性研究［J］. 船电技术， 2021，41（2）：44-47.,1

In [82]:
df.head(5)

,reference,title,keywords,link,ref_no
0,"SAVARESI S M, POUSSOT-VASSAL C, SPELTA C,et al. Semi-active suspension control design for vehicles[M]. Oxford: Elsevier,2010.",A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1
1,"GUGLIELMINO E, SIRETEANU T, STAMMERA C W, et al. Semi-active suspension control:improved vehicle ride and road friendliness[M]. London: Springer,2008.",A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,2
2,"YOKOYAMA M, HEDRICK J K, TOYAMA S. A model follow sliding mode control for semi-active suspension systems[C]. Proceedings of the American Control Conference, Arlington, VA June25-27,2001:2652 -2657.",A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,3
3,"DIXIT R, BUCKNER G. Sliding mode observation and control for semiactive vehicle suspensions[J]. Vehicle System Dynamics,2005,43(2):83-105.",A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,4
4,"CHEN B, SHIU Y, HSIEH F. Sliding-mode control for semi-active suspension with actuator dynamics[J]. Vehicle System Dynamics,2011,49(1-2):277-290.",A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,5

In [92]:
df_ad = df[df['keywords'].str.contains('autonomous driving', case=False, na=False)]

In [93]:
df_ad.shape

(2088, 5)

In [94]:
df_ad['reference'].value_counts().reset_index()

,reference,count
0,HE K， ZHANG X， REN S， et al. Deep residual learning for image recognition［C］. Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition， 2016： 770-778.,4
1,VASWANI A， SHAZEER N， PARMAR N， et al. Attention is all you need［J］. Advances in Neural Information Processing Systems， 2017， 30.,4
2,DOSOVITSKIY A， ROS G， CODEVILLA F， et al. CARLA： an open urban driving simulator［C］. Conference on Robot Learning. PMLR， 2017： 1-16.,3
3,LANG A H， VORA S， CAESAR H， et al. Pointpillars： fast encoders for object detection from point clouds［C］. Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition， 2019： 12697-12705.,3
4,BELLEMARE M G， DABNEY W， MUNOS R. A distributional perspective on reinforcement learning［C］. International Conference on Machine Learning. PMLR， 2017： 449-458.,2
...,...,...
2049,DOU J， XUE J， FANG J. SEG-VoxelNet for 3D vehicle detection from RGB and LiDAR data［C］. 2019 International Conference on Robotics and Automation （ICRA）. 2019.,1
2050,廖家才，曹立波，夏家豪，等. 基于核相关滤波和运动模型的多目标轨迹跟踪［J］. 汽车工程，2019，41（10）：1179-1188.,1
2051,HE K， ZHANG X， REN S， et al. Deep residual learning for image recognition［C］. 2016 IEEE Conference on Computer Vision and Pattern Recognition （CVPR）. IEEE， 2016.,1
2052,SUN C， SHRIVASTAVA A， SINGH S， et al. Revisiting unreasonable effectiveness of data in deep learning era［C］. IEEE Computer Society. IEEE Computer Society， 2017.,1
2053,HE Y， XU D，WU L， et al. LFFD： a light and fast face detector for edge devices［J］.arXiv Preprint，arXiv：，2019.,1

In [95]:
df_kisha=df[df['reference'].str.contains('汽车工程')]

In [97]:
df_kisha.shape

(2802, 5)

In [98]:
df_kisha

,reference,title,keywords,link,ref_no
41,"王兆文,黄荣华,成晓北,等.重型车用柴油机气缸盖内流动与传热研究[J].汽车工程,2008,30(4):312-316.",A Study on the Influence of Measurement Module on the Measurement ofFlow Through Upper Water Holes on Cylinder Block in a Diesel Engine,"upper water hole on cylinder block,flow measurement,turbine flowmeter,measurement module,test,simulation,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004,5
43,"刘福水,闵祥芬,樊丰,等.柴油机冷却水套的优化设计方法[J].汽车工程,2014,36(6):728-733.",A Study on the Influence of Measurement Module on the Measurement ofFlow Through Upper Water Holes on Cylinder Block in a Diesel Engine,"upper water hole on cylinder block,flow measurement,turbine flowmeter,measurement module,test,simulation,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004,7
52,"韩晓梅,林学东,李德刚.轻型柴油机起动过程瞬态喷油量控制策略研究[J].汽车工程,2017,39(1):23-27.",Calculation Correction of Fuel Injection Parameters at Different FuelTemperatures of High Pressure Common Rail System,"power machinery and engineering,fuel injection quantity,high pressure common rail,temperature,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005,6
53,"黄丫,林学东,段春丽,等.高压共轨柴油机起动控制策略与参数优化研究[J].汽车工程,2018,40(5):501-507.",Calculation Correction of Fuel Injection Parameters at Different FuelTemperatures of High Pressure Common Rail System,"power machinery and engineering,fuel injection quantity,high pressure common rail,temperature,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005,7
61,"金辉,李世杰.基于极限车速的车辆稳定性控制研究[J].汽车工程,2018,40(1):48-56.",A Research on Handling Stability of High-speed Unmanned Vehicles,"high-speed unmanned vehicles,vehicle dynamics,handling stability,model predictive control,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006,4
...,...,...,...,...,...
37780,鲍伟， 葛建军. 基于稀疏采样数据的电动公交车电池SOC预测方法研究［J］. 汽车工程， 2020， 42（3）：367-374.,Review of State Estimation of Lithium-ion Battery with Machine Learning,"lithium-ion battery,machine learning,SOC,SOH,RUL,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.018,19
37794,孔祥创， 赵万忠， 王春燕. 基于BP-EKF算法的锂电池SOC联合估计［J］. 汽车工程， 2017， 39（6）：648-652.,Review of State Estimation of Lithium-ion Battery with Machine Learning,"lithium-ion battery,machine learning,SOC,SOH,RUL,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.018,33
37804,潘海鸿， 吕治强， 付兵， 等. 采用极限学习机实现锂离子电池健康状态在线估算［J］. 汽车工程， 2017， 39（12）：1375-1381，1396.,Review of State Estimation of Lithium-ion Battery with Machine Learning,"lithium-ion battery,machine learning,SOC,SOH,RUL,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.018,43
37853,孙道明， 俞小莉. 随机放电工况下锂离子电池容量预测方法［J］. 汽车工程， 2020， 42（9）：1189-1196.,Review of State Estimation of Lithium-ion Battery with Machine Learning,"lithium-ion battery,machine learning,SOC,SOH,RUL,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.018,92
37872,李军求，吴朴恩，张承宁.电动汽车动力电池热管理技术的研究与实现［J］. 汽车工程，2016，38（1）.,Study on the Collision of Battery Pack Bottom Based on Traffic Accident Statistics,"battery pack,collision,typical condition,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.019,6

In [116]:
dataset_cn=[]##中国語取得用
id=1
def clean(el):
    return " ".join("".join(el.itertext()).split())

def pick_en(vals):
    if len(vals) > 1:
        return vals[1]          
    return vals[0] if vals else None 
    
def pick_cn(vals):
    if len(vals) > 1:
        return vals[0]          
    return vals[0] if vals else None

for paper in data_total:
    url=paper['link']
    print(url)
    resp = requests.get(url, headers=headers)
    if resp.status_code != 200:          
        print("errorcode200:", resp.status_code, url)
        continue
    
    tree = etree.HTML(resp.text)
    xpath_ref='//div[@id="collapseThree"]//table//tr'
    elements_ref=tree.xpath(xpath_ref)
    xpath_title = '//meta[@name="citation_title"]/@content'
    elements_title = tree.xpath(xpath_title)
    xpath_keywords = '//meta[@name="DC.Keywords"]/@content'
    elements_kewords = tree.xpath(xpath_keywords)
    xpath_date = '//meta[@name="citation_date"]/@content'
    elements_date = tree.xpath(xpath_date)

    

    for elm in elements_ref:
        
        row = {
            'reference':clean(elm),
            'title':pick_cn(elements_title),
            'title_en':pick_en(elements_title),
            'keywords': pick_en(elements_kewords),
            'date':     elements_date[0] if elements_date else None,
            'link':url,
            'paperid':id
            }
    
        dataset_cn.append(row)
    time.sleep(0.3)
    id=id+1

https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.10.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.020
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.02.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2017.01.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.ep.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.04.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.04.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.11.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.01.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.09.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.03.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.03.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.ep.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.006
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.007
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.008
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.009
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.010
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.011
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.012
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.013
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.014
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.015
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.016
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.017
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.018
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.019
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.001
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.002
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.003
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.004
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.005
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.011.006

In [118]:
dataset_cn

[{'reference': '[1] SAVARESI S M, POUSSOT-VASSAL C, SPELTA C,et al. Semi-active suspension control design for vehicles[M]. Oxford: Elsevier,2010.[2] GUGLIELMINO E, SIRETEANU T, STAMMERA C W, et al. Semi-active suspension control:improved vehicle ride and road friendliness[M]. London: Springer,2008.[3] YOKOYAMA M, HEDRICK J K, TOYAMA S. A model follow sliding mode control for semi-active suspension systems[C]. Proceedings of the American Control Conference, Arlington, VA June25-27,2001:2652 -2657.[4] DIXIT R, BUCKNER G. Sliding mode observation and control for semiactive vehicle suspensions[J]. Vehicle System Dynamics,2005,43(2):83-105.[5] CHEN B, SHIU Y, HSIEH F. Sliding-mode control for semi-active suspension with actuator dynamics[J]. Vehicle System Dynamics,2011,49(1-2):277-290.[6] FALLAH M S, BHAT R, XIE W F. H∞ robust control of semi-active Macpherson suspension system: new applied design[J]. Vehicle System Dynamics,2010,48(3):339-360.[7] DU H, ZHANG N, NAGHDY F. Robust control of vehicle electrorheologi-cal suspensnion subject to measurement noises[J]. Vehicle System Dyna-mics,2011,49(1-2):257-275.[8] TSENG H E, HEDRICK J K. Semi-active control laws-optimal and sub-optimal[J]. Vehicle System Dynamics,1994,23(1):545-569.[9] VANDERAA M A H, MUIJDERMAN J H E A, VELDPAUS F E. Constrained optimal control of semi-active suspension systems with pre-view[J]. Vehicle System Dynamics,1997,28(4-5):307-323.[10] BREZAS P, SMITH M C, HOULT W. A clipped-optimal algorithm for semi-active vehicle suspensions: theory and experimental evaluation[J]. Automatica,2015,53(3):188-194.[11] KARNOPP D C,CROSBY M J, HARWOOD R A. Vibration control using semi-active force generators[J]. ASME Journal of Engineering for Industry,1974,96(2):619-626.[12] SAMMIER D, SENAME O, DUGARD L. Skyhook and H∞ control of semi-active suspensions some practical aspects[J]. Vehicle System Dyn-amics,2003,39(4):279-308.[13] SAVARESI S M, SILANI E, BITTANTI S. Acceleration driven damper(ADD): an optimal control algorithm for comfort-oriented semiactive suspensions[J]. Journal of Dynamic Systems, Measurement, and Control,2005,127(6):218-229.[14] MORSELLI R,ZANASI R. Control of port hamiltonian systems by dissipative devices and its application to improve the semi-active suspension behavior[J]. Mechatronics,2008,18(7):364-369.[15] SAVARESI S M, SPELTA C. Mixed sky-hook and ADD:approaching the filtering limits of a semi-active suspension[J]. Journal of Dynamic Systems Measurement, and Control,2007,129(7):382-392.[16] LIU Y, ZUO L. Mixed skyhook and power-driven-damper: a new low-jerk semi-active suspension control based on power flow analysis[J]. Journal of Dynamic Systems, Measurement and Control,2016,138(8):081009-1-081009-10.[17] SPELTA C, CUTINI M, BERTINOTTI S A, et al. A new concept of semi-active suspension with controllable damper and spring[C]. Proceeding of the European Control Conference, Budapest, Hungary, August23-26,2009.[18] SPELTA C, PREVIDI F, SAVARESI S M,et al. Performance analysis of semi-active suspensions with control of variable damping and stiffness[J]. Vehicle System Dynamics,2011,49(1):237-256.[19] SANDE T P J, BESSELINK I J M, NIJMEIJER H. Rule-based control of a semi-active suspension for minimal sprung mass acceleration: design and measurement[J]. Vehicle System Dynamics,2016,54(1):281-300.[20] 郭孔辉,王杨.一种用于车辆悬架系统的智能加速度阻尼半主动控制方法:CN106515348A[P].2017-03-22.',
  'title': '一种改进的加速度阻尼半主动控制策略研究*',
  'title_en': 'A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension',
  'keywords': 'semi-active suspension,skyhook control,ADD control,whole frequency range,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001',
  'paperid': 1},
 {'reference': '[1] EEA (Energy and Environmental Analysis, Inc.) 2007. Update for advanced technologies to improve fuel economy of light duty vehicles[R]. Prepared for US Department of Energy. Arlington, Virginia, August.[2] National Research Council. Committee on the assessment of technologies for improving light-duty vehicle fuel economy 2010[R]. Assessment of Technologies for Improving Light Duty Vehicle Fuel Economy. ISBN:0-309-15608-4.[3] 中国机动车环境管理年报(2017年度)[R].北京:中华人民共和国生态环境部,2018.[4] MIKULIC I, KOELMAN H, MAJKOWSKI S, et al. A study about particle filter application on a state-of-the-art homogeneous turbocharged 2L DI gasoline engine[R]. Aachener Kolloquium,2010.[5] ZHAN R, EAKLE S, WEBER P. Simultaneous reduction of PM, HC, CO and NOx emissions from a GDI engine[C]. SAE Paper 2010-01-0365.[6] CUSTER N, PAKKO J, BOERENSEN C, et al. Lubricant-derived ash impact on gasoline particulate filter performance[C]. SAE Paper 2016-01-0942.[7] SAPPOK A, WANG Y, KAMP C, et al. Theoretical and experimental analysis of ash accumulation and mobility in ceramic exhaust particulate filters and potential for improved ash management[C]. SAE Paper 2014-01-1517.[8] SHAO H, LAM W, REMIAS J, et al. Effect of lubricating oil properties on the performance of gasoline particulate filter (GPF)[C]. SAE Paper 2016-01-2287.[9] LAMBERT C, BUMBAROSKA M, DOBSON D, et al. Analysis of high mileage gasoline exhaust particle filters[C]. SAE Paper 2016-01-0941.',
  'title': '润滑油灰分对直喷汽油车GPF性能影响的试验研究*',
  'title_en': 'An Experimental Study on the Impact of Lubricant Ash onGasoline Particle Filter Performance of GDI Vehicle',
  'keywords': 'gasoline direct injection vehicle,gasoline particulate filter (GPF),accelerated ash accumulation,worldwide harmonized light vehicles test cycle (WLTC),durability,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.002',
  'paperid': 2},
 {'reference': '[1] DURBIN T, WILSON R, NORBECK J, et al. Estimates of the emission rates of ammonia from light-duty vehicles using standard chassis dynamometer test cycles[J]. Atmospheric Environment,2002,36(9):1475-1482.[2] LIVINGSTON C, RIEGER P, WINER A. Ammonia emissions from a representative in-use fleet of light and medium-duty vehicles in the California South Coast Air Basin[J]. Atmospheric Environment,2009(43):3326-3333.[3] 董艳强,陈长虹,黄成,等.长江三角洲地区人为源氨排放清单及分布特征[J].环境科学学报,2009(8):1611-1617.[4] MENG W J, et al. Improvement of a global high-resolution ammonia emission inventory for combustion and industrial sources with new data from the residential and transportation sectors[J]. Environmental Science and Technology,2017,51(5):2821-2829.[5] HEEB N V, FORSS A M, BRUHLMANN S, et al. Three-way catalyst-induced formation of ammonia-velocity- and acceleration-dependent emission factors[J]. Atmospheric Environment,2006(40):5986-5997.[6] WANG C X, ZHENG T T, LU J, et al. Three-way catalytic reactions on Rh-based catalyst: effect of Rh/ceria interfaces[J]. Applied Catalysis A: General,2017(6):30-39.[7] HEEB N V, SAXER C J, FORSS A M, et al. Trends of NO-, NO2-, and NH3- emissions from gasoline-fueled Euro-3-to Euro-4-passenger cars[J]. Atmospheric Environment,2008(42):2543-2554.[8] HEEB N V, SAXER C J, FORSS A, et al. Correlation of hydrogen, ammonia and nitrogen monoxide (nitric oxide) emissions of gasoline-fueled Euro-3 passenger cars at transient driving[J]. Atmospheric Environment,2006(40):3750-3763.',
  'title': '基于WLTC和NEDC循环的轻型车氨排放特性研究*',
  'title_en': 'A Research on Ammonia Emission Characteristics of Light-dutyVehicles Based on WLTC and NEDC Cycles',
  'keywords': 'ammonia emission characteristics,WLTC cycle,NEDC cycle,three-way catalytic converter,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.003',
  'paperid': 3},
 {'reference': '[1] 屈盛官,夏伟,王颖,等.高强化柴油机气缸套周围冷却水流动的数值模拟和试验研究[J].内燃机工程,2004(4):32-35.[2] 郭良平,张卫正,王长园,等.柴油机气缸盖传热规律研究[J].北京理工大学学报,2011,31(3):277-282.[3] 白敏丽,吕继组,丁铁新,等.六缸柴油机冷却系统流动与传热的数值模拟研究[J].内燃机学报,2004(6):525-531.[4] 王兆文,黄荣华,成晓北,等.车用柴油机气缸盖热负荷的改善[J].华中科技大学学报:自然科学版,2008(8):99-102.[5] 王兆文,黄荣华,成晓北,等.重型车用柴油机气缸盖内流动与传热研究[J].汽车工程,2008,30(4):312-316.[6] 王兆文,赵强,陈雄,等.基于正交设计方法的气缸盖上水孔流量测量技术[J].农业机械学报,2014,45(4):42-48,21.[7] 刘福水,闵祥芬,樊丰,等.柴油机冷却水套的优化设计方法[J].汽车工程,2014,36(6):728-733.[8] 陈思南,薛冬新,周禛,等.某16缸中速柴油机冷却水系统分析与优化[J].内燃机工程,2015,36(4):133-139.[9] 陈铄,苏中地,林景殿.气体涡轮流量计流道压力损失的数值模拟[J].中国计量学院学报,2015,26(2):134-139.[10] CHEN X Q, YU X L, LU Y J, et al. Study of different cooling structures on the thermal status of an internal combustion engine[J]. Applied Thermal Engineering,2017,116:419-432.',
  'title': '测量模块对柴油机缸体上水孔流量测量的影响研究*',
  'title_en': 'A Study on the Influence of Measurement Module on the Measurement ofFlow Through Upper Water Holes on Cylinder Block in a Diesel Engine',
  'keywords': 'upper water hole on cylinder block,flow measurement,turbine flowmeter,measurement module,test,simulation,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004',
  'paperid': 4},
 {'reference': '[1] TOMISHIMA H, MATSUMOTO T, OKI M. The advanced diesel common rail system for achieving a good balance between ecology and economy[C]. SAE Paper 2008-28-0017.[2] 苏海峰,张幽彤,梁建伟.高压共轨多次喷射的温度特性[J].北京理工大学学报,2013,33(10):1027-1031.[3] 聂枝根,申立中.高压共轨柴油机燃油状态系统的研究[J].现代车用动力,2010(1):15-18.[4] SALVADOR F J, GLMERO J, CARRERS M, et al. Fuel temperature influence on the performance of a last generation common-rail diesel ballistic injector. PartⅡ[J]. Energy Conversion & Management,2016,114(4):375-394.[5] GUPTA V K, ZHANG Zhen, SUN Zongxuan. Modeling and control of a novel pressure regulation mechanism for common rail fuel injection systems[J]. Applied Mathematical Modeling,2011,35:3473-3483.[6] 韩晓梅,林学东,李德刚.轻型柴油机起动过程瞬态喷油量控制策略研究[J].汽车工程,2017,39(1):23-27.[7] 黄丫,林学东,段春丽,等.高压共轨柴油机起动控制策略与参数优化研究[J].汽车工程,2018,40(5):501-507.[8] 杨世铭,陶文铨.传热学[M].北京:高等教育出版社,2006.8.[9] 张建明,张卫刚,王亚伟.柴油高压物理特性研究[J].高压物理学报,2005,19(1):41-44.[10] CHEN Gong. Study of temperature effects on fuel injection, combustion, and emission of direct-injection diesel engine[J]. Journal of Engineering for Gas Turbines and Power,2009,113(2):1-8.[11] YANG Xiaohong, LI Wenyang. A novel theoretical approach to the temperature-viscosity for fluidic fuel[J]. Fuel,2015,153(8):85-89.',
  'title': '高压共轨系统不同温度下喷油参数修正计算*',
  'title_en': 'Calculation Correction of Fuel Injection Parameters at Different FuelTemperatures of High Pressure Common Rail System',
  'keywords': 'power machinery and engineering,fuel injection quantity,high pressure common rail,temperature,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005',
  'paperid': 5},
 {'reference': '[1] 陈慧岩,熊光明,龚建伟,等.无人驾驶汽车概论[M].北京:北京理工大学出版社,2014.[2] 陈慧岩,陈舒平,龚建伟.智能汽车横向控制方法研究综述[J].兵工学报,2017,38(6):1203-1214.[3] 陈慧岩,张玉.军用地面无人机动平台技术发展综述[J].兵工学报,2014,35(10):1696-1706.[4] 金辉,李世杰.基于极限车速的车辆稳定性控制研究[J].汽车工程,2018,40(1):48-56.[5] LIU K, GONG J, KURT A, et al. A model predictive-based approach for longitudinal control in autonomous driving with lateral interruptions[C]. IEEE International Conference on Intelligent Vehicles Symposium (IV),2017:359-364.[6] 龚建伟,姜岩,徐威.无人驾驶车辆模型预测控制[M].北京:北京理工大学出版社,2014.[7] BROWN M, ERLIEN S M, FUNKE J, et al. Collision avoidance and stabilization for autonomous vehicles in emergency scenarios[J]. IEEE Transactions on Control Systems Technology,2017,25(4):1204-1216.[8] 李静,王子涵,王宣锋.基于相平面法的制动方向稳定性分析[J].汽车工程,2014,36(8):974-979.[9] LIU K, GONG J, CHEN S, et al. Model predictive stabilization control of high-speed autonomous ground vehicles considering the effect of road topography[J]. Applied Sciences,2018,8(5):822-837.[10] PACEJKA H B. Tyre and vehicle dynamics[M]. Netherlands: Butterworth-Heinemann,2006.[11] 李玲,马力,牟宇,等.模型车轮胎侧偏刚度的参数辨识方法[J].汽车工程,2016,38(12):1508-1514,1466.[12] MATTINGLEY J, BOYD S. CVXGEN: a code generator for embedded convex optimization[J]. Optimization and Engineering,2012,13(1):1-27.[13] 余志生.汽车理论[M].北京:机械工业出版社,2007.',
  'title': '高速无人驾驶车辆的操控稳定性研究*',
  'title_en': 'A Research on Handling Stability of High-speed Unmanned Vehicles',
  'keywords': 'high-speed unmanned vehicles,vehicle dynamics,handling stability,model predictive control,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006',
  'paperid': 6},
 {'reference': '[1] WONG N, CHAMBERS C, STOL K, et al. Development of a robotic driver for autonomous vehicle following[J]. International Journal of Intelligent Systems Technologies and Applications,2010,8(1-4):276-287.[2] HIRATA N, MIZUTANI N, MATSUI H, et al. Fuel consumption in a driving test cycle by robotic driver considering system dynamics[C]. IEEE International Conference on Robotics and Automation (ICRA), Seattle, Washington, USA,2015:3374-3379.[3] CHEN G, ZHANG W G. Hierarchical coordinated control method for unmanned robot applied to automotive test[J]. IEEE Transactions on Industrial Electronics,2016,63(2):1039-1051.[4] CHEN G, ZHANG W G. Digital prototyping design of electromagnetic unmanned robot applied to automotive test[J]. Robotics and Computer-Integrated Manufacturing,2015,32:54-64.[5] 牛喆,牛志刚.汽车驾驶机器人换挡机械手运动仿真分析[J].中国农机化学报,2013,34(4):197-200.[6] 黄开胜,张尧,卓晴.一种汽车自动驾驶机器人:201410174404.2[P].2014-04-28.[7] 石柱,张文俊,胡可凡,等.自动驾驶机器人:201110247651.7[P].2011-08-25.[8] 陈弘,李伟,乔胜华.用于汽车试验的驾驶机器人:201110264909.4[P].2011-9-7.[9] 卢伟,陈浩,王玲,等.拖拉机驾驶机器人换挡机械手运动分析[J].农业机械学报,2016,47(1):37-44.[10] 陈刚,张为公.基于模糊自适应PID的汽车驾驶机器人的车速控制[J].汽车工程,2012,34(6):511-516.[11] 佘致廷,袁俊波,李英,等.基于模糊PI控制策略的电动汽车无离合器两挡变速控制[J].汽车工程,2012,34(11):976-980.[12] 陈刚,张为公.汽车驾驶机器人车速跟踪神经网络控制方法[J].中国机械工程,2012,23(2):240-243.[13] 袁安富,伏俊杰.驾驶机器人油门机械腿模糊自整定PID控制方法[J].自动化与仪表,2013,28(3):5-9.[14] 刘坤明,徐国艳,余贵珍.驾驶机器人机械腿动力学建模与仿真分析[J].北京航空航天大学学报,2016,42(8):1709-1714.[15] 毕翔,韩江洪,刘征宇.模糊离散事件系统的自适应监督控制[J].仪器仪表学报,2013,4(10):2170-2176.[16] 郭瑜.半监督迭代模糊聚类模型及其在中长期水文预报中的应用[J].东南大学学报:自然科学版,2013,43:59-62.[17] 国家环境保护总局.轻型汽车污染物排放限值及测量方法(中国Ⅲ、Ⅳ阶段):GB 18352.3—2005[S].北京:中国标准出版社,2005.[18] 詹兴泉.车用催化转化器评价技术及耐久试验方法间相关性研究[D].武汉:武汉理工大学,2002.',
  'title': '无人驾驶机器人机械腿模糊监督控制*',
  'title_en': 'Fuzzy Supervisory Control of Mechanical Legs of Unmanned Robots',
  'keywords': 'unmanned robot,dynamic model,fuzzy supervisory control,stability,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007',
  'paperid': 7},
 {'reference': '[1] 吴光强,栾文博.汽车传动系相关NVH问题的动力学研究论述[J].机械工程学报,2013,49(24):108-116.[2] 高炳钊,洪金龙,陈虹.汽车传动系统平顺性驾驶品质控制[J].控制理论与应用,2017,34(7):849-866.[3] COUDERC P, CALLENAERE J. Vehicle driveline dynamic behaviour: experimentation and simulation[J]. Journal of Sound & Vibration,1998,218(1):133-157.[4] FARSHIDIANFAR A, EBRAHIMI M, BARTLETT H. Hybrid modelling and simulation of the torsional vibration of vehicle driveline systems[J]. Proceedings of the Institution of Mechanical Engineers, Part D: Journal of Automobile Engineering,2003,215(2):217-229.[5] FARSHIDIANFAR A, EBRAHIMI M, BARTLETT H, et al. Driveline shuffle in rear wheel vehicles[J]. International Journal of Heavy Vehicle Systems,2002,9(1):76-91.[6] BARTRAM M, MAVROS G, BIGGS S. A study on the effect of road friction on driveline vibrations[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2010,224(4):321-340.[7] FARSHIDIANFAR A, EBRAHIMI M, RAH-NEJAT H, et al. Optimization of the high-frequency torsional vibration of vehicle driveline systems using genetic algorithms[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2002,216(3):249-262.[8] GKINIS T, RAHMANI R, RAHNEJAT H. Effect of clutch lining frictional characteristics on take-up judder[J]. Proceedings of the Institution of Mechanical Engineers, Part K: Journal of Multi-body Dynamics,2017,31(3):493-503.[9] 徐红亮,龚宪生,廉超,等.新型汽车扭振减振器扭振特性试验研究[J].振动与冲击,2013,32(6):29-32.[10] 李亚南,郝志勇,郑旭,等.基于解决发动机加速异响问题的TVD分析优化[J].振动与冲击,2018,37(6):86-91.[11] YANG X S. Firefly algorithms for multimodal optimization[J]. Mathematics,2012,5792:169-178.[12] YANG X S, HE X. Firefly algorithm: recent advances and applications[J]. International Journal of Swarm Intelligence,2013,1(1):36-50.[13] FISTER I, JR I F, YANG X S, et al. A comprehensive review of firefly algorithms[J]. Swarm & Evolutionary Computation,2013,13:34-46.[14] GARCIAGONZALO E, FERNANDEZLUNA J, MARTINEZ J A. A brief historical review of particle swarm optimization (PSO)[J]. Journal of Bioinformatics & Intelligent Control,2012,1(1):3-16.[15] KENNEDY J. Particle swarm optimization[C]. Proc. of 1995 IEEE Int. Conf. Neural Networks,Perth, Australia, Nov.27-1995.[16] EBERHART R C, SHI Y. Particle swarm optimization: developments, applications and resources[C]. Congress on Evolutionary Computation. IEEE,2001.',
  'title': '汽车传动系激励转矩波动估计与扭振性能调校*',
  'title_en': 'Estimation of Excitation Torque Fluctuation and Torsional VibrationPerformance Adjustment of Automobile Transmission System',
  'keywords': 'transmission system,parameter estimation,torque fluctuation,torsional vibration test,order analysis,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.008',
  'paperid': 8},
 {'reference': '[1] 杨易,徐永康,沈夏威,等.基于气动升力的汽车底部流场改进[J].中南大学学报:自然科学版,2013,44(10):4063-4068.[2] YAN X, QIAO X, ZHAO Z M, et al. Comparative study on external flow simulation of passenger car with complex underbody and flat underbody[J]. Applied Mechanics and Materials,2013,380-384:69-72.[3] 肖能,王小碧,王伟民,等.前扰流板对机舱进气量和车辆气动阻力的影响研究[J].汽车工程,2014,36(10):1254-1257.[4] HWANG B G, LEE S, LEE E J, et al. Reduction of drag in heavy vehicles with two different types of advanced side skirts[J]. Journal of Wind Engineering & Industrial Aerodynamics,2016,155:36-46.[5] WANG H, ZHOU Y, ZOU C, et al. Aerodynamic drag reduction of an Ahmed body based on deflectors[J]. Journal of Wind Engineering & Industrial Aerodynamics,2016,148:34-44.[6] 张勇,潘正宇,谷正气,等.基于鲨鱼鳍的汽车车身仿生气动减阻研究[J].汽车工程,2017,39(9):1018-1024+1029.[7] 汪怡平,王涛,黎帅.基于自由变形技术的汽车气动减阻优化[J].机械工程学报,2017,53(9):135-143.[8] MCNALLY J, FERNANDEZ E, ROBERTSON G, et al. Drag reduction on a flat-back ground vehicle with active flow control[J]. Journal of Wind Engineering & Industrial Aerodynamics,2015,145:292-303.[9] 丁鹏,葛如海,李智,等.汽车自适应可调尾翼系统的研发[J].汽车工程,2017,39(08):895-899.[10] 王冰心,杨志刚,朱晖,等.定常喷/吸流动主动控制方法减阻研究[J].同济大学学报:自然科学版,2017,45(9):1383-1389.[11] 文琪,谷正气,黄泰明,等.基于尾气排放控制尾涡的新型减阻方法研究[J].空气动力学学报,2018,36(1):47-51.[12] 崔文诗,杨志刚,王国俊.合成射流激励频率对车辆气动阻力的影响[J].同济大学学报:自然科学版,2017,45(8):1167-1173.[13] 袁志群,谷正气,杨明智,等.底部结构对轿车侧风气动特性的影响分析[J].汽车工程,2017,39(1):28-34.[14] YUAN Z, GU Z, WANG Y, et al. Numerical investigation for the influence of the car underbody on aerodynamic force and flow structure evolution in crosswind[J]. Advances in Mechanical Engineering,2018,10(10):1-14.[15] 刘立宁,石硕,郗学峰,等.隔离带对侧风条件下超车过程车辆气动力的影响[J].汽车工程,2018,40(4):437-442.[16] 龚旭,谷正气,李振磊,等.侧风状态下轿车气动特性数值模拟方法的研究[J].汽车工程,2010,32(01):13-16.[17] 杨建国.基于离散气动系数的轿车瞬态侧风稳定性研究[J].中国机械工程,2016,27(4):549-554.[18] WANG Y. Numerical and experimental investigations on the aerodynamic characteristic of three typical passenger vehicles[J]. Journal of Applied Fluid Mechanics,2014,7(4):6859-6671.[19] 杨易,聂云,徐永康,等.车尾造型对凹坑型非光滑车身气动减阻的影响[J].汽车工程,2015,37(3):300-306.',
  'title': '汽车底部复杂流场的主动和被动控制减阻方法研究*',
  'title_en': 'A Study on Car Drag Reduction by Active and PassiveControl of Complex Underbody Flow Field',
  'keywords': 'aerodynamic drag,spoiler,side-skirts,underbody suction control slot,wake jet control slot,dynamic control method,',
  'date': '2019-06-05',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.009',
  'paperid': 9},

In [119]:
df_cn = pd.DataFrame(dataset_cn)

In [120]:
df_cn.shape

(39057, 7)

In [121]:
def to_pairs(text):
    if not isinstance(text, str) or not text.strip():
        return []
    if len(re.findall(r'\[\d+\]\s', text)) > 1:
        parts = re.split(r'(?=\[\d+\]\s)', text)
    else:
        parts = [text]
    out = []
    for p in parts:
        p = p.strip()
        if not p:
            continue
        m = LEAD.match(p)
        if m:
            no = m.group(1) or m.group(2)   # どちらの形式でマッチしたか
            out.append((no, m.group(3).strip()))
        else:
            out.append((None, p))
    return out

df_cn['_p'] = df_cn['reference'].apply(to_pairs)
df_cn = df_cn.explode('_p', ignore_index=True)
df_cn[['ref_no', 'reference']] = pd.DataFrame(df_cn['_p'].tolist(), index=df_cn.index)
df_cn = df_cn.drop(columns='_p')

# 番号なし＝翻訳を除去
df_dropped = df_cn[df_cn['ref_no'].isna()]            # 確認用に残す
df_cn = df_cn[df_cn['ref_no'].notna()].reset_index(drop=True)
df_cn['ref_no'] = df_cn['ref_no'].astype(int)

In [122]:
len(df_dropped)

9048

In [170]:
df_cn.to_csv('reference_repaired_cn.csv',index=False)

In [124]:
df_kisha_cn=df_cn[df_cn['reference'].str.contains('汽车工程')]

In [125]:
df_kisha_cn.head(10)

,reference,title,title_en,keywords,date,link,paperid,ref_no
41,"王兆文,黄荣华,成晓北,等.重型车用柴油机气缸盖内流动与传热研究[J].汽车工程,2008,30(4):312-316.",测量模块对柴油机缸体上水孔流量测量的影响研究*,A Study on the Influence of Measurement Module on the Measurement ofFlow Through Upper Water Holes on Cylinder Block in a Diesel Engine,"upper water hole on cylinder block,flow measurement,turbine flowmeter,measurement module,test,simulation,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004,4,5
43,"刘福水,闵祥芬,樊丰,等.柴油机冷却水套的优化设计方法[J].汽车工程,2014,36(6):728-733.",测量模块对柴油机缸体上水孔流量测量的影响研究*,A Study on the Influence of Measurement Module on the Measurement ofFlow Through Upper Water Holes on Cylinder Block in a Diesel Engine,"upper water hole on cylinder block,flow measurement,turbine flowmeter,measurement module,test,simulation,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.004,4,7
52,"韩晓梅,林学东,李德刚.轻型柴油机起动过程瞬态喷油量控制策略研究[J].汽车工程,2017,39(1):23-27.",高压共轨系统不同温度下喷油参数修正计算*,Calculation Correction of Fuel Injection Parameters at Different FuelTemperatures of High Pressure Common Rail System,"power machinery and engineering,fuel injection quantity,high pressure common rail,temperature,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005,5,6
53,"黄丫,林学东,段春丽,等.高压共轨柴油机起动控制策略与参数优化研究[J].汽车工程,2018,40(5):501-507.",高压共轨系统不同温度下喷油参数修正计算*,Calculation Correction of Fuel Injection Parameters at Different FuelTemperatures of High Pressure Common Rail System,"power machinery and engineering,fuel injection quantity,high pressure common rail,temperature,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.005,5,7
61,"金辉,李世杰.基于极限车速的车辆稳定性控制研究[J].汽车工程,2018,40(1):48-56.",高速无人驾驶车辆的操控稳定性研究*,A Research on Handling Stability of High-speed Unmanned Vehicles,"high-speed unmanned vehicles,vehicle dynamics,handling stability,model predictive control,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006,6,4
65,"李静,王子涵,王宣锋.基于相平面法的制动方向稳定性分析[J].汽车工程,2014,36(8):974-979.",高速无人驾驶车辆的操控稳定性研究*,A Research on Handling Stability of High-speed Unmanned Vehicles,"high-speed unmanned vehicles,vehicle dynamics,handling stability,model predictive control,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006,6,8
68,"李玲,马力,牟宇,等.模型车轮胎侧偏刚度的参数辨识方法[J].汽车工程,2016,38(12):1508-1514,1466.",高速无人驾驶车辆的操控稳定性研究*,A Research on Handling Stability of High-speed Unmanned Vehicles,"high-speed unmanned vehicles,vehicle dynamics,handling stability,model predictive control,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.006,6,11
80,"陈刚,张为公.基于模糊自适应PID的汽车驾驶机器人的车速控制[J].汽车工程,2012,34(6):511-516.",无人驾驶机器人机械腿模糊监督控制*,Fuzzy Supervisory Control of Mechanical Legs of Unmanned Robots,"unmanned robot,dynamic model,fuzzy supervisory control,stability,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007,7,10
81,"佘致廷,袁俊波,李英,等.基于模糊PI控制策略的电动汽车无离合器两挡变速控制[J].汽车工程,2012,34(11):976-980.",无人驾驶机器人机械腿模糊监督控制*,Fuzzy Supervisory Control of Mechanical Legs of Unmanned Robots,"unmanned robot,dynamic model,fuzzy supervisory control,stability,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.007,7,11
107,"肖能,王小碧,王伟民,等.前扰流板对机舱进气量和车辆气动阻力的影响研究[J].汽车工程,2014,36(10):1254-1257.",汽车底部复杂流场的主动和被动控制减阻方法研究*,A Study on Car Drag Reduction by Active and PassiveControl of Complex Underbody Flow Field,"aerodynamic drag,spoiler,side-skirts,underbody suction control slot,wake jet control slot,dynamic control method,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.009,9,3

In [114]:
df_ad_cn = df_cn[df_cn['keywords'].str.contains('autonomous driving', case=False, na=False)]

In [115]:
df_ad_cn

,reference,title,keywords,link,paperid,ref_no
452,BEHLEY J， GARBADE M， MILIOTO A， et al. SemanticKITTI： a dataset for semantic scene understanding of LIDAR sequences［C］. 2019 IEEE/CVF International Conference on Computer Vision. IEEE， 2019： 9297-9307.,基于三维锥形栅格的激光点云语义分割方法,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,1
453,CAESAR H， BANKITI V， LANG A H， et al. nuScenes： a multimodal dataset for autonomous driving［C］. 2020 IEEE/CVF International Conference on Computer Vision. IEEE， 2020： 11621-11631.,基于三维锥形栅格的激光点云语义分割方法,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,2
454,HACKEL T， SAVINOV N， LADICKY L， et al. Semantic3d. net： a new large-scale point cloud classification benchmark［J］. ISPRS Annals of Photogrammetry， Remote Sensing and Spatial Information Sciences， 2017， IV-1/W1： 91–98.,基于三维锥形栅格的激光点云语义分割方法,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,3
455,WU B， WAN A， YUE X， et al. SqueezeSeg： convolutional neural nets with recurrent CRF for real-time road-object segmentation from 3D LIDAR point cloud［C］. 2018 IEEE International Conference on Robotics and Automation （ICRA）. IEEE， 2018： 1887-1893.,基于三维锥形栅格的激光点云语义分割方法,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,4
456,WU B， ZHOU X， ZHAO S， et al. SqueezeSegV2： improved model structure and unsupervised domain adaptation for road-object segmentation from a LIDAR point cloud［C］. 2019 International Conference on Robotics and Automation （ICRA）. IEEE， 2019： 4376-4382.,基于三维锥形栅格的激光点云语义分割方法,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,5
...,...,...,...,...,...,...
37525,DOU J， XUE J， FANG J. SEG-VoxelNet for 3D vehicle detection from RGB and LiDAR data［C］. 2019 International Conference on Robotics and Automation （ICRA）. 2019.,基于特征融合的多层次多模态目标检测,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,12
37526,廖家才，曹立波，夏家豪，等. 基于核相关滤波和运动模型的多目标轨迹跟踪［J］. 汽车工程，2019，41（10）：1179-1188.,基于特征融合的多层次多模态目标检测,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,13
37527,HE K， ZHANG X， REN S， et al. Deep residual learning for image recognition［C］. 2016 IEEE Conference on Computer Vision and Pattern Recognition （CVPR）. IEEE， 2016.,基于特征融合的多层次多模态目标检测,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,14
37528,SUN C， SHRIVASTAVA A， SINGH S， et al. Revisiting unreasonable effectiveness of data in deep learning era［C］. IEEE Computer Society. IEEE Computer Society， 2017.,基于特征融合的多层次多模态目标检测,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,15
37529,HE Y， XU D，WU L， et al. LFFD： a light and fast face detector for edge devices［J］.arXiv Preprint，arXiv：，2019.,基于特征融合的多层次多模态目标检测,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,16

In [135]:
MARK = re.compile(r'[\[［]([A-Z]{1,2})[\]］]')

def parse(s):
    if not isinstance(s, str):
        return (None, None, None, None)
    m = MARK.search(s)
    if not m:
        return (None, None, None, None)
    head = s[:m.start()]                       # 著者＋タイトル
    tail = s[m.end():].lstrip('.． ')           # 掲載誌以降
    # headの「最後の」ピリオドで分割。イニシャルのピリオドは著者側に残る
    parts = re.split(r'[.．](?!.*[.．])', head, maxsplit=1)
    if len(parts) == 2:
        return (parts[0].strip(), parts[1].strip(), m.group(1), tail.strip())
    return (None, head.strip(), m.group(1), tail.strip())

df_cn[['ref_author', 'ref_title', 'ref_type', 'ref_journal']] = pd.DataFrame(
    df_cn['reference'].apply(parse).tolist(), index=df_cn.index)

In [136]:
df_cn.head(20)

,reference,title,title_en,keywords,date,link,paperid,ref_no,ref_author,ref_title,ref_journal,ref_type
0,"SAVARESI S M, POUSSOT-VASSAL C, SPELTA C,et al. Semi-active suspension control design for vehicles[M]. Oxford: Elsevier,2010.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,1,"SAVARESI S M, POUSSOT-VASSAL C, SPELTA C,et al",Semi-active suspension control design for vehicles,"Oxford: Elsevier,2010.",M
1,"GUGLIELMINO E, SIRETEANU T, STAMMERA C W, et al. Semi-active suspension control:improved vehicle ride and road friendliness[M]. London: Springer,2008.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,2,"GUGLIELMINO E, SIRETEANU T, STAMMERA C W, et al",Semi-active suspension control:improved vehicle ride and road friendliness,"London: Springer,2008.",M
2,"YOKOYAMA M, HEDRICK J K, TOYAMA S. A model follow sliding mode control for semi-active suspension systems[C]. Proceedings of the American Control Conference, Arlington, VA June25-27,2001:2652 -2657.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,3,"YOKOYAMA M, HEDRICK J K, TOYAMA S",A model follow sliding mode control for semi-active suspension systems,"Proceedings of the American Control Conference, Arlington, VA June25-27,2001:2652 -2657.",C
3,"DIXIT R, BUCKNER G. Sliding mode observation and control for semiactive vehicle suspensions[J]. Vehicle System Dynamics,2005,43(2):83-105.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,4,"DIXIT R, BUCKNER G",Sliding mode observation and control for semiactive vehicle suspensions,"Vehicle System Dynamics,2005,43(2):83-105.",J
4,"CHEN B, SHIU Y, HSIEH F. Sliding-mode control for semi-active suspension with actuator dynamics[J]. Vehicle System Dynamics,2011,49(1-2):277-290.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,5,"CHEN B, SHIU Y, HSIEH F",Sliding-mode control for semi-active suspension with actuator dynamics,"Vehicle System Dynamics,2011,49(1-2):277-290.",J
5,"FALLAH M S, BHAT R, XIE W F. H∞ robust control of semi-active Macpherson suspension system: new applied design[J]. Vehicle System Dynamics,2010,48(3):339-360.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,6,"FALLAH M S, BHAT R, XIE W F",H∞ robust control of semi-active Macpherson suspension system: new applied design,"Vehicle System Dynamics,2010,48(3):339-360.",J
6,"DU H, ZHANG N, NAGHDY F. Robust control of vehicle electrorheologi-cal suspensnion subject to measurement noises[J]. Vehicle System Dyna-mics,2011,49(1-2):257-275.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,7,"DU H, ZHANG N, NAGHDY F",Robust control of vehicle electrorheologi-cal suspensnion subject to measurement noises,"Vehicle System Dyna-mics,2011,49(1-2):257-275.",J
7,"TSENG H E, HEDRICK J K. Semi-active control laws-optimal and sub-optimal[J]. Vehicle System Dynamics,1994,23(1):545-569.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,8,"TSENG H E, HEDRICK J K",Semi-active control laws-optimal and sub-optimal,"Vehicle System Dynamics,1994,23(1):545-569.",J
8,"VANDERAA M A H, MUIJDERMAN J H E A, VELDPAUS F E. Constrained optimal control of semi-active suspension systems with pre-view[J]. Vehicle System Dynamics,1997,28(4-5):307-323.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,9,"VANDERAA M A H, MUIJDERMAN J H E A, VELDPAUS F E",Constrained optimal control of semi-active suspension systems with pre-view,"Vehicle System Dynamics,1997,28(4-5):307-323.",J
9,"BREZAS P, SMITH M C, HOULT W. A clipped-optimal algorithm for semi-active vehicle suspensions: theory and experimental evaluation[J]. Automatica,2015,53(3):188-194.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,10,"BREZAS P, SMITH M C, HOULT W",A clipped-optimal algorithm for semi-active vehicle suspensions: theory and experimental evaluation,"Automatica,2015,53(3):188-194.",J
10,"KARNOPP D C,CROSBY M J, HARWOOD R A. Vibration control using semi-active force generators[J]. ASME Journal of Engineering for Industry,1974,96(2):619-626.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,11,"KARNOPP D C,CROSBY M J, HARWOOD R A",Vibration control using semi-active force generators,"ASME Journal of Engineering for Industry,1974,96(2):619-626.",J
11,"SAMMIER D, SENAME O, DUGARD L. Skyhook and H∞ control of semi-active suspensions some practical aspects[J]. Vehicle System Dyn-amics,2003,39(4):279-308.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,12,"SAMMIER D, SENAME O, DUGARD L",Skyhook and H∞ control of semi-active suspensions some practical aspects,"Vehicle System Dyn-amics,2003,39(4):279-308.",J
12,"SAVARESI S M, SILANI E, BITTANTI S. Acceleration driven damper(ADD): an optimal control algorithm for comfort-oriented semiactive suspensions[J]. Journal of Dynamic Systems, Measurement, and Control,2005,127(6):218-229.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,13,"SAVARESI S M, SILANI E, BITTANTI S",Acceleration driven damper(ADD): an optimal control algorithm for comfort-oriented semiactive suspensions,"Journal of Dynamic Systems, Measurement, and Control,2005,127(6):218-229.",J
13,"MORSELLI R,ZANASI R. Control of port hamiltonian systems by dissipative devices and its application to improve the semi-active suspension behavior[J]. Mechatronics,2008,18(7):364-369.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,14,"MORSELLI R,ZANASI R",Control of port hamiltonian systems by dissipative devices and its application to improve the semi-active suspension behavior,"Mechatronics,2008,18(7):364-369.",J
14,"SAVARESI S M, SPELTA C. Mixed sky-hook and ADD:approaching the filtering limits of a semi-active suspension[J]. Journal of Dynamic Systems Measurement, and Control,2007,129(7):382-392.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,15,"SAVARESI S M, SPELTA C",Mixed sky-hook and ADD:approaching the filtering limits of a semi-active suspension,"Journal of Dynamic Systems Measurement, and Control,2007,129(7):382-392.",J
15,"LIU Y, ZUO L. Mixed skyhook and power-driven-damper: a new low-jerk semi-active suspension control based on power flow analysis[J]. Journal of Dynamic Systems, Measurement and Control,2016,138(8):081009-1-081009-10.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,16,"LIU Y, ZUO L",Mixed skyhook and power-driven-damper: a new low-jerk semi-active suspension control based on power flow analysis,"Journal of Dynamic Systems, Measurement and Control,2016,138(8):081009-1-081009-10.",J
16,"SPELTA C, CUTINI M, BERTINOTTI S A, et al. A new concept of semi-active suspension with controllable damper and spring[C]. Proceeding of the European Control Conference, Budapest, Hungary, August23-26,2009.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,17,"SPELTA C, CUTINI M, BERTINOTTI S A, et al",A new concept of semi-active suspension with controllable damper and spring,"Proceeding of the European Control Conference, Budapest, Hungary, August23-26,2009.",C
17,"SPELTA C, PREVIDI F, SAVARESI S M,et al. Performance analysis of semi-active suspensions with control of variable damping and stiffness[J]. Vehicle System Dynamics,2011,49(1):237-256.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,18,"SPELTA C, PREVIDI F, SAVARESI S M,et al",Performance analysis of semi-active suspensions with control of variable damping and stiffness,"Vehicle System Dynamics,2011,49(1):237-256.",J
18,"SANDE T P J, BESSELINK I J M, NIJMEIJER H. Rule-based control of a semi-active suspension for minimal sprung mass acceleration: design and measurement[J]. Vehicle System Dynamics,2016,54(1):281-300.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,19,"SANDE T P J, BESSELINK I J M, NIJMEIJER H",Rule-based control of a semi-active suspension for minimal sprung mass acceleration: design and measurement,"Vehicle System Dynamics,2016,54(1):281-300.",J
19,"郭孔辉,王杨.一种用于车辆悬架系统的智能加速度阻尼半主动控制方法:CN106515348A[P].2017-03-22.",一种改进的加速度阻尼半主动控制策略研究*,A Study on Modified Acceleration-driven DampingControl Strategy for Semi-active Suspension,"semi-active suspension,skyhook control,ADD control,whole frequency range,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.001,1,20,"郭孔辉,王杨",一种用于车辆悬架系统的智能加速度阻尼半主动控制方法:CN106515348A,2017-03-22.,P

In [141]:
print("抽出失敗:", df_cn['ref_type'].isna().sum(), "/", len(df_cn))
print(df_cn[['ref_author', 'ref_title']].sample(15).to_string(max_colwidth=45))

抽出失敗: 868 / 37879
                                ref_author                                     ref_title
30132        ELBANHAWI M， SIMIC M， JAZAR R  In the passenger seat： investigating ride...
25763             AKHTAR M T， MITSUHASHI W  A modified normalized FXLMS algorithm for...
35228          TAN D H S， MENG Y S， JANG J  Scaling up high-energy-density sulfidic s...
18526                                  吴飞腾                              基于深度学习的锂电池寿命预测方法
27452                                  NaN                                           NaN
28714  KHOYGANI M R， GHASEMI R， GHAYOOMI P  Robust observer-based control of nonlinea...
11401                              程小平， 秦健                     基于非线性模型预测控制的轮边电驱动客车驱动防滑研究
13779          FENG J， WANG C， XU C， et al  Active collision avoidance strategy consi...
8955                      李升波， 占国建， 蒋宇轩， 等                            类脑学习型自动驾驶决控系统的关键技术
15975                                张健， 等                           正面25%偏置碰撞中车轮铰链失效的研究
1626     VAHIDI A, STEFANOPOULOU A, PENG H  Recursive least squares with forgetting f...
14259                         罗际炜， 瞿涛， 邓徳祥                          嵌入式多通道无线视频传输的码率自适应算法
28108      DHILLON I S, MALLELA S, KUMAR R  A divisive information-theoretic feature ...
20706                          黄鹤，胡凯益，宋京，等                               雾霾线求解透射率的二次优化方法
23778                        陈君毅，刘镇源，杨雪珠，等                             感知系统触发条件穿透率评估方法研究

In [142]:
print(df_cn[df_cn['ref_type'].isna()]['reference'].head(15).tolist())

['国务院办公厅. 新能源汽车产业发展规划（2021-2035年）［EB/OL］. 2020-11-02. http：//www.gov.cn/zhengce/content/2020-11/02/content_5556716.htm.', '王燕军， 穆劲松， 吉喆， 等. 我国重型柴油货车黑碳排放影响因素分析［J/OL］. 环境科学研究： 1-11［2022-04-29］.', 'UniVehicle. UniTruck模型的优势［EB/OL］.上海： Bilibili， 2024-07-23［2024-08-09］.https：//www.bilibili.com/video/BV1p M8ieuEGt.', 'UniVehicle. UniTruck软件介绍［EB/OL］.上海： Bilibili， 2024-07-22［2024-08-09］.https：//www.bilibili.com/video/BV1YD8teq E1g.', 'UniVehicle. UniTruck仿真制动抖振_行车振动_驾驶体感_等动画演示视频［EB/OL］.上海： Bilibili， 2024-07-24［2024-08-09］. https：//www.bilibili.com/video/BV1S9eDeBEKR.', 'BAE I， MOON J， JHUNG J， et al. Self-driving like a human driver instead of a robocar： personalized comfortable driving experience for autonomous vehicles ［DB/OL］. （2022-11-18）. https：//arxiv.org/abs/2001.03908.', 'THOR-AV 50M dummy FE model LS-DYNA release version 0.6 technical report and user’s manual［EB/OL］. https：//www. humaneticsgroup. com/products/virtual-models/av-atd-virtual-models/thor-av-50m-fe.', 'TOYOTA Motor Corporation. Total human model for safety （THUMS）［EB/OL］. 2021. http：//www.lstc.com/thums.', '中国软件评测中心.车载智能计算基础平台参考架构1.0[R/OL].(2019-05)[2019-07-01].http://www.cstc.org.cn/filespath/files/20190625100742.pdf.', '中国电动汽车百人会.电动汽车安全性报告[EB/OL].[2016-08-23].http://www.chinabuses.com/tech/2016/0823/article_73404.html.', '国务院.国务院关于印发《中国制造2025》的通知[EB/OL]. http://www.miit.gov.cn/n973401/n1234620/n1234622/c4409653/content.html,2015-04-20.', '工信部.2018年汽车工业经济运行情况[EB/OL]. http://www.miit.gov.cn/n1146312/n1146904/n1648362/n1648363/c6600517/content.html.', '于艳君， 崔明恺， 陈叹辞，等. 基于模糊自适应速度调节器的绕组切换型电机控制［J/OL］.中国电机工程学报， 2021.', 'U.S. Energy Information Administration （EIA）. U.S. energy-related carbon dioxide emissions， 2019［EB/OL］. U.S. Energy Information Administration （EIA），2020-09-30.（2020-09-30）［2021-10-29］ .https：//www.eia.gov/environment/emissions/carbon/.', 'FACT SHEET： Biden administration advances the future of sustainable fuels in american aviation ［EB/OL］. The White House， 2021-09-09. （2021-09-09）［2021-10-29］ .https：//www.whitehouse.gov/briefing-room/statements-releases/2021/09/09/fact-sheet-biden-administration-advances-the-future-of-sustainable-fuels-in-american-aviation/.']

In [143]:
df_ad_cn = df_cn[df_cn['keywords'].str.contains('autonomous driving', case=False, na=False)]

In [145]:
import re, unicodedata

In [151]:
def norm(s):
    if not isinstance(s, str):
        return None
    s = unicodedata.normalize("NFKC", s)   # 全角英数・全角記号を半角へ統一
    s = re.sub(r'\s+', '', s)              # 空白を全除去
    return s.strip('.．,，').lower()

corpus = set(df_cn['title'].map(norm).dropna())    # 収録論文のタイトル集合
df_ad_cn['ref_title_n'] = df_ad_cn['ref_title'].map(norm)
df_ad_cn['is_internal'] = df_ad_cn['ref_title_n'].isin(corpus)

In [152]:
counts = (df_ad_cn[df_ad_cn['is_internal']]
          .groupby('ref_title_n')['link'].nunique()      # 引用元論文数で数える
          .sort_values(ascending=False))
print(counts.head(20))

ref_title_n
基于激光雷达的3d实时车辆跟踪                           3
基于多传感器信息融合的3维目标实时检测                       3
polardet:基于位置与语义信息加权的极坐标bev端到端3d目标检测算法    2
基于多尺度掩码分类域自适应网络的跨域目标检测算法                  2
基于检测的高效自动驾驶实例分割方法                         2
基于级联yolov7的自动驾驶三维目标检测                     2
基于residualbilstm网络的车辆切入意图预测研究             2
仿驾驶员ddpg汽车纵向自动驾驶决策方法                      2
基于实例分割的车道线检测算法                            2
类脑学习型自动驾驶决控系统的关键技术                        1
考虑主观认知的自动驾驶汽车序贯博弈类人决策                     1
考虑信号灯和能耗的电动车最优路径规划                        1
自动驾驶多传感器融合的时间校准方法研究                       1
考虑复杂扰动的轻型商用车路径跟踪混合控制方法                    1
考虑时变参考和转向延迟的自动驾驶车辆轨迹跟踪控制方法                1
考虑路径平滑性和避撞稳定性的智能汽车弯道轨迹规划研究                1
考虑车辆运动约束的最优避障轨迹规划算法                       1
社会性驾驶交互关键效用析取与应用                          1
汽车发动机噪声主动控制系统实验研究                         1
自动驾驶仿真多逻辑场景综合评价方法                         1
Name: link, dtype: int64

In [155]:
print("内部引用:", df_ad_cn['is_internal'].sum(), "/", len(df_ad_cn))
print("引用された収録論文数:", df_ad_cn.loc[df_ad_cn['is_internal'], 'ref_title_n'].nunique(),
      "/ 収録論文数:", len(corpus))

内部引用: 76 / 2088
引用された収録論文数: 65 / 収録論文数: 1740

In [158]:
df_ad_cn_kisha=df_ad_cn[df_ad_cn['ref_journal'].str.contains('汽车工程')]

In [163]:
df_kisha.shape

(2802, 5)

In [164]:
df_ad_cn_kisha.shape

(115, 14)

In [166]:
df_ad_cn

,reference,title,title_en,keywords,date,link,paperid,ref_no,ref_author,ref_title,ref_journal,ref_type,ref_title_n,is_internal
452,BEHLEY J， GARBADE M， MILIOTO A， et al. SemanticKITTI： a dataset for semantic scene understanding of LIDAR sequences［C］. 2019 IEEE/CVF International Conference on Computer Vision. IEEE， 2019： 9297-9307.,基于三维锥形栅格的激光点云语义分割方法,Semantic Segmentation Method of LiDAR Point Cloud Based on 3D Conical Grid,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",2022-08-25,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,1,BEHLEY J， GARBADE M， MILIOTO A， et al,SemanticKITTI： a dataset for semantic scene understanding of LIDAR sequences,2019 IEEE/CVF International Conference on Computer Vision. IEEE， 2019： 9297-9307.,C,semantickitti:adatasetforsemanticsceneunderstandingoflidarsequences,False
453,CAESAR H， BANKITI V， LANG A H， et al. nuScenes： a multimodal dataset for autonomous driving［C］. 2020 IEEE/CVF International Conference on Computer Vision. IEEE， 2020： 11621-11631.,基于三维锥形栅格的激光点云语义分割方法,Semantic Segmentation Method of LiDAR Point Cloud Based on 3D Conical Grid,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",2022-08-25,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,2,CAESAR H， BANKITI V， LANG A H， et al,nuScenes： a multimodal dataset for autonomous driving,2020 IEEE/CVF International Conference on Computer Vision. IEEE， 2020： 11621-11631.,C,nuscenes:amultimodaldatasetforautonomousdriving,False
454,HACKEL T， SAVINOV N， LADICKY L， et al. Semantic3d. net： a new large-scale point cloud classification benchmark［J］. ISPRS Annals of Photogrammetry， Remote Sensing and Spatial Information Sciences， 2017， IV-1/W1： 91–98.,基于三维锥形栅格的激光点云语义分割方法,Semantic Segmentation Method of LiDAR Point Cloud Based on 3D Conical Grid,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",2022-08-25,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,3,HACKEL T， SAVINOV N， LADICKY L， et al. Semantic3d,net： a new large-scale point cloud classification benchmark,ISPRS Annals of Photogrammetry， Remote Sensing and Spatial Information Sciences， 2017， IV-1/W1： 91–98.,J,net:anewlarge-scalepointcloudclassificationbenchmark,False
455,WU B， WAN A， YUE X， et al. SqueezeSeg： convolutional neural nets with recurrent CRF for real-time road-object segmentation from 3D LIDAR point cloud［C］. 2018 IEEE International Conference on Robotics and Automation （ICRA）. IEEE， 2018： 1887-1893.,基于三维锥形栅格的激光点云语义分割方法,Semantic Segmentation Method of LiDAR Point Cloud Based on 3D Conical Grid,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",2022-08-25,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,4,WU B， WAN A， YUE X， et al,SqueezeSeg： convolutional neural nets with recurrent CRF for real-time road-object segmentation from 3D LIDAR point cloud,2018 IEEE International Conference on Robotics and Automation （ICRA）. IEEE， 2018： 1887-1893.,C,squeezeseg:convolutionalneuralnetswithrecurrentcrfforreal-timeroad-objectsegmentationfrom3dlidarpointcloud,False
456,WU B， ZHOU X， ZHAO S， et al. SqueezeSegV2： improved model structure and unsupervised domain adaptation for road-object segmentation from a LIDAR point cloud［C］. 2019 International Conference on Robotics and Automation （ICRA）. IEEE， 2019： 4376-4382.,基于三维锥形栅格的激光点云语义分割方法,Semantic Segmentation Method of LiDAR Point Cloud Based on 3D Conical Grid,"autonomous driving,LiDAR point cloud,semantic segmentation,3D conical grid,re-parameterization,3D sparse convolution network,",2022-08-25,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007,24,5,WU B， ZHOU X， ZHAO S， et al,SqueezeSegV2： improved model structure and unsupervised domain adaptation for road-object segmentation from a LIDAR point cloud,2019 International Conference on Robotics and Automation （ICRA）. IEEE， 2019： 4376-4382.,C,squeezesegv2:improvedmodelstructureandunsuperviseddomainadaptationforroad-objectsegmentationfromalidarpointcloud,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37525,DOU J， XUE J， FANG J. SEG-VoxelNet for 3D vehicle detection from RGB and LiDAR data［C］. 2019 International Conference on Robotics and Automation （ICRA）. 2019.,基于特征融合的多层次多模态目标检测,Multi-level and Multi-modal Target Detection Based on Feature Fusion,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",2021-11-22,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,12,DOU J， XUE J， FANG J,SEG-VoxelNet for 3D vehicle detection from RGB and LiDAR data,2019 International Conference on Robotics and Automation （ICRA）. 2019.,C,seg-voxelnetfor3dvehicledetectionfromrgbandlidardata,False
37526,廖家才，曹立波，夏家豪，等. 基于核相关滤波和运动模型的多目标轨迹跟踪［J］. 汽车工程，2019，41（10）：1179-1188.,基于特征融合的多层次多模态目标检测,Multi-level and Multi-modal Target Detection Based on Feature Fusion,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",2021-11-22,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,13,廖家才，曹立波，夏家豪，等,基于核相关滤波和运动模型的多目标轨迹跟踪,汽车工程，2019，41（10）：1179-1188.,J,基于核相关滤波和运动模型的多目标轨迹跟踪,False
37527,HE K， ZHANG X， REN S， et al. Deep residual learning for image recognition［C］. 2016 IEEE Conference on Computer Vision and Pattern Recognition （CVPR）. IEEE， 2016.,基于特征融合的多层次多模态目标检测,Multi-level and Multi-modal Target Detection Based on Feature Fusion,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",2021-11-22,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,14,HE K， ZHANG X， REN S， et al,Deep residual learning for image recognition,2016 IEEE Conference on Computer Vision and Pattern Recognition （CVPR）. IEEE， 2016.,C,deepresiduallearningforimagerecognition,False
37528,SUN C， SHRIVASTAVA A， SINGH S， et al. Revisiting unreasonable effectiveness of data in deep learning era［C］. IEEE Computer Society. IEEE Computer Society， 2017.,基于特征融合的多层次多模态目标检测,Multi-level and Multi-modal Target Detection Based on Feature Fusion,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",2021-11-22,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,15,SUN C， SHRIVASTAVA A， SINGH S， et al,Revisiting unreasonable effectiveness of data in deep learning era,IEEE Computer Society. IEEE Computer Society， 2017.,C,revisitingunreasonableeffectivenessofdataindeeplearningera,False
37529,HE Y， XU D，WU L， et al. LFFD： a light and fast face detector for edge devices［J］.arXiv Preprint，arXiv：，2019.,基于特征融合的多层次多模态目标检测,Multi-level and Multi-modal Target Detection Based on Feature Fusion,"autonomous driving,environmental perception,hierarchical feature fusion,multimodal fusion,small target detection,",2021-11-22,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005,1911,16,HE Y， XU D，WU L， et al,LFFD： a light and fast face detector for edge devices,arXiv Preprint，arXiv：，2019.,J,lffd:alightandfastfacedetectorforedgedevices,False

In [167]:
edges = (df_ad_cn[df_ad_cn['is_internal']]
         [['title', 'ref_title_n']]      # citing → cited
         .drop_duplicates())

indeg  = edges['ref_title_n'].value_counts()   # 被引用回数
outdeg = edges['title'].value_counts()       # 引用した回数

nodes = set(edges['title']) | set(edges['ref_title_n'])   # 線がつながる論文のみ

In [168]:
roots = [n for n in nodes if indeg.get(n, 0) == 0 and outdeg.get(n, 0) > 0]

In [169]:
roots

['语义驱动的4D雷达与相机融合目标检测',
 '匝道汇入场景下基于交互场模型的驾驶员交互行为研究',
 '城市道路场景下考虑多类交通参与者的多模态车辆轨迹预测方法研究',
 '基于角度交并比和自适应生命周期的三维多目标跟踪算法',
 '基于复合动态采样的自动驾驶矿车节能路径规划方法',
 '基于多信息融合网络的行人轨迹预测方法',
 '基于双分支实例分割网络的复杂环境车道线检测方法',
 '基于多粒度关系推理的自动驾驶域自适应视觉目标检测算法',
 '车载雷达关键场景的数据采集与标记方法',
 '基于实例激活图的自动驾驶实时实例分割算法',
 '基于有向图的城市交叉口场景相似性评价方法',
 '基于模型预测路径积分和输出调节的层级运动控制',
 '面向自动驾驶的大模型对齐技术：综述',
 '飞行汽车关键技术及应用研究综述',
 '基于改进分层可拓理论的智能汽车AFS/DYC协调控制',
 '自动驾驶等级提高条件下驾驶人驾驶姿势变化规律分析',
 '基于双目逆投影的停车位占位快速检测方法',
 '仿驾驶员DDPG汽车纵向自动驾驶决策方法',
 '线控转向相似性路径跟踪的综合控制器设计',
 '引入自监督预训练的轨迹预测方法',
 '环境车辆轨迹拟人学习的自动驾驶仿真场景构建方法',
 '基于结构化意图建模的自动驾驶类人性决策策略研究',
 '基于级联YOLOv7的自动驾驶三维目标检测',
 '基于LiDAR点云特征补全的雪天无人车目标检测',
 '自动驾驶环境下车道级雷视融合SLAM',
 '基于BEV特征融合的3D目标检测方法',
 '面向量产自动驾驶域控制器多传感器同步方法研究',
 '基于人机博弈的驾驶权接管控制策略']

In [171]:
df_ev_cn = df_cn[df_cn['keywords'].str.contains('electric vehicles', case=False, na=False)]

In [172]:
df_ev_cn

,reference,title,title_en,keywords,date,link,paperid,ref_no,ref_author,ref_title,ref_journal,ref_type
177,"BRESSER D, HOSOI K, HOWELL D, et al. Perspectives of automotive battery R&D in China, Germany, Japan, and the USA[J]. Journal of Power Sources,2018,382:176-178.",车用锂离子电池低温特性与加热方法研究进展*,Research Progress on Low-temperature Characteristics and HeatingTechniques of Vehicle Lithium-ion Battery,"electric vehicles,lithium-ion batteries,low temperature performances,heating techniques,thermal management,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014,14,1,"BRESSER D, HOSOI K, HOWELL D, et al","Perspectives of automotive battery R&D in China, Germany, Japan, and the USA","Journal of Power Sources,2018,382:176-178.",J
178,"LU L, HAN X, LI J, et al. A review on the key issues for lithium-ion battery management in electric vehicles[J]. Journal of Power Sources,2013,226:272-288.",车用锂离子电池低温特性与加热方法研究进展*,Research Progress on Low-temperature Characteristics and HeatingTechniques of Vehicle Lithium-ion Battery,"electric vehicles,lithium-ion batteries,low temperature performances,heating techniques,thermal management,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014,14,2,"LU L, HAN X, LI J, et al",A review on the key issues for lithium-ion battery management in electric vehicles,"Journal of Power Sources,2013,226:272-288.",J
179,"HARKS P P R M L, MULDER F M, NOTTEN P H L. In situ methods for Li-ion battery research: a review of recent developments[J]. Journal of Power Sources,2015,288:92-105.",车用锂离子电池低温特性与加热方法研究进展*,Research Progress on Low-temperature Characteristics and HeatingTechniques of Vehicle Lithium-ion Battery,"electric vehicles,lithium-ion batteries,low temperature performances,heating techniques,thermal management,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014,14,3,"HARKS P P R M L, MULDER F M, NOTTEN P H L",In situ methods for Li-ion battery research: a review of recent developments,"Journal of Power Sources,2015,288:92-105.",J
180,"雷治国,张承宁,李军求,等.电动车用锂离子电池低温性能研究[J].汽车工程,2013,35(10):927-933.",车用锂离子电池低温特性与加热方法研究进展*,Research Progress on Low-temperature Characteristics and HeatingTechniques of Vehicle Lithium-ion Battery,"electric vehicles,lithium-ion batteries,low temperature performances,heating techniques,thermal management,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014,14,4,"雷治国,张承宁,李军求,等",电动车用锂离子电池低温性能研究,"汽车工程,2013,35(10):927-933.",J
181,"CHO H M, CHOI W S, GO J Y, et al. A study on time-dependent low temperature power performance of a lithium-ion battery[J]. Journal of Power Sources,2012,198:273-280.",车用锂离子电池低温特性与加热方法研究进展*,Research Progress on Low-temperature Characteristics and HeatingTechniques of Vehicle Lithium-ion Battery,"electric vehicles,lithium-ion batteries,low temperature performances,heating techniques,thermal management,",2019-06-05,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.05.014,14,5,"CHO H M, CHOI W S, GO J Y, et al",A study on time-dependent low temperature power performance of a lithium-ion battery,"Journal of Power Sources,2012,198:273-280.",J
...,...,...,...,...,...,...,...,...,...,...,...,...
37322,宗硕， 宋昱龙， 曹锋. 跨临界CO2喷射器系统优化调节技术综述［J］. 流体机械， 2021， 49（7）：50-56，68.,-30至50 ℃车辆工况下CO2喷射器的适应性研究,Research on the Adaptability of CO2 Ejector Under Automotive Conditions Ranging from -30 to 50 ℃,"electric vehicles,ejector,CO<sub>2</sub>,adaptability,heat pump system,",2024-04-24,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.04.014,1901,17,宗硕， 宋昱龙， 曹锋,跨临界CO2喷射器系统优化调节技术综述,流体机械， 2021， 49（7）：50-56，68.,J
37323,索科洛夫， 津格尔. 喷射器［M］. 黄秋云，译. 北京： 科学出版社， 1977.,-30至50 ℃车辆工况下CO2喷射器的适应性研究,Research on the Adaptability of CO2 Ejector Under Automotive Conditions Ranging from -30 to 50 ℃,"electric vehicles,ejector,CO<sub>2</sub>,adaptability,heat pump system,",2024-04-24,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.04.014,1901,18,索科洛夫， 津格尔,喷射器,黄秋云，译. 北京： 科学出版社， 1977.,M
37324,吕宇捷. 跨临界CO2喷射器的设计及性能研究［D］. 杭州： 浙江大学， 2013.,-30至50 ℃车辆工况下CO2喷射器的适应性研究,Research on the Adaptability of CO2 Ejector Under Automotive Conditions Ranging from -30 to 50 ℃,"electric vehicles,ejector,CO<sub>2</sub>,adaptability,heat pump system,",2024-04-24,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.04.014,1901,19,吕宇捷,跨临界CO2喷射器的设计及性能研究,杭州： 浙江大学， 2013.,D
37325,MOFFAT R J. Describing the uncertainties in experimental results［J］. Experimental Thermal and Fluid Science， 1988， 1（1）： 3-17.,-30至50 ℃车辆工况下CO2喷射器的适应性研究,Research on the Adaptability of CO2 Ejector Under Automotive Conditions Ranging from -30 to 50 ℃,"electric vehicles,ejector,CO<sub>2</sub>,adaptability,heat pump system,",2024-04-24,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.04.014,1901,20,MOFFAT R J,Describing the uncertainties in experimental results,Experimental Thermal and Fluid Science， 1988， 1（1）： 3-17.,J
37326,LEMMON E， HUBER M， MCLINDEN M. NIST standard reference database 23： reference fluid thermodynamic and transport proerties-REFPROP， version 9.1［DB］. NIST， 2013.,-30至50 ℃车辆工况下CO2喷射器的适应性研究,Research on the Adaptability of CO2 Ejector Under Automotive Conditions Ranging from -30 to 50 ℃,"electric vehicles,ejector,CO<sub>2</sub>,adaptability,heat pump system,",2024-04-24,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.04.014,1901,21,LEMMON E， HUBER M， MCLINDEN M. NIST standard reference database 23： reference fluid thermodynamic and transport proerties-REFPROP， version 9,1,NIST， 2013.,DB

In [174]:
corpus = set(df_cn['title'].map(norm).dropna())    # 収録論文のタイトル集合
df_ev_cn['ref_title_n'] = df_ev_cn['ref_title'].map(norm)
df_ev_cn['is_internal'] = df_ev_cn['ref_title_n'].isin(corpus)
edges = (df_ev_cn[df_ev_cn['is_internal']]
         [['title', 'ref_title_n']]      # citing → cited
         .drop_duplicates())

indeg  = edges['ref_title_n'].value_counts()   # 被引用回数
outdeg = edges['title'].value_counts()       # 引用した回数

nodes = set(edges['title']) | set(edges['ref_title_n'])

In [176]:
roots2 = [n for n in nodes if indeg.get(n, 0) == 0 and outdeg.get(n, 0) > 0]
roots2

['融合工况识别的增程式电动汽车模糊能量管理策略研究',
 '面向极限工况的分布式驱动电动汽车动力学集成控制方法',
 '基于分层式控制的混合动力汽车生态驾驶研究',
 '一种车用高速电机循环冷却油温集总参数模型',
 '电动汽车关门声品质预测模型研究',
 '分布式驱动电动汽车多目标转矩分配策略',
 '基于R290工质的电动汽车集成式热管理系统性能研究',
 '电动汽车无线充电系统DDDQ型磁耦合结构研究',
 '电动汽车两挡变速器方案与换挡控制研究综述',
 '大数据驱动动力电池智能安全管理与控制方法研究',
 '新能源汽车综合经济性对比分析及预测研究',
 '基于电动汽车制动安全检测的短时工况及方法研究',
 '基于LADRC的纯电动汽车双离合变速器换挡控制',
 '制冷工况下汽车座舱新风比例智能控制策略及节能效果评价']