In [1]:
##This is program to scrape china-SAE site

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [6]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 
}

In [14]:
response = requests.get("https://www.qichegongcheng.com/CN/1000-680X/home.shtml",headers=headers)
doc = BeautifulSoup(response.text)

In [2]:
url="https://www.qichegongcheng.com/CN/1000-680X/home.shtml"

In [15]:
doc

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
<title>汽车工程</title>
<script language="javascript" src="https://www.qichegongcheng.com/images/OPENWIN.JS"></script>
<script src="https://www.qichegongcheng.com/js/prototype-1.3.1.js" type="text/JavaScript"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/jquery1.8.2/jquery.min.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/modelDialog1.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/layer2.1/layer.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/drag.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/store.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/download.js"></script>
<link href="https://www.qichegongcheng.com/js/manu/lrtk.css" rel="stylesheet" type="text/css"/>
<script language="javascript" src="https://www.qichegongcheng.com/js/manu/manu.js"></script>
<!--图片显示  弹出窗口-->
<link href="https://www.qichegongcheng.com/js/colorbox/colorbox.css" rel="stylesheet"/>
<script src="https://www.qichegongcheng.com/js/colorbox/jquery.colorbox.js"></script>
<!--图片显示  弹出窗口   结束-->
<script language="javascript">
function collectArticle(id) {
	var url = window.location.href;
	jQuery.ajax({
		url: "https://www.qichegongcheng.com/CN/user/addCollectArticle.do",
		data: {
			"articleId": id,
			"url": url
		},
		type: "post",
		success: function(res) {
			if (res == "true") {
				alert("收藏成功！");
			} else if (res == "false") {
				alert("您已经收藏过该篇文章啦！");
			} else if (res.length > 5) {
				window.location.href = "https://www.qichegongcheng.com/CN/user/userInfo_cn.jsp?url=" + res;
			} else {
				alert("收藏失败！");
				window.location.reload();
			}
		},
		error: function() {
			alert("收藏失败！");
		}
	});
}

$(document).ready(function(){
	$(".figureClass").colorbox({rel:'figureClass', transition:"none", width:"80%", height:"80%"});
	jQuery.getJSON("https://www.qichegongcheng.com/CN/article/NumbersStatistics.do?", null, function(json){
		var articleCount = json.articleCount;
		var downloadCount = json.downloadCount;
		var journalCount = json.journalCount;
		var browseCount = json.browseCount;

		var maxNian = json.maxNian;
		var minNian = json.minNian;
		var allMaxNian = json.allMaxNian;
		var allMinNian = json.allMinNian;
		var issueCount = json.issueCount;
		var allIssueCount = json.allIssueCount;
		var allArticleCount = json.allArticleCount;
		var allDownloadCount = json.allDownloadCount;
		var allBrowseCount = json.allBrowseCount;
		var citedCount = json.citedCount;
		var allCitedCount = json.allCitedCount;

		$("#articleCount").text(articleCount);
		$("#downloadCount").text(downloadCount);
		$("#journalCount").text(journalCount);
		$("#browseCount").text(browseCount);
		$("#maxNian").text(maxNian);
		$("#minNian").text(minNian);
		$("#allMaxNian").text(allMaxNian);
		$("#allMinNian").text(allMinNian);
		$("#issueCount").text(issueCount);
		$("#allIssueCount").text(allIssueCount);
		$("#allArticleCount").text(allArticleCount);
		$("#allDownloadCount").text(allDownloadCount);
		$("#allBrowseCount").text(allBrowseCount);
		$("#citedCount").text(citedCount);
		$("#allCitedCount").text(allCitedCount);


	});


});
//选中文章  文章块  变色
function hightlightrowaction(rowid) {
	var thisrow = $("#"+rowid);
	if ($(thisrow).hasClass("selectedrow")) {
		$(thisrow).removeClass("selectedrow");
		$(thisrow).addClass("noselectrow");
	} else {
		$(thisrow).addClass("selectedrow");
		$(thisrow).removeClass("noselectrow");
	}
}

function lsdy2(attachType,articleId,qiKanWangZhi,nian,issn){
	var pars = "attachType="+attachType+"&id="+articleId;
		if(attachType == "RICH_HTML"){
			jQuery.post(qiKanWangZhi+"/CN/article/downloadArticleFileFee.do?" + new Date(), pars, function(data){
				window.location.href = qiKanWangZhi+"/article/"+nian+"/"+issn+"/"+articleId;
			});
		}else{
			window.location.href = qiKanWangZhi+"/CN/article/downloadArticleFile.do?attachType="+attachType+"&id="+articleId;
		}
			$('.layui-layer').hide();
	$('.layui-layer-shade').hide();
}
function getScroll() {
    var t, l, w, h; 11.
    if (document.documentElement && document.documentElement.scrollTop) {
        t = document.documentElement.scrollTop;
        l = document.documentElement.scrollLeft;
        w = document.documentElement.scrollWidth;
        h = document.documentElement.scrollHeight;
    } else if (document.body) {
        t = document.body.scrollTop;
        l = document.body.scrollLeft;
        w = document.body.scrollWidth;
        h = document.body.scrollHeight;
    }
    return { t: t, l: l, w: w, h: h };
}
function isready1(){
	var flag=0;
	var obj = document.getElementsByName('pid');
	for(var i= 0;i<obj.length;i++){
		if(obj[i].checked){
			flag=1;
			break;
		}
    }
	if(flag==0){
		alert("请选择文章!");
		return  false;
	}
	var form = document.getElementById("AbstractList");
	form.action="../article/uniteZhaiYao.do";
	form.submit();
}

function selectall(argu,checkBoxName){
	var obj = document.getElementsByName(checkBoxName);
    for(var i= 0;i<obj.length;i++){
		obj[i].checked = argu.checked;
        //hightlightrowaction('art'+obj[i].value);
        var thisrow = $("#art"+obj[i].value);
        if(obj[i].checked){
        	if (!$(thisrow).hasClass("selectedrow")) {
				$(thisrow).addClass("selectedrow");
				$(thisrow).removeClass("noselectrow");
			}
        }else{
        	if ($(thisrow).hasClass("selectedrow")) {
				$(thisrow).removeClass("selectedrow");
				$(thisrow).addClass("noselectrow");
			}
        }
    }
}
//文章图片显示隐藏用
function togthumb() {
	$(".apwrap").toggleClass("hiden");
	if($('.apwrap').hasClass('hiden'))
		$("#thumbtn").attr("src", "https://www.qichegongcheng.com/images/sele_pic2.png");
	else
		$("#thumbtn").attr("src", "https://www.qichegongcheng.com/images/sele_pic1.png");
}
//导出
function downloadCitations(type){
	var flag=0;
	var ids="";
	var obj = document.getElementsByName('pid');
	for(var i= 0;i<obj.length;i++){
		if(obj[i].checked){
			flag=1;
			ids+=obj[i].value+",";
		}
    }
	if(flag==0){
		alert("请选择文章!");
		return  false;
	}
	window.location.href="https://www.qichegongcheng.com/CN/article/getTxtFiles.do?fileType="+type+"&articleIds="+ids;
}
function DrawImage(ImgD,FitWidth,FitHeight){
	var image=new Image();
	image.src=ImgD.src;
	if(image.width>0 && image.height>0){
		if(image.width/image.height>= FitWidth/FitHeight){
			if(image.width>FitWidth){
				ImgD.width=FitWidth;
				ImgD.height=(image.height*FitWidth)/image.width;
			}else{
				ImgD.width=image.width;
				ImgD.height=image.height;
			}
		} else{
			if(image.height>FitHeight){
				ImgD.height=FitHeight;
				ImgD.width=(image.width*FitHeight)/image.height;
			}else{
				ImgD.width=image.width;
				ImgD.height=image.height;
			}
		}
	}
}
</script>
<style type="text/css">
.black_overlay{
    display: none;
    position: absolute;
    top: 0%;
    left: 0%;
    width: 100%;
    height: 100%;
    background-color: #D8D8D8;
    z-index:1001;
    -moz-opacity: 0.8;
    opacity:.80;
    filter: alpha(opacity=80);
}
.waiting_content {
    display: none;
    position: absolute;
    top: 15%;
    left: 25%;
    width: 50%;
    padding: 16px;
    border: 1px solid orange;
    background-color: white;
    z-index:1002;
    overflow: auto;
}
.STYLE58{
	text-indent: 2em;
}
</style>
<!-- 浮动广告开始-->
<script type="text/javascript">
		 function hidead()
			{
				document.getElementById("ad1").style.display="none";
			}
		function addEvent(obj,evtType,func,cap){
				cap=cap||false;
				if(obj.addEventListener){
					obj.addEventListener(evtType,func,cap);
					return true;
				}else if(obj.attachEvent)
				{
					if(cap){
						obj.setCapture();
						return true;
					}else{
						return obj.attachEvent("on" + evtType,func);
					}
				}else{
					return false;
				}
		}
	function getPageScroll(){
		var xScroll,yScroll;
		if (self.pageXOffset) {
			xScroll = self.pageXOffset;
		} else if (document.documentElement && document.documentElement.scrollLeft){
			xScroll = document.documentElement.scrollLeft;
		} else if (document.body) {
			xScroll = document.body.scrollLeft;
		}
		if (self.pageYOffset) {
			yScroll = self.pageYOffset;
		} else if (document.documentElement && document.documentElement.scrollTop){
			yScroll = document.documentElement.scrollTop;
		} else if (document.body) {
			yScroll = document.body.scrollTop;
		}
			arrayPageScroll = new Array(xScroll,yScroll);
			return arrayPageScroll;
	}
		function GetPageSize(){
			var xScroll, yScroll;
		if (window.innerHeight && window.scrollMaxY) {
			xScroll = document.body.scrollWidth;
			yScroll = window.innerHeight + window.scrollMaxY;
		} else if (document.body.scrollHeight > document.body.offsetHeight){
			xScroll = document.body.scrollWidth;
			yScroll = document.body.scrollHeight;
		} else {
			xScroll = document.body.offsetWidth;
			yScroll = document.body.offsetHeight;
		}
		var windowWidth, windowHeight;
		if (self.innerHeight) {
			windowWidth = self.innerWidth;
			windowHeight = self.innerHeight;
		} else if (document.documentElement && document.documentElement.clientHeight) {
			windowWidth = document.documentElement.clientWidth;
			windowHeight = document.documentElement.clientHeight;
		} else if (document.body) {
			windowWidth = document.body.clientWidth;
			windowHeight = document.body.clientHeight;
		}
		if(yScroll < windowHeight){
			pageHeight = windowHeight;
		} else {
			pageHeight = yScroll;
		}
		if(xScroll < windowWidth){
			pageWidth = windowWidth;
		} else {
			pageWidth = xScroll;
		}
			arrayPageSize = new Array(pageWidth,pageHeight,windowWidth,windowHeight)
			return arrayPageSize;
		}

		var AdMoveConfig=new Object();
		AdMoveConfig.IsInitialized=false;
		AdMoveConfig.ScrollX=0;
		AdMoveConfig.ScrollY=0;
		AdMoveConfig.MoveWidth=0;
		AdMoveConfig.MoveHeight=0;
		AdMoveConfig.Resize=function(){
			var winsize=GetPageSize();
			AdMoveConfig.MoveWidth=winsize[2];
			AdMoveConfig.MoveHeight=winsize[3];
			AdMoveConfig.Scroll();
		}
		AdMoveConfig.Scroll=function(){
			var winscroll=getPageScroll();
			AdMoveConfig.ScrollX=winscroll[0];
			AdMoveConfig.ScrollY=winscroll[1];
		}
		addEvent(window,"resize",AdMoveConfig.Resize);
		addEvent(window,"scroll",AdMoveConfig.Scroll);
		function AdMove(id){
		if(!AdMoveConfig.IsInitialized){
			AdMoveConfig.Resize();
			AdMoveConfig.IsInitialized=true;
		}
		var obj=document.getElementById(id);
		obj.style.position="absolute";
		var W=AdMoveConfig.MoveWidth-obj.offsetWidth;
		var H=AdMoveConfig.MoveHeight-obj.offsetHeight;
		var x = W*Math.random(),y = H*Math.random();
		var rad=(Math.random()+1)*Math.PI/6;
		var kx=Math.sin(rad),ky=Math.cos(rad);
		var dirx = (Math.random()<0.5?1:-1), diry = (Math.random()<0.5?1:-1);
		var step = 1;
		var interval;
		this.SetLocation=function(vx,vy){x=vx;y=vy;}
		this.SetDirection=function(vx,vy){dirx=vx;diry=vy;}
		obj.CustomMethod=function(){
		obj.style.left = (x + AdMoveConfig.ScrollX) + "px";
		obj.style.top = (y + AdMoveConfig.ScrollY) + "px";
		rad=(Math.random()+1)*Math.PI/6;
		W=AdMoveConfig.MoveWidth-obj.offsetWidth;
		H=AdMoveConfig.MoveHeight-obj.offsetHeight;
		x = x + step*kx*dirx;
		if (x < 0){
			dirx = 1;x = 0;kx=Math.sin(rad);ky=Math.cos(rad);
		}
		if (x > W){
			dirx = -1;x = W;kx=Math.sin(rad);ky=Math.cos(rad);
		}
		y = y + step*ky*diry;
		if (y < 0){
			diry = 1;y = 0;kx=Math.sin(rad);ky=Math.cos(rad);
		}
		if (y > H){
			diry = -1;y = H;kx=Math.sin(rad);ky=Math.cos(rad);
			}
		}
		this.Run=function(){
			var delay = 10;
			interval=setInterval(obj.CustomMethod,delay);
			obj.onmouseover=function(){clearInterval(interval);}
			obj.onmouseout=function(){interval=setInterval(obj.CustomMethod, delay);}
		}
	}
	</script>
<script type="text/javascript">
		var ad1=new AdMove("ad1");
		ad1.Run();
				//多组漂浮
				//var ad1=new AdMove("ad2");
		//ad2.Run();
	</script>
<!--漂浮结束-->
<link href="https://www.qichegongcheng.com/images/1000-680X/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://www.qichegongcheng.com/images/1000-680X/css/css.css" rel="stylesheet"/>
<script src="https://www.qichegongcheng.com/js/jquery/jquery.min.js"></script>
<script src="https://www.qichegongcheng.com/images/1000-680X/js/bootstrap.min.js"></script>
<link href="https://www.qichegongcheng.com/images/1000-680X/fonts/font-awesome.min.css" rel="stylesheet"/>
<!--兼容性问题-->
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<script language="javascript">
$(document).ready(function () {
	$("#online_first").load("../article/asap.do");
	$("#zuixin").load("../article/showNewArticleSimple.do");
	$("#guokan").load("../article/showOldVolumnSimple.do");
	$("#featured_articles").load("../article/showHotArticleSimple.do");
	$("#most_downloader").load("../article/showDownloadTopListSimple.do?year=0");
	$("#most_browse").load("../article/showBrowseTopListSimple.do?year=0");
	$("#most_cited").load("../article/showBeiyincishuTopSimple.do");
	$("#xnzt").load("../subject/listCollection.do");
});
</script>
</head>
<body>
<!--头部-->
<!--头部-->
<header class="banner1">
<div class="container">
<div class="row">
<div class="col-md-7 col-xs-7 logo">
<h1> <img class="img-responsive" data-bd-imgshare-binded="1" src="https://www.qichegongcheng.com/images/1000-680X/images/logo.png"/> </h1>
</div>
<div class="col-md-5 col-xs-5 hidden-sm hidden-xs">
<div class="row">
<div class="col-md-4 col-xs-4 issn text-right">
<div class="row">
<img src="https://www.qichegongcheng.com/images/1000-680X/images/logo_xy.png"/>
</div>
</div>
<div class="col-md-8 col-xs-8 text-right issn" style="text-align: left">
主管：中国科学技术协会<br/>
主办：中国汽车工程学会<br/>
出版：《汽车之友》杂志社有限公司
    </div>
</div>
<div class="btn-toolbar btn-p input-group" role="toolbar">
<iframe allowtransparency="true" border="0" frameborder="0" height="40" id="search1" scrolling="no" src="https://www.qichegongcheng.com/CN/article/quickSearch.do" width="460"></iframe>
</div>
</div>
</div>
</div>
</header>
<div class="navbar site-nav whitebg">
<div class="container">
<div class="row">
<div class="navbar-header">
<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button"> <span class="sr-only">导航切换</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
<a class="navbar-brand visible-xs" href="https://www.qichegongcheng.com">汽车工程</a> </div>
<div class="navbar-collapse collapse" role="navigation">
<ul class="nav navbar-nav">
<li><a href="https://www.qichegongcheng.com">首页</a></li>
<li class="dropdown" role="presentation"> <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#">关于期刊 <b class="caret"></b></a>
<ul class="dropdown-menu site-nav">
<li><a href="https://www.qichegongcheng.com/CN/column/column1.shtml" target="_blank">期刊介绍</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column13.shtml" target="_blank">数据库收录</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column15.shtml" target="_blank">期刊荣誉</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column3.shtml" target="_blank">编委会</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column21.shtml" target="_blank">学术编委</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column22.shtml" target="_blank">青年编委</a></li>
</ul>
</li>
<li class="dropdown" role="presentation"> <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#">在线投稿 <b class="caret"></b></a><ul class="dropdown-menu site-nav">
<li><a href="https://www.qichegongcheng.com/CN/column/column6.shtml" target="_blank">投稿指南</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column17.shtml" target="_blank">论文模板</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column20.shtml" target="_blank">版权协议</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column18.shtml" target="_blank">投稿流程</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column19.shtml" target="_blank">专题征稿</a></li>
</ul>
</li>
<li><a href="https://www.qichegongcheng.com/CN/column/column9.shtml" target="_blank">动态新闻</a></li>
<li class="dropdown" role="presentation"> <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#">期刊文章 <b class="caret"></b></a>
<ul class="dropdown-menu site-nav">
<li><a href="https://www.qichegongcheng.com/CN/1000-680X/current.shtml" target="_blank">当期目录</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showNewArticle.do">优先出版</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showOldVolumn.do">过刊浏览</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showChannelList.do">主题特辑</a></li>
<li><a href="https://www.qichegongcheng.com/CN/subject/listSubject.do">虚拟专辑</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showDownloadTopList.do">下载排行</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showBrowseTopList.do">点击排行</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showBeiyincishuTop.do">引用排行</a></li>
<li><a href="https://www.qichegongcheng.com/CN/alert/showAlertInfo.do">E-mail Alter</a></li>
</ul>
</li>
<li><a href="https://www.qichegongcheng.com/CN/column/column8.shtml" target="_blank">期刊订阅</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column14.shtml" target="_blank">广告合作</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column12.shtml" target="_blank">联系我们</a></li>
<li><a href="https://www.qichegongcheng.com/EN/1000-680X/home.shtml" target="_blank">English</a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="container whitebg" style="height: 20px"></div>
<!--头部end-->
<script src="https://tongji.journalreport.cn/mstatistics.service.js"></script><script>recordAdd('da25d21082af4c7f83b3b717ae7eb26c')</script>
<div class="container whitebg">
<div class="row">
<div class="col-md-9 col-xs-9">
<!--轮播图-->
<section class="banner" style="margin-bottom: 15px;">
<div class="carousel slide" data-interval="5000" data-ride="carousel" id="carousel-example-captions">
<!--自动播放（data-ride="carousel"）　时间（data-interval="5000"）-->
<!-- Carousel items -->
<div class="carousel-inner" role="listbox">
<div class="item active">
<a href="https://www.das.publish.founderss.cn/otherPages/Microblog/html/topicCatalog.html?magId=6034" target="_blank">
<img data-holder-rendered="true" src="https://www.qichegongcheng.com/fileup/1000-680X/NEWS/20260305153851.jpg" title="2025年分领域专辑正式发布"/>
<div class="carousel-caption">
			2025年分领域专辑正式发布
        </div>
</a></div>
<div class="item">
<a href="http://www.qichegongcheng.com/CN/column/column19.shtml" target="_blank">
<img data-holder-rendered="true" src="https://www.qichegongcheng.com/fileup/1000-680X/NEWS/20190710094134.jpg" title="《汽车工程》征稿"/>
<div class="carousel-caption">
			《汽车工程》征稿
        </div>
</a></div>
<div class="item">
<a href="https://link.springer.com/journal/42154" target="_blank">
<img data-holder-rendered="true" src="https://www.qichegongcheng.com/fileup/1000-680X/NEWS/20190710094326.jpg" title="Automotive Innovation-中国汽车行业第一本英文国际期刊"/>
<div class="carousel-caption">
			Automotive Innovation-中国汽车行业第一本英文国际期刊
        </div>
</a></div>
</div>
<ol class="carousel-indicators hidden-xs">
<li class="active" data-slide-to="0" data-target="#carousel-example-captions"></li>
<li data-slide-to="1" data-target="#carousel-example-captions"></li>
<li data-slide-to="2" data-target="#carousel-example-captions"></li>
</ol>
<!-- Carousel nav -->

In [4]:
from lxml import etree

In [7]:
resp = requests.get(url, headers=headers)

In [8]:
tree = etree.HTML(resp.text)

In [16]:
xpath = '//a[@class="txt_biaoti"]'

In [17]:
elements = tree.xpath(xpath)
elements

[<Element a at 0x10cb34180>,
 <Element a at 0x10caaee40>,
 <Element a at 0x10cabac80>,
 <Element a at 0x10cbd5fc0>,
 <Element a at 0x10cbd4c80>,
 <Element a at 0x10cbd6140>,
 <Element a at 0x10cbd61c0>,
 <Element a at 0x10cbd6200>,
 <Element a at 0x10cbd6240>,
 <Element a at 0x10cbd6180>,
 <Element a at 0x10cbd6280>,
 <Element a at 0x10cbd62c0>,
 <Element a at 0x10cbd6300>,
 <Element a at 0x10cbd6340>,
 <Element a at 0x10cbd6380>,
 <Element a at 0x10cbd63c0>,
 <Element a at 0x10cbd6400>,
 <Element a at 0x10cbd6440>,
 <Element a at 0x10cbd6480>,
 <Element a at 0x10cbd64c0>,
 <Element a at 0x10cbd6500>,
 <Element a at 0x10cbd6540>,
 <Element a at 0x10cbd6580>,
 <Element a at 0x10cbd65c0>,
 <Element a at 0x10cbd6600>]

In [18]:
data = []
for elm in elements:
    link = elm.get('href')
    title = elm.text
    row = {'link' : link, 'title': title}
    data.append(row)

In [19]:
data

[{'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.001',
  'title': '基于旋转平移不变性的高效点云描述子研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.002',
  'title': '低照度环境下基于红外视觉的驾驶员异常行为检测研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.003',
  'title': '面向复合工况的智能轮胎侧向力估计方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.004',
  'title': '基于声压缓冲机制的车内声场分区控制研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.005',
  'title': '基于分组递进优化的ABS虚拟加速标定方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.006',
  'title': '基于率失真优化的设计运行条件边界动态监测方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.007',
  'title': '数字钥匙非可视测距研究与实现'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.008',
  'title': '城市低空飞行汽车环境感知方案综述'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.009',
  'title': '智驾车辆乘坐舒适性主客观测试评价研究进展'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.010',
  'title': '融合Mamba状态建模的多模态端到端自动驾驶决策方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.011',
  'title': '基于强化学习的偏好轨迹规划策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.012',
  'title': '基于Transformer和置信机制的车载CAN网络入侵检测系统'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.013',
  'title': '面向开放交通长尾场景感知的视觉-语言模型特征级提示词融合方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.014',
  'title': '融合自注意力机制和低层特征增强的交通场景语义分割方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.015',
  'title': '智能驾驶汽车动力学时序特征相似性度量方法与敏感性分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.016',
  'title': '手势交互中反馈机制对驾驶行为的影响研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.017',
  'title': '基于强化学习自适应PID的越野巡航控制研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.018',
  'title': '考虑能效优化的燃料电池热管理分层控制研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.019',
  'title': '基于数据驱动的锂离子电池热失控表面温度场重构模型'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.ep.002',
  'title': '内嵌半导体除湿单元的动力电池包多场建模及性能分析评价'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.021',
  'title': '基于仿气生根流道的锂离子电池液冷性能分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.022',
  'title': '基于深度学习的质子交换膜燃料电池系统水状态数字孪生方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.023',
  'title': '适用SUV风阻仿真的数据驱动湍流模型研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.024',
  'title': '三面导流板对方背Ahmed模型的气动影响研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.06.025',
  'title': '车内声场分区控制分频段实现方法'}]

In [20]:
url_total="https://www.qichegongcheng.com/CN/article/showOldVolumn.do"

In [22]:
resp = requests.get(url_total, headers=headers)
tree = etree.HTML(resp.text)
xpath = '//a[@class="J_WenZhang"]'
elements = tree.xpath(xpath)
elements

[<Element a at 0x10cc5d640>,
 <Element a at 0x10cd51f40>,
 <Element a at 0x10cd52280>,
 <Element a at 0x10cd501c0>,
 <Element a at 0x10cd53300>,
 <Element a at 0x10cc39a00>,
 <Element a at 0x10cc39bc0>,
 <Element a at 0x10cc3afc0>,
 <Element a at 0x10cc3ab40>,
 <Element a at 0x10cd199c0>,
 <Element a at 0x10cc3ab00>,
 <Element a at 0x10cc3ae40>,
 <Element a at 0x10cc3b200>,
 <Element a at 0x10cc39b00>,
 <Element a at 0x10cc3b180>,
 <Element a at 0x10cc3a800>,
 <Element a at 0x10cc39740>,
 <Element a at 0x10cc39840>,
 <Element a at 0x10cc393c0>,
 <Element a at 0x10cc39c00>,
 <Element a at 0x10cc38d40>,
 <Element a at 0x10cc39b40>,
 <Element a at 0x10cc39fc0>,
 <Element a at 0x10cc39d80>,
 <Element a at 0x10a5c2500>,
 <Element a at 0x10a5c1700>,
 <Element a at 0x10a5c0d80>,
 <Element a at 0x10a5c0dc0>,
 <Element a at 0x109c99000>,
 <Element a at 0x10ca051c0>,
 <Element a at 0x1087cc280>,
 <Element a at 0x109bb7b00>,
 <Element a at 0x10a488840>,
 <Element a at 0x109794600>,
 <Element a at 0x1085e6b00>,
 <Element a at 0x109c12ec0>,
 <Element a at 0x109c11740>,
 <Element a at 0x10c9f85c0>,
 <Element a at 0x10c9f8100>,
 <Element a at 0x10c9f8680>,
 <Element a at 0x10a684fc0>,
 <Element a at 0x10a684d80>,
 <Element a at 0x10907d680>,
 <Element a at 0x107fc90c0>,
 <Element a at 0x10a4bc680>,
 <Element a at 0x10a4be000>,
 <Element a at 0x10a4be780>,
 <Element a at 0x10a4bde40>,
 <Element a at 0x10a4bf800>,
 <Element a at 0x10a4bcfc0>,
 <Element a at 0x10a4bdf40>,
 <Element a at 0x10a4bcd80>,
 <Element a at 0x10a4bd8c0>,
 <Element a at 0x10a4bd4c0>,
 <Element a at 0x1097f5d80>,
 <Element a at 0x108074380>,
 <Element a at 0x108077740>,
 <Element a at 0x109582a00>,
 <Element a at 0x109581d80>,
 <Element a at 0x10caa8040>,
 <Element a at 0x10caa8100>,
 <Element a at 0x10caa8280>,
 <Element a at 0x10caa9b80>,
 <Element a at 0x10caa8300>,
 <Element a at 0x10caa9800>,
 <Element a at 0x10caa9b00>,
 <Element a at 0x10caa9300>,
 <Element a at 0x10caa9b40>,
 <Element a at 0x10caa81c0>,
 <Element a at 0x10caa84c0>,
 <Element a at 0x10caa9880>,
 <Element a at 0x10caa9a80>,
 <Element a at 0x10caa95c0>,
 <Element a at 0x10caa9580>,
 <Element a at 0x10caa9500>,
 <Element a at 0x10caa9540>,
 <Element a at 0x10caa9400>,
 <Element a at 0x10caa9340>,
 <Element a at 0x10caa8440>,
 <Element a at 0x10caa8500>,
 <Element a at 0x10caa8380>,
 <Element a at 0x10caa8840>,
 <Element a at 0x10caa8680>,
 <Element a at 0x10caa8780>,
 <Element a at 0x10caa8700>,
 <Element a at 0x10caa87c0>,
 <Element a at 0x10caa8640>,
 <Element a at 0x10caa8a40>,
 <Element a at 0x10caa8c80>,
 <Element a at 0x10caa8980>,
 <Element a at 0x10caa8c00>,
 <Element a at 0x10caa8b40>,
 <Element a at 0x10caa8c40>,
 <Element a at 0x10caa8dc0>,
 <Element a at 0x10caa8d40>,
 <Element a at 0x10caa8d00>,
 <Element a at 0x10caa9000>,
 <Element a at 0x10caa8ec0>,
 <Element a at 0x10caa8e40>,
 <Element a at 0x10caa90c0>,
 <Element a at 0x10caa9040>,
 <Element a at 0x10caa8fc0>,
 <Element a at 0x10caa9380>,
 <Element a at 0x10caa8f40>,
 <Element a at 0x10caa9140>,
 <Element a at 0x10caa97c0>,
 <Element a at 0x10caa94c0>,
 <Element a at 0x10caa9600>,
 <Element a at 0x10caa9940>,
 <Element a at 0x10caa9440>,
 <Element a at 0x10caa9740>,
 <Element a at 0x10caa9680>,
 <Element a at 0x10caa9840>,
 <Element a at 0x10caa96c0>,
 <Element a at 0x10caa98c0>,
 <Element a at 0x10caa99c0>,
 <Element a at 0x10caa9a40>,
 <Element a at 0x10765fb40>,
 <Element a at 0x10a5ef580>,
 <Element a at 0x10a5ef1c0>,
 <Element a at 0x10a60b440>,
 <Element a at 0x10a60a880>,
 <Element a at 0x10a60b640>,
 <Element a at 0x10a609900>,
 <Element a at 0x10a60b4c0>,
 <Element a at 0x109859fc0>,
 <Element a at 0x109859e00>,
 <Element a at 0x10a6a1d00>,
 <Element a at 0x10a6a1cc0>,
 <Element a at 0x109585740>,
 <Element a at 0x109584f40>,
 <Element a at 0x10cb23b80>,
 <Element a at 0x10cb23500>,
 <Element a at 0x10cb22f40>,
 <Element a at 0x10cb23180>,
 <Element a at 0x10cb20240>,
 <Element a at 0x10cb23cc0>,
 <Element a at 0x10cb22340>,
 <Element a at 0x10cb23d80>,
 <Element a at 0x10cb23e00>,
 <Element a at 0x10cb21d40>,
 <Element a at 0x10cb23840>,
 <Element a at 0x10cb22b80>,
 <Element a at 0x10cb22f00>,
 <Element a at 0x10cb23200>,
 <Element a at 0x10cb22840>,
 <Element a at 0x10cb22880>,
 <Element a at 0x10cb23740>,
 <Element a at 0x10cb21480>,
 <Element a at 0x10cb23800>,
 <Element a at 0x10cb21a00>,
 <Element a at 0x10cb21100>,
 <Element a at 0x10cb21cc0>,
 <Element a at 0x10cb23000>,
 <Element a at 0x10cb23dc0>,
 <Element a at 0x10cb22d00>,
 <Element a at 0x10cb23540>,
 <Element a at 0x10cb22640>,
 <Element a at 0x10cb20ac0>,
 <Element a at 0x10a4d7a80>,
 <Element a at 0x10a4d7b00>,
 <Element a at 0x10a4d7000>,
 <Element a at 0x10808c740>,
 <Element a at 0x10808c680>,
 <Element a at 0x10808f700>,
 <Element a at 0x10808dac0>,
 <Element a at 0x10808f440>,
 <Element a at 0x109484280>,
 <Element a at 0x10cb665c0>,
 <Element a at 0x10cb662c0>,
 <Element a at 0x10cb67300>,
 <Element a at 0x10cb67040>,
 <Element a at 0x10cb67900>,
 <Element a at 0x10cb657c0>,
 <Element a at 0x10cb67580>,
 <Element a at 0x10cb67bc0>,
 <Element a at 0x10cb652c0>,
 <Element a at 0x10cb66b80>,
 <Element a at 0x10cb66e40>,
 <Element a at 0x10cb67b80>,
 <Element a at 0x10cb64280>,
 <Element a at 0x10cb65080>,
 <Element a at 0x10cb643c0>,
 <Element a at 0x10cb65700>,
 <Element a at 0x10cb64a40>,
 <Element a at 0x10cb66a00>,
 <Element a at 0x10cb64880>,
 <Element a at 0x10cb67c40>,
 <Element a at 0x10cb66fc0>,
 <Element a at 0x10cb65e40>,
 <Element a at 0x10cb664c0>,
 <Element a at 0x10cb66240>,
 <Element a at 0x10cb67600>,
 <Element a at 0x10cb67240>]

In [27]:
urls = []
for elm in elements:
    link = elm.get('href')
    urls.append(link)

In [131]:
len(urls)

194

In [127]:
def remove_duplicates(lst):
    return list(set(lst))

In [132]:
len(unique_urls)

105

In [128]:
unique_urls=remove_duplicates(urls)

In [29]:
import time

In [47]:
from urllib.parse import urljoin
source_page_url = "https://www.qichegongcheng.com/CN/article/showOldVolumn.do"

In [53]:
data_total=[]
data_everybook=[]

In [133]:
data_total=[]
for url in unique_urls:
    url = urljoin(source_page_url, url) 
    resp = requests.get(url, headers=headers)
    tree = etree.HTML(resp.text)
    xpath = '//a[@class="txt_biaoti"]'
    elements = tree.xpath(xpath)
    data_everybook=[]
    time.sleep(2)
    for elm in elements:        
        print("-----")
        
        link = elm.get('href')
        title = elm.text
        print(link)
        row = {'link' : link, 'title': title}
        data_total.append(row)

-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.019
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.001
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.002
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.003
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.004
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.005
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.006
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.007
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.008
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.009
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.010
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.011
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.012
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.013
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.014
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.015
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.016
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.017
-----
https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.ep.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.01.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.04.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.07.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.08.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.001
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.002
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.003
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.004
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.005
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.006
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.007
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.008
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.009
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.010
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.011
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.012
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.013
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.014
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.015
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.016
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.017
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.018
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.06.019
-----
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.012.001
-----

In [49]:
url

'https://www.qichegongcheng.com/CN/volumn/volumn_2.shtml'

In [134]:
data_total

[{'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.001',
  'title': '基于HS⁃FCM模糊聚类的快速多目标车辆跟踪算法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.002',
  'title': '面向视频结构化的细粒度车辆检测分类模型'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.003',
  'title': '面向车辆目标的路侧多摄像机双向匹配交接方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.004',
  'title': '智能车辆多信号灯路口快速节能车速规划'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.005',
  'title': '隔热层对锂电池模组热失控蔓延特性影响的实验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.006',
  'title': '基于EGO加点策略的动力电池包多目标优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.007',
  'title': '质子交换膜燃料电池阴阳极压力控制策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.008',
  'title': '采用粒子群优化和高斯回归实现电池SOH估计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.009',
  'title': '碳化硅CDPF再生特性的关键性影响因素试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.010',
  'title': '积分迭代模式优化对侧翻一步碰撞算法的改进'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.011',
  'title': '基于MPDB试验的车辆碰撞攻击性识别与评价方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.012',
  'title': '基于碰撞波形与约束系统耦合的汽车安全性改进'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.013',
  'title': '汽车拼焊B柱成型工艺与耐撞性分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.014',
  'title': '带弯道信息的城市复合行驶工况构建方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.015',
  'title': '基于LCC/N磁集成补偿网络的强耦合无线充电系统研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.016',
  'title': '沟槽面积对不同润滑油温下离合器摩擦磨损特性的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.017',
  'title': '基于熵的车载CAN总线异常检测研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.018',
  'title': '基于缸压信号的汽车声音合成算法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.019',
  'title': '基于应力张量分析的后副车架疲劳试验'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.001',
  'title': '双电机一体化纯电动客车动力分配策略优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.002',
  'title': '增程式电动汽车最优曲线模糊控制策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.003',
  'title': '基于改进PSO-RBF算法的纯电动汽车剩余里程实时预测'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.004',
  'title': '基于NA-EKF的分布式驱动电动汽车行驶状态估计研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.005',
  'title': '喷油时刻和EGR对Diesel/MF混合燃料燃烧和排放的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.006',
  'title': '基于平台翻滚的微型客车耐撞性研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.007',
  'title': '基于多目标可靠性优化的骡车车身耐撞性及轻量化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.008',
  'title': '汽车盘式制动器时变稳定性的分析与优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.009',
  'title': '电动汽车连续再生制动系统防抱死制动试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.010',
  'title': '分布驱动轮式车辆差动转向动力学特性研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.011',
  'title': '驱动桥准双曲面齿轮传动误差有限元分析与试验'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.012',
  'title': '乘员表面温度分布和乘员舱热舒适性的模拟'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.013',
  'title': '发动机热平衡测试及影响因素研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.014',
  'title': '基于小波与深度置信网络的柴油机失火故障诊断'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.015',
  'title': '基于改进K_means的发动机状态评估方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.016',
  'title': '表贴式永磁电机磁场的解析计算与分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.017',
  'title': '基于HMM和SVM级联算法的驾驶意图识别'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.07.018',
  'title': '表面处理对车身用5182铝合金接头胶粘性能的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.001',
  'title': '考虑信号灯和能耗的电动车最优路径规划'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.002',
  'title': '基于双目逆投影的停车位占位快速检测方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.003',
  'title': '基于电池寿命预测控制的履带车辆能量管理'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.004',
  'title': '电量保持阶段增程器的排放与工作特性的试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.005',
  'title': '基于交通信息的复合电源系统控制策略优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.006',
  'title': '基于强化学习的多燃烧模式混合动力能量管理策略'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.007',
  'title': '转向主销定位参数和接地点偏距的解析研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.008',
  'title': '基于主客观综合赋权法的制动踏板感觉评价'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.009',
  'title': '基于中国工况的纯电动乘用车续驶里程评价方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.010',
  'title': '平头货车在考虑侧风影响下的气动阻力系数优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.011',
  'title': '基于相平面的分布式驱动电动汽车稳定性控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.012',
  'title': '全球NCAP行人保护测评的对比研究及展望'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.013',
  'title': '不同角度正面碰撞中老年驾驶员下肢模型的响应研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.014',
  'title': '汽车与护栏碰撞立柱绊阻机理及防止措施'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.015',
  'title': '梯度负泊松比结构填充吸能盒多工况优化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.016',
  'title': '基于显式控制律设计的AMT电控系统开发流程与验证'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.017',
  'title': '电液耦合转向系统转向盘转矩的自抗扰控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.018',
  'title': '汽车后副车架轻量化概念设计方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.05.019',
  'title': '基于胶带密封法的汽车各密封部位动静态泄漏噪声的试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.001',
  'title': '智能车辆换道潜在冲突分析与风险量化方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.002',
  'title': '网联交叉口信号-车辆轨迹协同优化控制方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.003',
  'title': '基于自查询的车载多目标跟踪算法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.004',
  'title': '基于粗糙性度量的道路可行驶区域识别方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.005',
  'title': '基于特征融合的多层次多模态目标检测'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.006',
  'title': '转向避撞工况下装载激光雷达车辆的障碍物跟踪'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.007',
  'title': '基于改进型ELM的熟练驾驶员行车轨迹拟合方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.008',
  'title': '缸内直喷射流点火汽油机的燃烧优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.009',
  'title': '瞬态工况下掺混PODE对混合动力柴油机排放特性的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.010',
  'title': '动态密封状态下汽车风噪性能不确定性研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.011',
  'title': '带侧翼式扩散器对汽车气动特性影响研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.012',
  'title': '基于多源数据的车流量时空预测方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.013',
  'title': '无人车辆底盘集成动力学系统解耦控制研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.014',
  'title': '考虑多维驾驶特性的制动反应时间预测模型'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.015',
  'title': '基于低通滤波的大功率型氢燃料电池重型货车 自适应能量管理策略'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.016',
  'title': '基于平均-差异模型的电池组短路电流估计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.017',
  'title': '基于DTV-IGPR模型的锂离子电池SOH估计方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.018',
  'title': '锂离子电池状态估计机器学习方法综述'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.11.019',
  'title': '基于交通事故统计的电池包底部碰撞研究'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.001',
  'title': '基于马尔科夫链的并联PHEB预测型能量管理策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.002',
  'title': '电场极性对甲烷空气混合气燃烧特性的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.003',
  'title': '基于Delphi\ue011变异系数组合赋权法的电池性能评估研究'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.004',
  'title': '新型R1233zde制冷剂的高效节能环保性能分析'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.005',
  'title': '考虑冲压工艺约束的车身骨架断面形状优化\n考虑冲压工艺约束的车身骨架断面形状优化'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.006',
  'title': '基于车身概念模型的白车身主断面尺寸优化'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.007',
  'title': '基于分析驱动设计的封闭白车身轻量化多目标优化'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.008',
  'title': '一种汽车防撞梁轻量化结构的仿真分析与试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.009',
  'title': '基于有限元法的汽车盘式制动器蠕动颤振建模与分析'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.010',
  'title': '基于EEMD和熵理论的电动汽车制动意图识别方法'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.011',
  'title': '一种基于数字图像相关的高精度车辆跟踪算法'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.012',
  'title': '基于V2X通信网络的车辆协同定位增强方法'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.013',
  'title': '基于三维激光雷达的无人车障碍物检测与跟踪'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.014',
  'title': '基于行驶场景模型的线控辅助转向系统仿真'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.015',
  'title': '单帽型薄壁梁弯曲和轴向压溃吸能的理论预测方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.016',
  'title': '一种客车骨架接头非线性应力快速计算方法'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.017',
  'title': '汽车侧窗风振噪声特性差异研究'},
 {'link': 'https://www.qichegongcheng.com/CN/doi:10.19562/j.chinasae.qcgc.2018.08.018',
  'title': '基于蒸发温度的汽车空调蒸发器除霜判定方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.001',
  'title': '高压共轨柴油机起动控制策略与参数优化研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.002',
  'title': '梯度强度汽车薄壁结构抗撞性优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.003',
  'title': '基于脑电信号的疲劳驾驶状态研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.004',
  'title': '汽车乘员约束系统多目标不确定性优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.005',
  'title': '微型电动汽车转向管柱支撑结构耐撞性设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.006',
  'title': '商用车鼓式制动器热流双向耦合分析技术研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.007',
  'title': '智能车辆换道行驶的经济车速研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.008',
  'title': '车辆自适应巡航控制系统的建模与分层控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.009',
  'title': '基于深度置信网络的多源信息前方车辆检测'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.010',
  'title': '磁流变半主动悬架试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.011',
  'title': '某新型线控转向系统的自适应模糊滑模控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.012',
  'title': '一种新型液电馈能式悬架系统的设计与研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.013',
  'title': '基于多模型交互的复杂工况下车辆状态估计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.014',
  'title': '高频制动尖叫的振动能量流动分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.015',
  'title': '曲轴偏置对活塞裙部混合润滑特性的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.016',
  'title': '汽车托运平板车辆的模拟试验方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.017',
  'title': '基于隐式参数化模型的白车身轻量化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.05.018',
  'title': '基于模块化设计的车身装配结构优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.001',
  'title': '氢燃料电池汽车整车集成式热管理系统研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.002',
  'title': '基于三介质换热器的电动汽车热管理系统及其性能分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.003',
  'title': '低温环境下车用锂电池预加热策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.004',
  'title': '汽车乘员舱热舒适性影响因素多参数优化分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.ep.005',
  'title': '非均匀热环境人体局部热响应对整体热感觉影响差异性分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.006',
  'title': '锂电池热管-液冷板式冷却结构多目标优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.007',
  'title': '基于同心圆结构的新型液冷板优化设计及其性能研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.008',
  'title': '基于帧间隔-总线电压混合特征的汽车ECU伪装攻击识别'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.009',
  'title': '基于特征和标签联合分布匹配的智能驾驶跨域自适应目标检测'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.010',
  'title': '基于RMPC的自动驾驶货车路径跟踪控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.011',
  'title': '基于多参数控制的分布式驱动电动汽车操纵稳定性控制策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.012',
  'title': '纯电动汽车传动系统-电机结构参数协同设计优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.013',
  'title': '车用燃料电池堆低温停机吹扫试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.014',
  'title': '火花辅助压燃准维燃烧模型的建立及应用'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.015',
  'title': '三火花塞点火系统对混动专用发动机稀燃性能影响试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.016',
  'title': '车用大功率燃料电池发动机进气系统控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.017',
  'title': '副车架静刚度修正方法及多层级拓扑优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.018',
  'title': '碳陶盘式制动器散热特性台架实验分析与数值仿真研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.11.019',
  'title': '基于薄板承载特性的车身接头结构设计方法'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.001',
  'title': '并联混合动力传动系统结构创新设计研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.002',
  'title': '基于DL-MOPSO算法的等效燃油消耗最小能量管理策略优化研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.003',
  'title': '冲程缸径比对汽油机缸内流场影响的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.004',
  'title': 'CVVL发动机动态工况优化控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.005',
  'title': '自动驾驶汽车横向可拓预瞄切换控制系统研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.006',
  'title': '基于模型预测控制的混合动力汽车模式切换中的转矩协调控制策略'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.007',
  'title': '基于环境态势评估的智能车自主变道决策机制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.008',
  'title': '自动变速器表面涂层齿轮温度场特性的仿真与试验研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.009',
  'title': '基于稳态卡尔曼滤波的车辆质量与道路坡度估计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.010',
  'title': '换挡离合器摩擦元件周向间歇接触温度场研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.011',
  'title': '混合动力汽车的转速转矩双同步换挡控制'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.012',
  'title': '作动器惯性质量对主动悬架幅频特性的影响'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.013',
  'title': '车辆侧倾状态估计的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.014',
  'title': '座椅体压分布仿真分析与评价'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.015',
  'title': '内燃机式增程器扭转振动的建模与分析'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.016',
  'title': '增压发动机正时系统冷起动敲击噪声的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2018.09.017',
  'title': '双排行星齿轮系统的齿轮优化修形'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.001',
  'title': '基于多目标遗传算法的SCR系统氨覆盖率优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.002',
  'title': '基于CCP协议的纯电动车整车控制器标定研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.003',
  'title': '基于等效因子优化的插电式混合动力客车自适应能量管理策略'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.004',
  'title': '智能网联环境下的多车协同换道策略研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.005',
  'title': '凸轮驱动式液压可变气门机构设计及运动特性'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.006',
  'title': '基于灵敏度分析中心组合设计的乘用车发动机舱温度场优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.007',
  'title': '基于活塞传热与强度分析的内冷油腔的优化'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.008',
  'title': '安装ECAS和液压互联悬架的客车动态性能研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.009',
  'title': '含时滞悬架系统'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.010',
  'title': '矩阵风扇冷却系统模糊控制的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.011',
  'title': '轻型客车用户目标载荷建立方法的研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.012',
  'title': '一种基于Sepic-Zeta混合斩波电路的动力电池组双向高速均衡器研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.013',
  'title': '基于稀疏采样数据的电动公交车电池SOC预测方法研究'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.014',
  'title': '新能源汽车的多热源分段协同制热系统'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.015',
  'title': '真空高压铸造铝合金车身后纵梁轻量化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.016',
  'title': '碳纤维复合材料防撞梁轻量化设计'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.017',
  'title': '发动机半阶次振动引起的车内声品质问题分析和改进'},
 {'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.03.018',
  'title': '白车身激光扫描焊熔池边界提取与缺陷识别的研究'},

In [135]:
len(data_total)

1925

In [137]:
df_total = pd.DataFrame(data_total)

In [138]:
df_total['link'].value_counts()

link
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.001    1
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.002    1
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.003    1
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.004    1
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.005    1
                                                                         ..
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.013    1
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.014    1
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.015    1
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.016    1
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.017    1
Name: count, Length: 1925, dtype: int64

In [56]:
url2="https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.05.001"

In [78]:
resp = requests.get(url2, headers=headers)
tree = etree.HTML(resp.text)

In [79]:
tree

In [103]:
xpath = '//p[strong[contains(.,"Abstract")]]/following-sibling::p[1]' ##テスト
elements = tree.xpath(xpath)
elements[0].text

'To accurately acquire the vehicle location in the GNSS restricted environment such as urban canyon， a visual vehicle locating method is proposed with single road side unit （RSU） assisted. A camera is used to measure the lateral distance from the vehicle to the lane lines， and the RSU and vehicle are interacted for the distance measurement and communications. The information of GNSS， IMU， RSU and camera observed are fused through the error state Kalman filtering algorithm to fulfill the accurate estimation of the location and orientation of vehicle. Real vehicle tests are conducted to analyze the effects of the ranging information of single RSU and the lateral distance measured on positioning results. The results show that the ranging information of single RSU can effectively reduce the longitudinal positioning error， but its correction effects of lateral positioning error gradually reduce with the increase of the distance from RSU. This defect can be effectively remedied by lateral distance measurement， and complementing both advantages results in a root mean square error in horizontal positioning less than 10 cm， verifying the effectiveness of the method proposed.'

In [91]:
xpath = '//meta[@name="citation_title"]/@content' ##これもテスト
elements = tree.xpath(xpath)
elements

['基于专家策略行为克隆的高速NOA强化学习研究',
 'Research on High-Speed NOA Reinforcement Learning Based on Expert Strategy Behavior Cloning']

In [93]:
for elm in elements:
    print(elm)

基于专家策略行为克隆的高速NOA强化学习研究
Research on High-Speed NOA Reinforcement Learning Based on Expert Strategy Behavior Cloning

In [72]:
response = requests.get(url2,headers=headers)
doc = BeautifulSoup(response.text)

In [73]:
doc

<!DOCTYPE html>
<html>
<head>
<meta content="自动驾驶,规划控制,行为克隆,强化学习," name="keywords"/>
<meta content="https://www.qichegongcheng.com/CN/abstract/abstract2176.shtml" name="HW.ad-path"/>
<meta content="https://www.qichegongcheng.com/CN/abstract/abstract2176.shtml" name="HW.identifier"/>
<meta content="text/html" name="DC.Format"/>
<meta content="cn" name="DC.Language"/>
<meta content="基于专家策略行为克隆的高速NOA强化学习研究" name="DC.Title"/>
<meta content="10.19562/j.chinasae.qcgc.2026.05.001" name="DC.Identifier"/>
<meta content="赵克刚" name="DC.Contributor"/>
<meta content="李佳宜" name="DC.Contributor"/>
<meta content="叶杰" name="DC.Contributor"/>
<meta content="曾润林" name="DC.Contributor"/>
<meta content="2026-05-22" name="DC.Date"/>
<meta content="汽车工程" name="citation_journal_title"/>
<meta content="汽车工程" name="citation_journal_abbrev"/>
<meta content="1000-680X" name="citation_issn"/>
<meta content="赵克刚,李佳宜,叶杰,曾润林" name="citation_authors" xml:lang="cn"/>
<meta content="基于专家策略行为克隆的高速NOA强化学习研究" name="citation_title" xml:lang="cn"/>
<meta content="自动驾驶,规划控制,行为克隆,强化学习," name="DC.Keywords" xml:lang="cn"/>
<meta content="2026-05-22" name="citation_date"/>
<meta content="48" name="citation_volume"/>
<meta content="5" name="citation_issue"/>
<meta content="963" name="citation_firstpage"/>
<meta content="972" name="citation_lastpage"/>
<meta content="48/5/963" name="citation_id"/>
<meta content="10.19562/j.chinasae.qcgc.2026.05.001" name="citation_doi"/>
<meta content="Kegang Zhao,Jiayi Li,Jie Ye,Runlin Zeng" name="citation_authors" xml:lang="en"/>
<meta content="Research on High-Speed NOA Reinforcement Learning Based on Expert Strategy Behavior Cloning" name="citation_title" xml:lang="en"/>
<meta content="autonomous driving,planning control,behavior cloning,reinforcement learning," name="DC.Keywords" xml:lang="en"/>
<meta content="https://www.qichegongcheng.com/CN/abstract/abstract2176.shtml" name="citation_abstract_html_url"/>
<meta content="https://www.qichegongcheng.com/CN/article/downloadArticleFile.do?attachType=PDF&amp;id=2176" name="citation_pdf_url"/>
<meta content="https://www.qichegongcheng.com/CN/abstract/abstract2176.shtml" name="citation_public_url"/>
<meta content="noarchive" name="robots"/>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
<title>基于专家策略行为克隆的高速NOA强化学习研究</title>
<!--css必引 -->
<link href="https://www.qichegongcheng.com/images/1000-680X/css/bootstrap.min.css" rel="stylesheet"/>
<link href="https://www.qichegongcheng.com/images/1000-680X/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet"/>
<!-- jQuery必引-->
<script src="https://www.qichegongcheng.com/images/1000-680X/js/jquery.min.js"></script>
<!-- 网站css必引-->
<link href="https://www.qichegongcheng.com/images/1000-680X/css/css.css" rel="stylesheet"/>
<!--原摘要中的js -->
<!--图片弹出窗口 必须放在jquery.min.js后-->
<link href="https://www.qichegongcheng.com/js/colorbox/colorbox.css" rel="stylesheet"/>
<script src="https://www.qichegongcheng.com/js/colorbox/jquery.colorbox.js"></script>
<script type="text/javascript">
	//等比缩放图片
function DrawImage(ImgD,FitWidth,FitHeight){
	var image=new Image();
	image.src=ImgD.src;
	if(image.width>0 && image.height>0){
		if(image.width/image.height>= FitWidth/FitHeight){
			if(image.width>FitWidth){
				ImgD.width=FitWidth;
				ImgD.height=(image.height*FitWidth)/image.width;
			}else{
				ImgD.width=image.width;
				ImgD.height=image.height;
			}
		} else{
			if(image.height>FitHeight){
				ImgD.height=FitHeight;
				ImgD.width=(image.width*FitHeight)/image.height;
			}else{
				ImgD.width=image.width;
				ImgD.height=image.height;
			}
		}enm
	}
}
	window.onload=function(){
		$(".figureClass").colorbox({rel:'figureClass', inline:true, width:"80%"});
		$(".inline").colorbox({rel:'inline',inline:true, width:"80%"});

	}
	</script>
<!--图片弹出窗口结束-->
<!--原摘要中js end -->
<script language="javascript" src="https://www.qichegongcheng.com/js/modelDialog1.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/layer2.1/layer.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/drag.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/store.js"></script>
<script language="javascript" src="https://www.qichegongcheng.com/js/download.js"></script>
<script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" type="text/javascript"></script>
<script type="text/x-mathjax-config">
	MathJax.Hub.Config({
		extensions: ["tex2jax.js"],
		jax: ["input/TeX", "output/HTML-CSS"],
		tex2jax: {inlineMath: [ ['$','$'], ["\\(","\\)"] ],displayMath: [ ['$$','$$'], ["\\[","\\]"] ],processEscapes: true},
		"HTML-CSS": { availableFonts: ["TeX"] },
		TeX: {equationNumbers: {autoNumber: ["AMS"], useLabelIds: true}},
        "HTML-CSS": {linebreaks: {automatic: true}},
        SVG: {linebreaks: {automatic: true}}
		});
</script>
<script type="text/javascript">
jQuery(function() {
	jQuery.ajax({
		url: "https://www.qichegongcheng.com/CN/user/validateCollectArticle.do?articleId=2176",
		success: function(res) {
			collectCount();
			if (res == "true") {
				jQuery("#collectArticle").append("已收藏");
			}
			if (res == "false") {
				jQuery("#collectArticle").append("<a href='javascript:;' onclick=\"collectArticle('2176')\">收藏文章</a>");
			}
		}
	});
});

function collectCount() {
	jQuery.ajax({
		url: "https://www.qichegongcheng.com/CN/user/articleCollectionTimes.do?articleId=2176",
		success: function(res) {
			jQuery("#collectCount").html("");
			jQuery("#collectCount").append(res);
		}
	});
}

function collectArticle(id) {
	var url = window.location.href;
	jQuery.ajax({
		url: "https://www.qichegongcheng.com/CN/user/addCollectArticle.do",
		data: {
			"articleId": id,
			"url": url
		},
		type: "post",
		success: function(res) {
			if (res == "true") {
				document.getElementById("collectArticle").innerHTML = "已收藏";
				collectCount();
				alert("收藏成功！");
			} else if (res == "false") {
				alert("您已经收藏过该篇文章啦！");
				window.location.reload();
			} else if (res.length > 5) {
				window.location.href = "https://www.qichegongcheng.com/CN/user/userInfo_cn.jsp?url=" + res;
			} else {
				alert("收藏失败！");
				window.location.reload();
			}
		},
		error: function() {
			alert("收藏失败！");
		}
	});
}


//可视化开始
$(document).ready(function(){
    jQuery.getJSON("https://www.qichegongcheng.com/CN/lexeme/existsCnctstInArticle.do?articleID=2176", null, function(json){
        if(json.result){
            $("#knowledge_map_count").html(json.count);
            $("#knowledge_map_div").show();
        }
    });
});
function changeKnowledgeMapImg(flag){
    if(flag==1){
        document.getElementById("knowledge_map_img").src="../../images/knowledge_map1.png";
    }else{
        document.getElementById("knowledge_map_img").src="../../images/knowledge_map2.png";
    }
}
//可视化结束

//点赞开始
jQuery(function() {
    jQuery.ajax({
        url: 'https://www.qichegongcheng.com/CN/article/showArticleLikedNum.do',
        data: {
            articleId: 2176
        },
        type: 'post',
        dataType: 'json',
        success:function(data){  //成功的回调函数
            $("#articleLikedNum").text(data);
        },
        error:function (XMLHttpRequest, textStatus, errorThrown) {
            console.log("错误");
            // 状态码
            console.log(XMLHttpRequest.status);
            // 状态
            console.log(XMLHttpRequest.readyState);
            // 错误信息
            console.log(textStatus);
        }
    });
});

function addArticleLikedNum(id){
    jQuery.ajax({
        url: 'https://www.qichegongcheng.com/CN/article/addArticleLikedNum.do',
        data: {
            articleId: id
        },
        type: 'post',
        dataType: 'json',
        success:function(data){  //成功的回调函数
            if(data==-1){
                alert('今日已点赞！！');
            }else{
                $("#articleLikedNum").text(data);
            }
        },
        error:function (XMLHttpRequest, textStatus, errorThrown) {
            console.log("错误");
            // 状态码
            console.log(XMLHttpRequest.status);
            // 状态
            console.log(XMLHttpRequest.readyState);
            // 错误信息
            console.log(textStatus);
        }
    });
}
//点赞结束

function lsdy2(attachType,articleId,qiKanWangZhi,nian,issn){
	var pars = "attachType="+attachType+"&id="+articleId;
		if(attachType == "RICH_HTML"){
			jQuery.post(qiKanWangZhi+"/CN/article/downloadArticleFileFee.do?" + new Date(), pars, function(data){
				window.location.href = qiKanWangZhi+"/article/"+nian+"/"+issn+"/"+articleId;
			});
		}else{
			window.location.href = qiKanWangZhi+"/CN/article/downloadArticleFile.do?attachType="+attachType+"&id="+articleId;
		}
					$('.layui-layer').hide();
	$('.layui-layer-shade').hide();
}
function submitLogin(login_id, remote_password){
	var login_id = document.getElementById(login_id).value;
	var remote_password = document.getElementById(remote_password).value;
	var pars = "login_id="+login_id+"&remote_password="+remote_password;
	jQuery.post("https://www.qichegongcheng.com/CN/user/login.do?" + new Date(), pars, function(data){
		window.subwin = new SubWindow("下载文件",data,null,null,null,null,'620px','310px',null,null,"#dddddd","true",null,null,"true",null);
		subwin.show();
	});
}

function close(){
		subwin.close();
	}

function showArticleFile(url,attachType,articleId){
	var viewAttach = url+"/CN/article/showArticleFile.do?attachType="+attachType+"&id="+articleId;
	window.open(viewAttach,"下载文件","toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizeable=no,copyhistory=no,width=520,height=200,left=88,top=88");
}
function searchKeyword(url,id,keyword){
	var form = document.refForm;
	form.searchSQL.value="(("+keyword+"[Keyword]) AND "+id+"[Journal])";
	form.action = url+"/CN/article/advancedSearchResult.do";
	form.submit();
}
function searchEnKeyword(url,id,keyword){
	var form = document.refForm;
	form.searchSQL.value="(("+keyword+"[Keyword]) AND "+id+"[Journal])";
	form.action = url+"/EN/article/advancedSearchResult.do";
	form.submit();
}

function searchAuthor(url,id,author){
	var form = document.refForm;
	form.searchSQL.value="(("+author+"[Author]) AND "+id+"[Journal])";
	form.action = url+"/CN/article/searchArticleResult.do";
	form.submit();
}

function addtobookshelf(url,articleId){
	var addbookshelf = "";
	addbookshelf = url+"/CN/article/addBookShelf.do?id="+articleId;
	window.open(addbookshelf,"添加到书架","");
}

function showTxtFile(url,articleId){
	var showtxtfile = "";
	showtxtfile = url+"/CN/article/showTxtFile.do?id="+articleId;
	window.open(showtxtfile,"引用管理器","");
}

function addComment(url,articleId){
	var addComment = "";
	addComment = url+"/CN/comment/addComment.do?id="+articleId;
	window.open(addComment,"文章反馈","toolbar=no,location=no,directories=no,status=no,menubar=no,scrollbars=no,resizeable=no,copyhistory=no,width=520,height=300,left=88,top=88");
}



function findPassword(email){
	var emailReg = /^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+(.[a-zA-Z0-9_-])+/
	var email = document.getElementById(email).value;
	var matchemail = emailReg.test(email);
	var pars = "email="+email;
	if(email == '' || email == null){
		alert("Email不能为空！");
		return false;
	} else {
		if(matchemail){
			jQuery.post("https://www.qichegongcheng.com/CN/user/findPassword.do?" + new Date(), pars, function(data){
				subwin.close();
			});
		}else{
			alert("Email格式不正确");
		}
	}
}
function chakan(shifoukaifang,id,url){
	var url2 = "https://www.qichegongcheng.com/fileup/1000-680X/SUPPL/"+url;
	window.location.href = "https://www.qichegongcheng.com/CN/suppl/validateVideo.do?url="+url2+"&id="+id+"&shifoukaifang="+shifoukaifang;
}
</script>
<script src="https://www.qichegongcheng.com/images/1000-680X/js/bootstrap.min.js"></script>
<script src="https://www.qichegongcheng.com/images/1000-680X/js/jquery.pin.js"></script>
<script src="https://www.qichegongcheng.com/images/1000-680X/js/abstract.js"></script>
<!--[if lt IE 9]>
	<script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->
<style>
		#bsBox{
			width:560px !important;
			height:420px !important;
		}
		.bFind-wrapper-top{
			height:25px !important;
		}
		#bsWXBox{
			height: 257px !important;
			width: 232px !important;
		}
	</style>
</head>
<body id="goTop" style="background:#fff;">
<!--头部-->
<header class="banner1">
<div class="container">
<div class="row">
<div class="col-md-7 col-xs-7 logo">
<h1> <img class="img-responsive" data-bd-imgshare-binded="1" src="https://www.qichegongcheng.com/images/1000-680X/images/logo.png"/> </h1>
</div>
<div class="col-md-5 col-xs-5 hidden-sm hidden-xs">
<div class="row">
<div class="col-md-4 col-xs-4 issn text-right">
<div class="row">
<img src="https://www.qichegongcheng.com/images/1000-680X/images/logo_xy.png"/>
</div>
</div>
<div class="col-md-8 col-xs-8 text-right issn" style="text-align: left">
主管：中国科学技术协会<br/>
主办：中国汽车工程学会<br/>
出版：《汽车之友》杂志社有限公司
    </div>
</div>
<div class="btn-toolbar btn-p input-group" role="toolbar">
<iframe allowtransparency="true" border="0" frameborder="0" height="40" id="search1" scrolling="no" src="https://www.qichegongcheng.com/CN/article/quickSearch.do" width="460"></iframe>
</div>
</div>
</div>
</div>
</header>
<div class="navbar site-nav whitebg">
<div class="container">
<div class="row">
<div class="navbar-header">
<button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button"> <span class="sr-only">导航切换</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
<a class="navbar-brand visible-xs" href="https://www.qichegongcheng.com">汽车工程</a> </div>
<div class="navbar-collapse collapse" role="navigation">
<ul class="nav navbar-nav">
<li><a href="https://www.qichegongcheng.com">首页</a></li>
<li class="dropdown" role="presentation"> <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#">关于期刊 <b class="caret"></b></a>
<ul class="dropdown-menu site-nav">
<li><a href="https://www.qichegongcheng.com/CN/column/column1.shtml" target="_blank">期刊介绍</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column13.shtml" target="_blank">数据库收录</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column15.shtml" target="_blank">期刊荣誉</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column3.shtml" target="_blank">编委会</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column21.shtml" target="_blank">学术编委</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column22.shtml" target="_blank">青年编委</a></li>
</ul>
</li>
<li class="dropdown" role="presentation"> <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#">在线投稿 <b class="caret"></b></a><ul class="dropdown-menu site-nav">
<li><a href="https://www.qichegongcheng.com/CN/column/column6.shtml" target="_blank">投稿指南</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column17.shtml" target="_blank">论文模板</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column20.shtml" target="_blank">版权协议</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column18.shtml" target="_blank">投稿流程</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column19.shtml" target="_blank">专题征稿</a></li>
</ul>
</li>
<li><a href="https://www.qichegongcheng.com/CN/column/column9.shtml" target="_blank">动态新闻</a></li>
<li class="dropdown" role="presentation"> <a aria-expanded="false" class="dropdown-toggle" data-toggle="dropdown" href="#">期刊文章 <b class="caret"></b></a>
<ul class="dropdown-menu site-nav">
<li><a href="https://www.qichegongcheng.com/CN/1000-680X/current.shtml" target="_blank">当期目录</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showNewArticle.do">优先出版</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showOldVolumn.do">过刊浏览</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showChannelList.do">主题特辑</a></li>
<li><a href="https://www.qichegongcheng.com/CN/subject/listSubject.do">虚拟专辑</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showDownloadTopList.do">下载排行</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showBrowseTopList.do">点击排行</a></li>
<li><a href="https://www.qichegongcheng.com/CN/article/showBeiyincishuTop.do">引用排行</a></li>
<li><a href="https://www.qichegongcheng.com/CN/alert/showAlertInfo.do">E-mail Alter</a></li>
</ul>
</li>
<li><a href="https://www.qichegongcheng.com/CN/column/column8.shtml" target="_blank">期刊订阅</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column14.shtml" target="_blank">广告合作</a></li>
<li><a href="https://www.qichegongcheng.com/CN/column/column12.shtml" target="_blank">联系我们</a></li>
<li><a href="https://www.qichegongcheng.com/EN/1000-680X/home.shtml" target="_blank">English</a></li>
</ul>
</div>
</div>
</div>
</div>
<div class="container whitebg" style="height: 20px"></div>
<!--头部end-->
<script src="https://tongji.journalreport.cn/mstatistics.service.js"></script><script>recordAdd('da25d21082af4c7f83b3b717ae7eb26c')</script>
<div class="container whitebg">
<div class="abs-con">
<div class="row">
<div class="col-md-12">
<p style="margin-top:10px;">
<span><a href="https://www.qichegongcheng.com">汽车工程</a> ›› <a href="https://www.qichegongcheng.com/CN/article/showTenYearVolumnDetail.do?nian=2026">2026</a>, <a href="https://www.qichegongcheng.com/CN/article/showTenYearVolumnDetail.do?nian=2026">Vol. 48</a>  ›› <a href="https://www.qichegongcheng.com/CN/volumn/volumn_105.shtml">Issue (5)</a>: 963-972.</span><span class="doi-doi">doi: <a href="https://doi.org/10.19562/j.chinasae.qcgc.2026.05.001" target="_blank">10.19562/j.chinasae.qcgc.2026.05.001</a></span> </p>
<p>
</p>
<p class="clearfix">
<span class="pull-left">•  •</span>
<span class="pull-right">    <a href="https://www.qichegongcheng.com/CN/abstract/abstract2155.shtml">下一篇 <i class="glyphicon glyphicon-chevron-right"></i></a></span>
</p>
<!--中文-->
<h3 class="abs-tit">
         基于专家策略行为克隆的高速NOA强化学习研究
       </h3>
<p data-target="#divPanel" data-toggle="collapse">
<span>
               		赵克刚<sup>1</sup>,李佳宜<sup>1</sup>,叶杰<sup>2</sup>(<a href="mailto:yejie@fosu.edu.cn"><img border="0" src="https://www.qichegongcheng.com/images/email.png"/></a>),曾润林<sup>1</sup>

        <span data-placement="right" type="button">
<i class="glyphicon glyphicon-menu-down" style="cursor:pointer;"></i>
</span>
</span>
</p>
<div class="collapse bs-callout" id="divPanel">
<address class="address">
<ol class="list-unstyled">
<li><sup>1.</sup>华南理工大学机械与汽车工程学院，广州 510641<br/><sup>2.</sup>佛山大学机电工程与自动化学院，佛山 528231</li>
</ol>
</address>
<ul class="list-unstyled code-style" style="overflow: hidden;">
<li>
<span>
<code>收稿日期:</code>2025-06-10
									</span>
<span>
<code>修回日期:</code>2026-04-05
									</span>
<span>
</span>
<span>
<code>出版日期:</code>2026-05-25
									</span>
<span>
<code>发布日期:</code>2026-05-22
									</span>
</li>
<li> <code>通讯作者:</code>
					叶杰
											E-mail:yejie@fosu.edu.cn
												</li>
<li> </li>
<li>
<code class="pull-left" style="overflow: hidden;">基金资助:</code><div class="pull-left">国家自然科学基金(52572474);2023年度广东省特支计划领军人才项目资助</div>
</li>
</ul>
</div>
<!--中文end-->
<!------------------------------------英文---------------------------------------------------------------------->
<h3 class="abs-tit">
	       Research on High-Speed NOA Reinforcement Learning Based on Expert Strategy Behavior Cloning
    </h3>
<p data-target="#divPanelEn" data-toggle="collapse">
<span>
               		Kegang Zhao<sup>1</sup>,Jiayi Li<sup>1</sup>,Jie Ye<sup>2</sup>(<a href="mailto:yejie@fosu.edu.cn"><img border="0" src="https://www.qichegongcheng.com/images/email.png"/></a>),Runlin Zeng<sup>1</sup>


In [155]:
from requests.exceptions import RequestException

if 'dataset' not in globals():
    dataset = []
if 'failed' not in globals():
    failed = []

done = {r['link'] for r in dataset}       
i = len(dataset)                            

def pick_en(vals):
    if len(vals) > 1:
        return vals[1]
    return vals[0] if vals else None

def pick_cn(vals):
    return vals[0] if vals else None

def fetch(url, headers, retries=3):
    for k in range(retries):
        try:
            return requests.get(url, headers=headers, timeout=30)
        except RequestException as e:
            wait = 5 * (2 ** k)             # 5秒 → 10秒 → 20秒
            print(f"  リトライ{k+1}/{retries}: {type(e).__name__} ({wait}秒待機)")
            time.sleep(wait)
    return None

for paper in data_total:
    url = paper['link']

    if url in done:                          # 再実行時は取得済みを飛ばす
        continue

    print(url)
    resp = fetch(url, headers)
    if resp is None or resp.status_code != 200:
        code = resp.status_code if resp is not None else "接続失敗"
        print("取得失敗:", code, url)
        failed.append(url)                   # 後でまとめて再取得
        continue

    resp.encoding = "utf-8"
    tree = etree.HTML(resp.text)

    xpath_title = '//meta[@name="citation_title"]/@content'
    elements_title = tree.xpath(xpath_title)
    xpath_name = '//meta[@name="citation_authors"]/@content'
    elements_name = tree.xpath(xpath_name)
    xpath_date = '//meta[@name="citation_date"]/@content'
    elements_date = tree.xpath(xpath_date)
    xpath_keywords = '//meta[@name="DC.Keywords"]/@content'
    elements_kewords = tree.xpath(xpath_keywords)
    xpath_abstract = 'string(//p[strong[contains(.,"Abstract")]]/following-sibling::p[1])'
    elements_abstract = tree.xpath(xpath_abstract)

    i = i + 1
    row = {
        'title':    pick_cn(elements_title),
        'title_en': pick_en(elements_title),
        'name':     pick_en(elements_name),
        'date':     elements_date[0] if elements_date else None,
        'keywords': pick_en(elements_kewords),
        'abstract': elements_abstract or None,
        'link':     url,
        'id':       i,
    }
    dataset.append(row)
    done.add(url)                            # 同一実行内の重複も防ぐ
    print(i)

    if len(dataset) % 200 == 0:              # 定期保存
        pd.DataFrame(dataset).to_json("dataset_tmp.jsonl", orient="records",
                                      lines=True, force_ascii=False)
        print(f"  --- 中間保存 {len(dataset)}件 ---")

    time.sleep(2)

https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2022.01.017
1602
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.001
1603
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.002
1604
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.003
1605
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.004
1606
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.005
1607
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.006
1608
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.007
1609
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.008
1610
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.009
1611
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.010
1612
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.011
1613
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.012
1614
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.013
1615
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.014
1616
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.015
1617
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.016
1618
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.017
1619
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.018
1620
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.019
1621
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.01.020
1622
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.001
1623
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.002
1624
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.003
1625
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.004
1626
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.005
1627
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.006
1628
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.007
1629
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.008
1630
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.009
1631
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.010
1632
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.011
1633
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.012
1634
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.013
1635
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.014
1636
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.015
1637
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.016
1638
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.017
1639
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.018
1640
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.03.019
1641
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.001
1642
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.002
1643
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.003
1644
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.004
1645
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.005
1646
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.006
1647
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.007
1648
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.008
1649
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.009
1650
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.010
1651
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.011
1652
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.012
1653
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.013
1654
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.014
1655
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.015
1656
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.016
1657
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.017
1658
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2023.02.018
1659
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.001
1660
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.002
1661
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.003
1662
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.004
1663
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.005
1664
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.006
1665
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.007
1666
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.008
1667
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.009
1668
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.010
1669
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.011
1670
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.012
1671
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.013
1672
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.014
1673
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.015
1674
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.016
1675
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.017
1676
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.018
1677
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.019
1678
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.08.020
1679
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.001
1680
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.002
1681
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.003
1682
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.004
1683
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.ep.001
1684
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.006
1685
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.007
1686
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.008
1687
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.009
1688
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.010
1689
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.011
1690
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.012
1691
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.013
1692
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.014
1693
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.015
1694
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.016
1695
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.017
1696
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.018
1697
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.03.019
1698
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.001
1699
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.002
1700
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.003
1701
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.004
1702
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.005
1703
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.006
1704
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.007
1705
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.008
1706
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.009
1707
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.010
1708
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.011
1709
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.012
1710
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.013
1711
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.014
1712
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.015
1713
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.016
1714
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.010.017
1715
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.001
1716
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.ep.003
1717
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.ep.005
1718
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.004
1719
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.005
1720
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.006
1721
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.007
1722
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.008
1723
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.009
1724
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.010
1725
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.011
1726
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.012
1727
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.013
1728
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.014
1729
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.015
1730
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.016
1731
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.017
1732
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.018
1733
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.01.019
1734
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.001
1735
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.002
1736
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.003
1737
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.004
1738
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.005
1739
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.006
1740
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.007
1741
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.008
1742
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.009
1743
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.010
1744
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.ep.004
1745
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.012
1746
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.013
1747
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.014
1748
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.015
1749
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.016
1750
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.017
1751
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.018
1752
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.12.019
1753
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.001
1754
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.002
1755
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.003
1756
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.004
1757
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.005
1758
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.006
1759
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.007
1760
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.008
1761
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.009
1762
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.010
1763
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.011
1764
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.012
1765
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.013
1766
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.014
1767
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.015
1768
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.016
1769
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.017
1770
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.018
1771
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.019
1772
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.01.020
1773
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.ep.003
1774
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.001
1775
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.002
1776
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.003
1777
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.004
1778
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.005
1779
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.006
1780
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.007
1781
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.008
1782
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.009
1783
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.010
1784
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.011
1785
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.012
1786
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.013
1787
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.014
1788
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.015
1789
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.016
1790
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.017
1791
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.018
1792
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.019
1793
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.020
1794
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2026.02.021
1795
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.001
1796
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.002
1797
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.003
1798
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.004
1799
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.005
1800
  --- 中間保存 1800件 ---
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.006
1801
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.007
1802
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.008
1803
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.009
1804
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.010
1805
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.011
1806
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.012
1807
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.013
1808
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.014
1809
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.015
1810
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.016
1811
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.017
1812
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.018
1813
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2020.12.019
1814
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.001
1815
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.002
1816
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.003
1817
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.004
1818
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.005
1819
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.006
1820
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.007
1821
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.008
1822
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.009
1823
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.010
1824
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.011
1825
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.012
1826
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.013
1827
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.015
1828
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.016
1829
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.017
1830
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.018
1831
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.05.019
1832
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.001
1833
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.002
1834
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.003
1835
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.004
1836
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.005
1837
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.006
1838
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.007
1839
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.008
1840
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.009
1841
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.010
1842
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.011
1843
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.012
1844
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.013
1845
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.014
1846
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.015
1847
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.016
1848
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.017
1849
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.018
1850
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2024.08.019
1851
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.001
1852
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.002
1853
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.003
1854
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.004
1855
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.005
1856
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.006
1857
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.007
1858
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.008
1859
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.009
1860
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.010
1861
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.011
1862
https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.09.012
1863

In [140]:
dataset

[{'title': 'A Fast Multiple Maneuvering Vehicle Tracking Algorithm Based on Half Suppressed Fuzzy C⁃means Clustering',
  'name': 'Junhui Zhang,Zongjie Fu,Xiaoman Guo,Qing Li,Dapeng Chen,Ye Zhao',
  'date': '2021-10-25',
  'keywords': 'intelligent vehicle,data fusion,object of interest,state estimation,fuzzy C?means,',
  'abstract': 'In order to improve the real-time performance and reliability of multi-target data association in complex traffic scenarios， a fast multi-target vehicle tracking algorithm based on half suppressed fuzzy c-means clustering （HS-FCM） is thus proposed in this article. Firstly， the multi-target vehicle-tracking problem is described mathematically， and the spatial mapping relationship between the camera pixel coordinate system and the world coordinate system is established. Secondly， the fuzzy clustering approach based on fuzzy theory is employed to solve the plot-track association problem. The probability of a feasible joint event in the joint probability data association （JPDA） algorithm is indirectly calculated by solving the fuzzy membership function defined by the distance between a sample and its cluster center. The multi-objective state is filtered and estimated by the probability weighted fusion method. Thirdly， in the dense vehicle environment the measurement update is suppressed by adjusting Kalman gain reasonably to solve the problem of short-term target losing. The real vehicle test and simulation results validate the feasibility and effectiveness of the proposed fast multi-vehicle tracking algorithm.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.001'},
 {'title': 'Fine⁃grained Vehicle Detection and Classification Model for Video Structuring Description',
  'name': 'Jian Shi,Qian Cheng,Lisheng Jin,Yaoguang Hu,Xiaobei Jiang,Baicang Guo,Wuhong Wang',
  'date': '2021-10-25',
  'keywords': 'driverless technology,roadside environment perception,video structuring description algorithm,fine?grained vehicle detection and classification,',
  'abstract': 'In order to solve the problem of limited understanding of complex traffic scenes in driverless environment perception technology， this paper proposes a roadside-oriented video structured description framework， which can enrich the fine-grained information of different targets in traffic scenes and improve the understanding ability of complex traffic scenes. For the proposed framework， this paper provides an engineering fine-grained vehicle detection and classification model. The YOLOv4 algorithm is optimized by channel pruning strategy， and the volume of the compressed model， YOLOv4-Pruned， is reduced by about 60% compared with the original model under the condition that mAP is almost unchanged. A vehicle classification method with 16 types and 12 colors is designed， which can effectively cover all vehicles in the current traffic scene. And the classification accuracy of the test set can reach 93%. The fine-grained vehicle detection and classification model designed in this paper is stable at 23FPS under 1920 × 1080 pixel input， NVIDIA Geforce RTX 2080ti， and the unquantified model is stable at 13FPS under Hisilicon-Hi3516DV300.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.002'},
 {'title': 'Vehicle Target Oriented Bidirectional Matching Handover Method for Multi Camera on Roadside',
  'name': 'Ming Chen,Yimin Wu,Bolin Gao,Kaiyuan Zheng',
  'date': '2021-10-25',
  'keywords': 'vehicle?road?cloud integration,roadside camera,overlapping field of view,target handover,bidirectional matching,',
  'abstract': 'Because of the high field of view angle and wide detection range， roadside sensor is conducive to observe the spatial?temporal relationship and movement trend of targets， and becomes an important sensing means to support the vehicle road cloud integration system. However， the current roadside sensor faces the challenge that it is difficult to continuously track the target motion across the sensing domain. In order to solve the problem of target handover between cross view cameras， a bi?directional matching target handover method is proposed for roadside sensing overlapped field of vision. The transformation relationship between cameras is established to project the vehicle target in the overlapped domain， and the matching constraint mechanism is designed to solve the problem of matching conflict. The bidirectional matching strategy is designed based on the bidirectional projection of the target， and the handover result is output according to the matching matrix identifier and color similarity. The roadside experimental data show that the proposed method can be effectively applied to typical urban road traffic scenes. Compared with the one?way matching method， it reduces the missing matching by 22.22% and the false matching by 28.57% for road scenes； The missing matching and false matching of intersection scenes are reduced by 28.89% and 44.00%， respectively， which has good accuracy and reliability.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.003'},
 {'title': 'Fast Energy⁃saving Speed Planning Through Multi Signal Intersections of Intelligent Vehicles',
  'name': 'Jianghao Leng,Chao Sun,Bing Lu',
  'date': '2021-10-25',
  'keywords': 'multi signal intersections,speed planning,dynamic programming,interior point method,',
  'abstract': 'The existing energy?saving speed planning method of intelligent vehicles for complex scenes at multi signal intersections is usually with big computational burden that cannot be implemented in real-time. This paper proposes an optimized intelligent vehicle energy?saving speed planning method combining dynamic programming and the interior point method， which can rapidly calculate the road energy?saving reference speed based on the vehicle fuel consumption model and the traffic light information， and realize real?time application. Firstly， in this paper， the vehicle fuel consumption model and the signal phase and time mathematical model are established. A weighted orientation graph based on energy consumption per unit distance at cruise speed is constructed by sampling the arrival time at each intersection. The weighted orientation graph is solved via dynamic programming to obtain the optimal period of green light passing phase. Then， taking the optimal green light passing phase as the constraint， the optimal control problem is formulated and transformed into a nonlinear optimization problem， which is solved via the interior point method. To accelerate convergence speed， the initial guess of the interior point method is set to the solution of the weighted orientation graph solved by dynamic programming. Finally， simulation is carried out for evaluation. The results show that： （1） the proposed method can reduce energy consumption by over 30% compared with the improved intelligent driver model； （2） the initial guess close to optimal solution calculated by dynamic programming improves computational efficiency by more than 40%， compared with the rule?based iterative initial guess generation method.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.004'},
 {'title': 'Experimental Study on the Effects of Thermal Insulation Layers on the Propagation Characteristics of Thermal Runaway in Lithium⁃ion Battery Module',
  'name': 'Runze Chang,Bin Zheng,Xuning Feng,Chengshan Xu,Huaibin Wang,Liduo Chen,Youtang Wang',
  'date': '2021-10-25',
  'keywords': 'lithium?ion battery module,insulating layer,thermal runaway,heat propagation suppression,aerogel,',
  'abstract': 'In this paper， an experimental study on the effects of different types of heat insulation layer on the propagation characteristics of thermal runaway in battery modules is conducted. The results show that heat insulation layer can extend the heat spread time of battery module， prevent the fire caused by valve eruption in battery and lower the peak temperature in the thermal runaway of battery module. Among them， the thermal runaway propagation effect of the insulation layer of preoxidized fibers aerogel has the best effect in suppressing the propagation of thermal runaway. Its total propagation time of thermal runaway is 138% longer than that of ceramic aerogel， and 279% longer than that of nano-glass fiber.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.005'},
 {'title': 'Multi⁃objective Optimization of Traction Battery Pack Based on EGO Strategy with Additive Sample Points',
  'name': 'Puyi Wang,Yingchun Bai,Cheng Lin,Zhenjiang Wu,Baohua Wang',
  'date': '2021-10-25',
  'keywords': 'battery pack,multi?objective optimization,surrogate model,EGO with additive sample points,',
  'abstract': 'For the lightweighting of battery pack and increasing its modal frequency， a multi-objective optimization scheme based on efficient global optimization （EGO） strategy with additive sample points is proposed. Firstly， by using the design of experiment and Pareto rule， the effects of design variables on the optimization objectives are analyzed， and the variables having more significant influences on the mass and 1st-order modal frequency of battery pack are chosen to be optimized so as to reduce the problem-solving difficulty. Then， multi-objective particle swarm optimization （MOPSO） algorithm is adopted assisted with Kriging surrogate model to solve the optimization problem， and the EGO strategy with additive sample points is employed to get the new design points and samples respectively， with the surrogate model updated until the optimization procedure converges. Finally， the test functions are utilized to verify the effectiveness of the scheme proposed， which is then applied to the multi-objective optimization of battery pack. The results show the scheme is efficient and feasible， with which the mass of battery pack reduces by 4.89 kg while maintaining a higher 1st order modal frequency.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.006'},
 {'title': 'Study on Control Strategy for Anode and Cathode Pressures in Proton Exchange Membrane Fuel Cell',
  'name': 'Jiujian Chang,Xiaolin Wang,Jianping Fang,Dilin Xie,Chen Wang',
  'date': '2021-10-25',
  'keywords': 'PEMFC,pressure control strategy,',
  'abstract': 'In order to extend the service life of the proton exchange membrane fuel cell （PEMFC）， a model for PEMFC including its cathode and anode supply system is established in this paper based on an analysis on the principle of the pressure regulation of PEMFC. A control strategy for both cathode and anode pressures is designed and the flow control components covering air compressor， throttle valve and hydrogen injection valve are jointly controlled according to the pressure difference between cathode and anode. The results of hardware-in-the-loop simulation show that with the joint control strategy for cathode and anode pressures， the cathode oxygen supply can stably respond to a large sudden change in load. The anode realizes the decoupling of pressure regulation and fuel supply， and the anode pressure can quickly change to follow the cathode pressure. The pressure difference between cathode and anode can be maintained at a very low value even under complex working conditions， significantly extending the service life of proton exchange membrane.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.007'},
 {'title': 'Estimation of Battery State⁃of⁃Health Using Particle Swarm Optimization with Gauss Process Regression',
  'name': 'Lin Chen,Bohao Liu,Yunhui Ding,Shuxiao Wu,Zhe Feng,Haihong Pan',
  'date': '2021-10-25',
  'keywords': 'lithium?ion battery,state?of?health,gaussian process regression,adaptive mutation particle swarm optimizer,kernel functions,',
  'abstract': 'In order to accurately estimate the state of health （SOH） of lithium?ion battery in the process of nonlinear degradation， an AMPSO?GPR algorithm is proposed by the fusion of adaptive mutation particle swarm optimizer （AMPSO） with gaussian process regression （GPR）. Firstly， the increment of ohmic internal resistance and the sample entropy of voltage are extracted as degradation characterization indicators. Then AMPSO is introduced to optimize the hyperparameters of GPR kernel function， an SOH estimation framework based on AMPSO?GPR is constructed， and the degradation characterization indicators are extracted to perform SOH estimation. Finally， by comparing the results of SOH estimation using AMPSO?GPR with different kernel functions， the optimal kernel function is obtained. The results of experiment indicate that the AMPSO?GPR algorithm can effectively estimate the SOH of battery with a maximum absolute estimation error not more than 2.08%.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.008'},
 {'title': 'Experimental Research on Key Influencing Factors of Regenerative Characteristics of Silicon Carbide CDPF',
  'name': 'Qing Li,Guisheng Chen,Ying Luo,Ru He,Han Zhang,Weijie Shi',
  'date': '2021-10-25',
  'keywords': 'diesel engine,catalytic diesel particulate filter,passive regeneration,DTI active regeneration,national VI regulations,',
  'abstract': 'Based on the D30 TCI diesel engine， a test bench for the National 6 after-treatment system is built to carry out the CDPF passive regeneration equilibrium point temperature test under different soot loads so as to study the influence of the inlet temperature on the passive regeneration of the CDPF. The active regeneration characteristics of the CDPF under the engine DTI condition are explored and its influence on the capture characteristics of the carrier is evaluated. The results show that the carbon loading has no significant effect on the temperature at the equilibrium point of CDPF passive regeneration and the increase of carbon loading can improve the uniformity of the internal temperature of the carrier and accelerate the reaction rate of CDPF passive regeneration. The inlet temperature has significant effect on the passive regeneration of CDPF. When the temperature is increased from 325 to 360 ℃， the regeneration efficiency reaches 94%， and the regeneration rate is 56 g/h， which is increased by 1 and 18 times respectively. Under DTI conditions， during CDPF active regeneration， the internal temperature of the carrier will appear "peak". The internal temperature and temperature rise rate reach the peak at the center of the rear section. There is no obvious impact on the PM capture efficiency of CDPF after multiple DTI active regeneration， but the PN capture efficiency will decrease； and the four exhaust pollutants （HC， CO， PM， PN） in WHTC test cycle all meet the National 6 emission regulations and limits.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.009'},
 {'title': 'Improvement of One⁃step Rollover Collision Algorithm by Optimizations of Integration and Iteration Modes',
  'name': 'Yisong Chen,Zitong Chen,Tong Wang,Yongtao Liu,Geng Luo',
  'date': '2021-10-25',
  'keywords': 'one?step rollover collision algorithm,integration point mode,reduced integration,gene?ralized unbalanced force,weighting factor,',
  'abstract': 'In view of the poor calculation accuracy and low efficiency of the initial algorithm of one-step rollover collision due to the tremendous computing efforts in in-plane four-point integration of Mindlin shell element， the irrational iteration mode of generalized unbalanced force and being prone to shear lock， the initial algorithm is optimized from two aspects in this paper. For the optimization of element integration point mode， both in-plane reduced integration and partial reduced integration are introduced， and three integration schemes， i.e. five point-， seven point- and nine point integrations are adopted along the direction of element thickness， which is then matched with in-plane integration. For the iteration mode optimization of generalized unbalanced forces， the separate weighting factor is defined for force and moment， respectively， to calculate the “2” norm of unbalanced force， and by means of calculation time-weighting factor ratio curve， the reasonable weighting factors for both force and moment are determined. Finally， the typical segment of a coach body is chosen as real calculation example， the results of improved algorithm， initial algorithm， LS-DYNA analysis and rollover test are compared， verifying the effectiveness of the improved scheme proposed.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.010'},
 {'title': 'Research on Identification and Evaluation Methods of Vehicle Crash Aggressiveness Based on MPDB Test',
  'name': 'Haitao Zhu,Zhendong Sun,Jialin Yang,Zhigang Huang',
  'date': '2021-10-25',
  'keywords': 'vehicle body structure,MPDB test,crash aggressiveness,aluminum honeycomb deformation,',
  'abstract': 'In view of that in Euro NCAP 2020， ODB test is replaced by MPDB test， and in the evaluation method of vehicle crash compatibility newly introduced， the transmission path and acting height of crash force cannot be monitored and identified， and the overall stiffness of vehicle frontend cannot be quantitatively evaluated， an evaluation strategy for the aggressiveness of vehicle frontend structure is proposed with consideration of the influencing factors of crash compatibility reflected by traffic accidents. Through the analysis on the energy absorbing theory of MPDB barrier， the evaluation regions of aluminum honeycomb are redivided， and so the corresponding evaluation indicator is put forward for each evaluation region， the monitoring and identifying method for the transmission path of crash force are obtained and the evaluation indicator and its implementation method of barrier energy absorption ratio correlated to the overall stiffness of vehicle are given.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.011'},
 {'title': 'Vehicle Safety Performance Improvement Based on Coupling Between Crash Waveform and Restraint System',
  'name': 'Hongbin Tang,Ledan Liu,Junyuan Zhang',
  'date': '2021-10-25',
  'keywords': 'crash waveform,occupant restraint system,coupling relationship evaluation,structure improvement,',
  'abstract': 'In the process of vehicle frontal crash， the coupling effect between body structures and restraint system directly affects occupant injuries. By combining theory and experience and using the evaluation method of the coupling relationship between crash waveform and restraint system， an analysis on the coupling relationship between the body structure and restraint system of a B-class passenger car is conducted， with body energy-absorbing structure and occupant restraint system modified. Final results indicate that the frontal crash star rating of that car is raised from three stars to five stars， effectively enhancing the safety performance of the vehicle.',
  'link': 'https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2021.10.012'},
 {'title': 'Forming Technologies and Crashworthiness Analysis of Automotive Tailor Welded B-pillar',
  'name': 'Binbing Huang,Shaopeng Li,Shucai Xu',
  'date': '2021-10-25',
  'keywords': 'tailor welded B-pillar,forming technologies,crashworthiness analysis,',

In [2]:
import pandas as pd

In [156]:
df = pd.DataFrame(dataset)

In [148]:
pd.set_option("display.max_colwidth", None)
df.tail(20)

,title,name,date,keywords,abstract,link
1905,Experimental and Numerical Analysis of Impact Resistance of Polyurea-Coated Aluminum Longitudinal Beams,"Hui Wang,Yang Zhao,Jinbo Zhou,Haifeng Jin,Jiajian Cao,Chao Liu",2025-12-19,"cast aluminum longitudinal beam,polyurea coatings,finite element analysis,impact property,",To meet the dual demand of lightweight design and crash safety performance improvement in passenger vehicles， in this study the synergistic reinforcement mechanism of polyurea coating thickness （0-7 mm） and interface strength （6 - 14 MPa） on the impact resistance of a one-piece die-cast aluminum rail that directly carries longitudinal loads is investigated. Through material-level static and dynamic tensile tests on polyurea， interfacial double cantilever beam （DCB） tests， and component-level quasi-static and dynamic crush tests on the rails， combined with a three-dimensional finite element model built on the LS-DYNA platform， multi-dimensional validation and parametric analysis of the coating are conducted. The results show that polyurea exhibits significant strain rate hardening behavior. When the coating thickness is 6 mm， the impact peak load of the rail can be increased by 16.53%. However， parameter analysis reveals that a thickness of approximately 3 mm achieves optimal energy absorption efficiency. The interface strength of around 12 MPa provides the best energy transfer efficiency， while insufficient strength may lead to interfacial delamination. The comparison between simulation and experimental results shows that the error in peak impact force is controlled within 10%， with highly consistent failure modes observed. In conclusion， by appropriately matching the polyurea coating thickness and interface strength， the load-bearing capacity， energy absorption efficiency， and structural integrity （e.g.， reduced fragment scattering） of the rail can be effectively enhanced， while improving deformation behavior during impact and suppressing local brittle fracture and buckling instability， thereby providing both theoretical support and engineering guidance for the coordinated design of automotive lightweight and safety.,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.12.017
1906,Multi-Level Topology Optimization Design of Aluminum Alloy Vehicle Frames Driven by Internet of Vehicles Big Data,"Zihao Meng,Dengfeng Wang,Xiaopeng Zhang,Yenan Ni,Yongfei Wang,Weiguang Wang",2025-12-19,"aluminum alloy frame,topology optimization,lightweight,weight coefficient,internet of vehicles big data,",In order to improve the lightweight level of electric commercial vehicles， in this paper a multi-level and multi-condition topology optimization design method is proposed for the aluminum alloy frame driven by Internet of Vehicles （IoV） big data. Firstly， the big data of the IoV is analyzed to obtain the proportion of working conditions to determine the objective weight， and the subjective weight is obtained through the Analytic Hierarchy Process （AHP）. Subsequently， a game theory approach integrates these weights through compromise programming to normalize conditions， establishing a multi-condition topology optimization objective function. Then， taking an aluminum alloy frame of a tractor as the research object， the Solid Isotropic Material with Penalization （SIMP） method is used to carry out the overall multi-condition topology optimization design of the first level of the frame， and the number and relative position information of the beams are obtained. Finally， the multi-body dynamic model is used to extract the multi-condition loads between the longitudinal and cross beams， and the second level cross beam section topology optimization is carried out on the frame， leading to the extraction of the cross-section shape of the cross beam. The results show that after topology optimization， the weight of the frame is reduced by 31.4% on the premise of performance improvement.,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.12.018
1907,Active Learning Kriging Based Structural Reliability Analysis Method and Application,"Hui Lü,Weijie Yan,Xiaoting Huang",2025-12-19,"reliability analysis,Kriging model,learning function,limit state surface,active learning,",For the problems of low computational accuracy and efficiency in the reliability analysis of complex automotive structures， an active learning Kriging reliability analysis method is proposed based on the limit state approximation and normalized response. Firstly， based on the probability density function under the assumption of Gaussian distribution and the Expected improvement criterion， the expectation of improved distance is derived when the degree of limit state surface （LSS） approximation improves， and the expected improvement index is proposed in combination with the current maximum distance. Then， considering the uncertainty of prediction， a learning function named expectation of redefined improvement （ERI） is developed based on the Kriging standard variance， which is used to adaptively increase the training samples. Next， a normalized response method is introduced to optimize the convergence threshold， which effectively alleviates the instability of dimensional convergence criteria. Finally， the effectiveness of the proposed method is verified through four application examples. The results show that the proposed method can achieve strong fitting of LSS with fewer function calls， with good applicability in multiple reliability analysis scenarios.,https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2025.12.019
1908,A Study on Finite Element Analysis and Structural AssessmentMethod for Aluminum-alloy Vehicle Body,"Wang Wanlin, Xu Congchang, Wang Zhenhu, Wang Zheyang, Li Luoxing",2019-07-03,"aluminum vehicle body,finite element analysis,generalized structure stiffness,structure assessment method,lightweighting,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t aluminum vehicle body, \n\t \t \t\t\t\t\t\t\t\t\t\t\t finite element analysis, \n\t \t \t\t\t\t\t\t\t\t\t\t\t generalized structure stiffness, \n\t \t \t\t\t\t\t\t\t\t\t\t\t structure assessment method, \n\t \t \t\t\t\t\t\t\t\t\t\t\t lightweighting \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.001
1909,Multi-Fuzzy Control Based Energy Management Strategy ofBattery/Super-capacitor Hybrid Energy System of Electric Vehicles,"Yao Dizhao, Xie Changjun, Zeng Tian, Huang Liang",2019-07-03,"battery/super-capacitor hybrid energy electric vehicle,energy management strategy,multi fuzzy control,modified fuzzy control strategy based on pulse modulation,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t battery/super-capacitor hybrid energy electric vehicle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t energy management strategy, \n\t \t \t\t\t\t\t\t\t\t\t\t\t multi fuzzy control, \n\t \t \t\t\t\t\t\t\t\t\t\t\t modified fuzzy control strategy based on pulse modulation \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.002
1910,Energy Management Strategy Optimization of Hybrid Energy StorageSystem Based on Radau Pseudo-spectral Method,"Liu Yanwei, Zhu Yunxue, Lin Ziyue, Zhao Kegang, Ye Jie",2019-07-03,"electric vehicle,hybrid energy storage system,pseudo-spectral method,energy management,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t electric vehicle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t hybrid energy storage system, \n\t \t \t\t\t\t\t\t\t\t\t\t\t pseudo-spectral method, \n\t \t \t\t\t\t\t\t\t\t\t\t\t energy management \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.003
1911,Effect of EGR Exhaust Gas Composition and Temperature onMechanical Characteristics of Diesel Engine Particles,"Zhao Yang, Li Mingdi, Wang Zhihao, Xu Guangju, Yuan Yinnan, Wu Bin",2019-07-03,"diesel engine,exhaust gas recirculation,particle,temperature,mechanical properties,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t diesel engine, \n\t \t \t\t\t\t\t\t\t\t\t\t\t exhaust gas recirculation, \n\t \t \t\t\t\t\t\t\t\t\t\t\t particle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t temperature, \n\t \t \t\t\t\t\t\t\t\t\t\t\t mechanical properties \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.004
1912,A Research on Hybrid Energy Storage System for Battery Electric Mining Trucks,"Zhang Wei, Yang Jue, Zhang Wenming, Ma Fei",2019-09-10,"mining truck,battery electric vehicle,battery,ultracapacitor,hybrid energy storage system,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t mining truck, \n\t \t \t\t\t\t\t\t\t\t\t\t\t battery electric vehicle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t battery, \n\t \t \t\t\t\t\t\t\t\t\t\t\t ultracapacitor, \n\t \t \t\t\t\t\t\t\t\t\t\t\t hybrid energy storage system \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.005
1913,A Study on the Influences of Grounding CharacteristicParameters on the Grip Performance of Tire,"Wang Guolin, Chen Xingpeng, Zhou Haichao",2019-07-03,"radial tire,tire grounding characteristics,dry and wet grounds,grip performance,correlation analysis,principal component analysis,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t radial tire, \n\t \t \t\t\t\t\t\t\t\t\t\t\t tire grounding characteristics, \n\t \t \t\t\t\t\t\t\t\t\t\t\t dry and wet grounds, \n\t \t \t\t\t\t\t\t\t\t\t\t\t grip performance, \n\t \t \t\t\t\t\t\t\t\t\t\t\t correlation analysis, \n\t \t \t\t\t\t\t\t\t\t\t\t\t principal component analysis \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.006
1914,A Research on Cooperative Path Tracking and Anti-roll Control ofCommercial Vehicle Based on Pareto Optimal Equilibrium Theory,"Li Yushan, Chi Yuanxin, Ji Xuewu, Liu Yulong, Wu Jian",2019-09-10,"commercial vehicle,path tracking,anti-roll control,Pareto optimal equilibrium theory,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t commercial vehicle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t path tracking, \n\t \t \t\t\t\t\t\t\t\t\t\t\t anti-roll control, \n\t \t \t\t\t\t\t\t\t\t\t\t\t Pareto optimal equilibrium theory \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.007
1915,A Research on Steering Wheel Resistance Torque of aCommercial Vehicle Based on LuGre Model,"Zhu Xianmin, Song Jian, Cheng Shuai",2019-07-03,"commercial vehicle,aligning torque,friction resistance torque,steering wheel resistance torque,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t commercial vehicle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t aligning torque, \n\t \t \t\t\t\t\t\t\t\t\t\t\t friction resistance torque, \n\t \t \t\t\t\t\t\t\t\t\t\t\t steering wheel resistance torque \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.008
1916,A Study on Vehicle Lateral Tracking Control Based on Arc-length Preview,"Li Shuang, Xu Yanhai, Chen Jing, Zhu Pengxin",2019-07-03,"vehicle,arc-length preview,path tracking,lateral control,simulation,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t vehicle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t arc-length preview, \n\t \t \t\t\t\t\t\t\t\t\t\t\t path tracking, \n\t \t \t\t\t\t\t\t\t\t\t\t\t lateral control, \n\t \t \t\t\t\t\t\t\t\t\t\t\t simulation \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.009
1917,Performance Measurement and Analysis of the Active NoiseControl System for Mass Production Vehicle,"Liu Feng, Wu Ming, Yang Jun",2019-07-03,"mass production vehicle,vehicle interior noise,active noise control,measurement and analysis,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t mass production vehicle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t vehicle interior noise, \n\t \t \t\t\t\t\t\t\t\t\t\t\t active noise control, \n\t \t \t\t\t\t\t\t\t\t\t\t\t measurement and analysis \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.010
1918,A Research on the Evaluation Method of High-frequencyWhining Noise in Electric Drivetrain,"Kang Qiang, Gu Pengyun, Li Jie, Zuo Shuguang",2019-07-03,"electric drivetrain,whining noise,evaluation,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t electric drivetrain, \n\t \t \t\t\t\t\t\t\t\t\t\t\t whining noise, \n\t \t \t\t\t\t\t\t\t\t\t\t\t evaluation \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.011
1919,A Research on Drag Reduction Effect of AerodynamicDrag Reducing Device for Van Truck,"Xu Jianmin, Fan Jianming",2019-07-03,"van type truck,bionic cab spoiler,tail fairing,bionic non-smooth surface,combined drag reducing device,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t van type truck, \n\t \t \t\t\t\t\t\t\t\t\t\t\t bionic cab spoiler, \n\t \t \t\t\t\t\t\t\t\t\t\t\t tail fairing, \n\t \t \t\t\t\t\t\t\t\t\t\t\t bionic non-smooth surface, \n\t \t \t\t\t\t\t\t\t\t\t\t\t combined drag reducing device \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.012
1920,Safety Assessment of Child Occupant Exposure to Electromagnetic Field Generated by DC Power Cable in Battery Electric Vehicles,"Dong Xuwei, Lu Mai",2019-07-03,"battery electric vehicle,electromagnetic dosimetry,child body model,magnetic flux density,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t battery electric vehicle, \n\t \t \t\t\t\t\t\t\t\t\t\t\t electromagnetic dosimetry, \n\t \t \t\t\t\t\t\t\t\t\t\t\t child body model, \n\t \t \t\t\t\t\t\t\t\t\t\t\t magnetic flux density \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.013
1921,A Study on Steady-state Performance of Winding Type Permanent Magnet Coupler in W-ECHPS System of a Heavy Vehicle,"Xia Lei, Jiang Haobin, Geng Guoqing",2019-07-03,"winding type permanent magnet coupler,electronically controlled hydraulic power steering,finite element simulation,steady-state performance,slip power recovery,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t winding type permanent magnet coupler, \n\t \t \t\t\t\t\t\t\t\t\t\t\t electronically controlled hydraulic power steering, \n\t \t \t\t\t\t\t\t\t\t\t\t\t finite element simulation, \n\t \t \t\t\t\t\t\t\t\t\t\t\t steady-state performance, \n\t \t \t\t\t\t\t\t\t\t\t\t\t slip power recovery \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.014
1922,Dimensional Stability Analysis of Polylactic-acid StructuralParts Based on Time Hardening Theory,"Ma Fangwu, Han Lu, Chen Shixian, Pu Yongfeng, Shen Liang",2019-07-03,"polylactic acid,topology optimization,creep,time hardening theory,finite element analysis,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t polylactic acid, \n\t \t \t\t\t\t\t\t\t\t\t\t\t topology optimization, \n\t \t \t\t\t\t\t\t\t\t\t\t\t creep, \n\t \t \t\t\t\t\t\t\t\t\t\t\t time hardening theory, \n\t \t \t\t\t\t\t\t\t\t\t\t\t finite element analysis \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.015
1923,Multi-objective Optimization on Structure Layout of Sliding Door Keeper,"Zhou Qiaoying, Xue Zhigang, Zhou Wufeng, Lin Qiquan, Li Luoxing",2019-07-03,"sliding door keeper,structure layout,multi-objective optimization,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t sliding door keeper, \n\t \t \t\t\t\t\t\t\t\t\t\t\t structure layout, \n\t \t \t\t\t\t\t\t\t\t\t\t\t multi-objective optimization \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.016
1924,An Analysis on Thermal Comfort in Passenger CompartmentBased on Human Thermal Regulation Model,"Chen Jiqing, Zheng Xijiao, Lan Fengchong, Peng Rui",2019-07-03,"passenger compartment,human thermal comfort,human thermal regulation model,","Key words: \n\t \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t passenger compartment, \n\t \t \t\t\t\t\t\t\t\t\t\t\t human thermal comfort, \n\t \t \t\t\t\t\t\t\t\t\t\t\t human thermal regulation model \n\t \t",https://www.qichegongcheng.com/CN/10.19562/j.chinasae.qcgc.2019.06.017

In [158]:
df.to_csv('AutomotiveEngeneering.csv',index=False)

In [157]:
df.shape

(1925, 8)

In [145]:
df['title'].value_counts()

title
                                                                                                                                  111
A Fast Multiple Maneuvering Vehicle Tracking Algorithm Based on Half Suppressed Fuzzy C⁃means Clustering                            1
Fine⁃grained Vehicle Detection and Classification Model for Video Structuring Description                                           1
Vehicle Target Oriented Bidirectional Matching Handover Method for Multi Camera on Roadside                                         1
Fast Energy⁃saving Speed Planning Through Multi Signal Intersections of Intelligent Vehicles                                        1
                                                                                                                                 ...
Safety Assessment of Child Occupant Exposure to Electromagnetic Field Generated by DC Power Cable in Battery Electric Vehicles      1
A Study on Steady-state Performance of Winding Type Permanent Magnet Coupler in  W-ECHPS System of a Heavy Vehicle                  1
Dimensional Stability Analysis of Polylactic-acid StructuralParts Based on Time Hardening Theory                                    1
Multi-objective Optimization on Structure Layout of Sliding Door Keeper                                                             1
An Analysis on Thermal Comfort in Passenger CompartmentBased on Human Thermal Regulation Model                                      1
Name: count, Length: 1797, dtype: int64

In [5]:
df = pd.read_csv('AutomotiveEngeneering.csv')

In [47]:
df_ad=df[df['abstract'].str.contains('autonomous driving|\bADAS\b|\bE2E\b|End to End|\bVLA\b|\bVLM\b')]

In [48]:
df_ad.shape

(83, 8)

In [49]:
df_ad.head(5)

,title,title_en,name,date,keywords,abstract,link,id
60,基于特征融合的多层次多模态目标检测,Multi-level and Multi-modal Target Detection B...,"Teng Cheng,Lei Sun,Dengchao Hou,Qin Shi,Junnin...",2021-11-22,"autonomous driving,environmental perception,hi...",For the problems of low robustness of the envi...,https://www.qichegongcheng.com/CN/10.19562/j.c...,61
203,基于级联YOLOv7的自动驾驶三维目标检测,Autonomous Driving 3D Object Detection Based o...,"Dongyu Zhao, Shuen Zhao",2023-07-25,"3D object detection,YOLOv7,F-PointNet,multi-se...",For the problems of incomplete feature informa...,https://www.qichegongcheng.com/CN/10.19562/j.c...,204
347,飞行汽车关键技术及应用研究综述,A Review of Key Technologies and Application o...,"Jiaxin Ma,Zhihong Wang,Zhuo Liu,Zongyang Li,Bi...",2025-11-28,"flying car,electrification,propulsion system,a...",As a three-dimensional expansion of automobile...,https://www.qichegongcheng.com/CN/10.19562/j.c...,348
408,面向人机共驾模式下驾驶人接管过程的视觉转移特性研究,Study on Driver's Visual Transfer Characterist...,"Mengfan Li,Zhongxiang Feng,Weihua Zhang,Jingyu Li",2024-05-17,"autonomous driving,human-computer interaction,...",When the driver is not required to supervise t...,https://www.qichegongcheng.com/CN/10.19562/j.c...,409
409,ADAS系统视觉与毫米波雷达分布式抗差卡尔曼滤波融合算法,Vision and Radars Fusion Algorithm Based on Di...,"Yunhong Deng,Zhiguo Zhao,Yifei Yang,Qin Yu",2024-05-17,"multi-target detection and tracking,sensor inf...",Autonomous vehicles often use multiple sensors...,https://www.qichegongcheng.com/CN/10.19562/j.c...,410

In [50]:
df_ad["date"] = pd.to_datetime(df_ad["date"], errors="coerce")

df_ad["year"] = df_ad["date"].dt.year
df_ad["month"] = df_ad["date"].dt.month
df_ad["day"] = df_ad["date"].dt.day

In [51]:
df_ad.value_counts('year',ascending=False)

year
2024    22
2023    18
2026    17
2025    11
2021     7
2022     7
2020     1
Name: count, dtype: int64

In [43]:
df_nev=df[df['abstract'].str.contains('electric vehicle|\bEV\b|New energy vehicle|a\bPHEV\b')]

In [44]:
df_nev.shape

(176, 8)

In [45]:
df_nev["date"] = pd.to_datetime(df_nev["date"], errors="coerce")

df_nev["year"] = df_nev["date"].dt.year
df_nev["month"] = df_nev["date"].dt.month
df_nev["day"] = df_nev["date"].dt.day
df_nev.value_counts('year',ascending=False)

year
2023    30
2025    27
2021    26
2024    24
2022    24
2020    15
2019    13
2018     9
2026     8
Name: count, dtype: int64